### ISSUE TITLE
Remove additional registry keys

### ISSUE THREAD

**Issue by ericfowler303** [10se1ucgo/DisableWinTracking#1]
![clfwb41usaakeki png large](https://cloud.githubusercontent.com/assets/8892211/9047324/6b29f4f8-39ee-11e5-9bc5-54a1492e42ce.png)
These might be some extra registry keys to remove in addition to the current set.

**Comment by 10se1ucgo** [comment]
I'll look into these.

**Comment by ReklatsMasters** [comment]
and this task
`\Microsoft\Windows\DiskDiagnostic\Microsoft-Windows-DiskDiagnosticDataCollector`
