### ISSUE TITLE
Access is denied for Windows Defender 

### ISSUE THREAD

**Issue by mzayn** [10se1ucgo/DisableWinTracking#100]
**INFORMATION:**

"Access is denied" regarding Windows Defender 

**LOG:**

13:45:17 INFO: Performing clutter control

13:45:42 INFO: DiagTrack box ticked

13:45:42 INFO: Service disable option ticked

13:45:42 INFO: DisableWinTracking Version: v2.5.1

13:45:42 INFO: Mode: Privacy

13:45:42 INFO: Telemetry box ticked

13:45:42 INFO: Host box ticked

13:45:42 INFO: Extra host box ticked

13:45:42 INFO: IP block box ticked

13:45:43 INFO: Defender/Wifisense box ticked

13:45:43 ERROR: Registry: Unable to modify Windows Defender Spynet key.
Traceback (most recent call last):
  File "<string>", line 575, in modifyregistry
WindowsError: [Error 5] Access is denied

13:45:43 ERROR: Registry: Unable to modify Windows Defender Sample Submission key.
Traceback (most recent call last):
  File "<string>", line 575, in modifyregistry
WindowsError: [Error 5] Access is denied

```

**Comment by 10se1ucgo** [comment]
Known issue, we're working on it.
