### ISSUE TITLE
Does not disable some spying in v2.5.1

### ISSUE THREAD

**Issue by Baigle** [10se1ucgo/DisableWinTracking#104]
**INFORMATION:**

Windows Edition (Home/Pro/Enterprise): Win10 Pro
Architecture (32bit/64bit): 64bit
Options used: Services, Clear DiagTrack log, Telemetry, Block tracking domains, Block even more tracking domains, Block tracking IP addresses, Stop Defender/Wifisense Data Collection, Uninstall OneDrive

**LOG:**

```python
01:18:59 INFO: Performing clutter control

01:18:59 ERROR: Clutter control: Could not remove domains.
Traceback (most recent call last):
  File "<string>", line 613, in modifyhostfile
WindowsError: [Error 5] Access is denied: 'C:\\WINDOWS\\System32\\drivers\\etc\\hosts'

01:18:59 ERROR: Extra domain clutter control: Could not remove domains.
Traceback (most recent call last):
  File "<string>", line 613, in modifyhostfile
WindowsError: [Error 5] Access is denied: 'C:\\WINDOWS\\System32\\drivers\\etc\\hosts'

01:19:01 INFO: DiagTrack box ticked

01:19:01 INFO: Service disable option ticked

01:19:01 INFO: DisableWinTracking Version: v2.5.1

01:19:01 INFO: Mode: Privacy

01:19:01 INFO: Telemetry box ticked

01:19:01 INFO: Host box ticked

01:19:01 ERROR: Domain block: Could not append domains
Traceback (most recent call last):
  File "<string>", line 599, in modifyhostfile
IOError: [Errno 13] Permission denied: 'C:\\WINDOWS\\System32\\drivers\\etc\\hosts'

01:19:01 INFO: Extra host box ticked

01:19:01 ERROR: Extra domain block: Could not append domains
Traceback (most recent call last):
  File "<string>", line 599, in modifyhostfile
IOError: [Errno 13] Permission denied: 'C:\\WINDOWS\\System32\\drivers\\etc\\hosts'

01:19:01 INFO: IP block box ticked

01:19:03 INFO: Defender/Wifisense box ticked

01:19:03 ERROR: Registry: Unable to modify Windows Defender Spynet key.
Traceback (most recent call last):
  File "<string>", line 575, in modifyregistry
WindowsError: [Error 5] Access is denied

01:19:03 ERROR: Registry: Unable to modify Windows Defender Sample Submission key.
Traceback (most recent call last):
  File "<string>", line 575, in modifyregistry
WindowsError: [Error 5] Access is denied

01:19:03 INFO: OneDrive box ticked
```

Winstore.mobile.exe sends M$ data, WpnService for Windows Push Notifications through explorer.exe does not get disabled and does not have an option to be disabled, App Connector is not obvious as to the reason you would want to uninstall it and is not listed, Windows SearchUI.exe setting for not searching Bing every time is not accessible under normal settings to my knowledge (could put in program).

Thanks for checking this out, I like what this program is trying to do and support the creator for sticking up to M$ for stealing an ungodly amount of sensitive and private information from its hundreds of millions of users.

**Comment by Baigle** [comment]
And this: http://www.digitalmunition.me/2015/06/how-microsoft-can-spy-on-you-and-how-to-stop-it/

What exactly does it block besides the specific options listed on the program?

**Comment by Ruined1** [comment]
@Baigle I believe some of these issues were fixed in recent commits, need to wait for developer to increment the version number and compile a new binary. We'll look into your sources and see what we can add. Thanks for participating =)

**Comment by Baigle** [comment]
Sweet, thanks!

**Comment by Ruined1** [comment]
@10se1ucgo the only thing that has me worried here, why would access to the host file be denied?

**Comment by jmdbox** [comment]
I think his hosts file must be set to read only, otherwise some other wrong permissions could be set on it.  Only saying because i am still in the old habit of setting a custom hosts file (just a very few things i like to add to it) and then setting the read-only attribute, and i got the same error when i forgot to clear the read-only attribute from it prior to running the DisableWinTracking.

**Comment by Ruined1** [comment]
Ah, well if that's the case then this is solved. I'll close it once I have a chance to research your sources from above and add anything we may not yet have.

**Comment by Baigle** [comment]
![capture](https://cloud.githubusercontent.com/assets/1761404/10510245/7180bcf0-72f7-11e5-897d-b32a22304e70.JPG)
This might be the problem... lol

**Comment by Baigle** [comment]
After I remove the extra files, remove read-only flag, and sec security permissions to allow administrators and my user account full read and write access it still gives: 

04:50:43 INFO: Performing clutter control

04:50:43 ERROR: Clutter control: Could not remove domains.
Traceback (most recent call last):
  File "<string>", line 613, in modifyhostfile
WindowsError: [Error 5] Access is denied: 'C:\\WINDOWS\\System32\\drivers\\etc\\hosts'

04:50:44 ERROR: Extra domain clutter control: Could not remove domains.
Traceback (most recent call last):
  File "<string>", line 613, in modifyhostfile
WindowsError: [Error 5] Access is denied: 'C:\\WINDOWS\\System32\\drivers\\etc\\hosts'

04:50:44 INFO: DisableWinTracking Version: v2.5.1

04:50:44 INFO: Mode: Privacy

04:50:44 INFO: Host box ticked

04:50:44 ERROR: Domain block: Could not append domains
Traceback (most recent call last):
  File "<string>", line 599, in modifyhostfile
IOError: [Errno 13] Permission denied: 'C:\\WINDOWS\\System32\\drivers\\etc\\hosts'

04:50:44 INFO: Extra host box ticked

04:50:44 ERROR: Extra domain block: Could not append domains
Traceback (most recent call last):
  File "<string>", line 599, in modifyhostfile
IOError: [Errno 13] Permission denied: 'C:\\WINDOWS\\System32\\drivers\\etc\\hosts'

**In the past I've only been able to get HOSTS file changes to work by copying a corrected version back into the directory and replacing the original, keeping what was in it and adding the new lines beforehand.

**Comment by jmdbox** [comment]
@Baigle Could it be possible your security software is denying changes?  What security/av software are you running?

**Comment by Ruined1** [comment]
@Baigle like jdmbox said, a LOT of AV software prevents hosts file changes, try temporarily disabling any AV software and run DWT again

**Comment by Baigle** [comment]
It was just the security permissions on the file I tried editing it again today... but without those permission changes it wasn't editable without copying, editing copy, and replacing old copy in that directory.

**Comment by Baigle** [comment]
My deepest apologies. I tried again on another system I had and found the reason you specified to be true. I had a variety of different configurations designed to protect the other system and realized that after disabling one of the stragglers on the second machine (not even windows 10, mind you) the software wrote the hosts file correctly.

**Comment by 10se1ucgo** [comment]
Should be fixed.
