### ISSUE TITLE
Replace with a short description of your problem

### ISSUE THREAD

**Issue by walkman1943** [10se1ucgo/DisableWinTracking#105]
11:19:17 ERROR: Registry: Unable to modify Windows Defender Spynet key.
Traceback (most recent call last):
  File "<string>", line 575, in modifyregistry
WindowsError: [Error 5] Access is denied

11:19:18 ERROR: Registry: Unable to modify Windows Defender Sample Submission key.
Traceback (most recent call last):
  File "<string>", line 575, in modifyregistry
WindowsError: [Error 5] Access is denied

**Comment by 10se1ucgo** [comment]
Known issue, @Ruined1 has a fix, I just need to pack a binary when I'm free.

**Comment by walkman1943** [comment]
Not sure where I go from here. Is there a modified edition of the program available that I need to download and install? Thanks for your help.

**Comment by Ruined1** [comment]
@walkman1943 As the Head Developer stated, he needs to pack a new binary. What this means is that we have already fixed the programs source code, if you new how to run the program from source, you could already run the latest version. However, if you dont you need to wait for him to pack that new binary (create a new .exe file from the source code) and upload it for you to download and run :+1:
