### ISSUE TITLE
I can't restore correctly search/data collecting service

### ISSUE THREAD

**Issue by psychok9** [10se1ucgo/DisableWinTracking#106]
I've tried to restore original settings, but it doesn't work at 100%.
Also after a reboot, "send your data to Microsoft" on the "diagnostic & feedback" menu still grey.
Obviously I selected "disable" on service method.
I don't know if others components still disabled.

Log:
Services: dmwappushsvc key successfully modified.
Services: DiagTrack key successfully modified.
Telemetry: AllowTelemetry key successfully modified.
Domain block: Domains successfully removed.
Extra domain block: Domains successfully removed.
IP Blocking: Succesfully unblocked.
WifiSense/Defender: Unable to modify Windows Defender Spynet key.
WifiSense/Defender: Unable to modify Windows Defender Sample Submission key.
WifiSense/Defender: WifiSense Open-ness key successfully modified.
WifiSense/Defender: WifiSense Credential Share key successfully modified.
WifiSense/Defender: Windows Defender Delivery Optimization Download key successfully modified.
Done. It's recommended that you reboot as soon as possible for the full effect.
If you feel something didn't work properly, please press the 'Report an issue' button and follow the directions

p.s. If I type on admin cmd prompt: *sc start DiagTrack*, I get something like "Unable to turn on the service, no active associated device or the service is disabled".

**Comment by 10se1ucgo** [comment]
Hmm. Try going to `gpedit.msc>Computer Configuration>Administrative Templates>Windows Components>Data Collection and Preview Builds` and set `Allow Telemetry` to any value besides `0`.

**Comment by psychok9** [comment]
I'm sorry... no time.
I tried your change, I did the reboot, but the setting still grey.

**Comment by 10se1ucgo** [comment]
Hmm. Very weird. I'm not really sure whats going on here.

**Comment by psychok9** [comment]
Ok... I played with Allow Telemetry, set to 1, and after disabled the control from gpedit.msc. Now I can start the service and seems work :)
