### ISSUE TITLE
DisableWinTracking not oppening

### ISSUE THREAD

**Issue by novarro** [10se1ucgo/DisableWinTracking#107]
I downloaded the latest version 2.5.1 on a samsung ultrabook with a windows 10 home and when I open it as an administrator after I confirm that I want to open it nothing happens! Same think if I try to run directly(not as an administrator)! What should I do?

**Comment by CooKino** [comment]
Same problem here with Windows 10 Pro x64.

**Comment by Ruined1** [comment]
@CooKino make/model? is yours also an ultra book?

I'm curious to know, because you two are the only two to report this issue. Maybe it's something specific we need to look at.

**Comment by CooKino** [comment]
It's a hand-maked PC, my configuration, if it can help: i7 4770, 8Gb RAM, GTX 970, Windows 10 Pro x64 installed on my SSD...
I moved "disablewindowstracking.exe" on my desktop, and it works! @novarro you can try this!

**Comment by Ruined1** [comment]
@CooKino Yea, and unfortunately that's not something we can affect. Microsoft is always limiting their users more and more... Anything executable, always try opening it from the desktop or your user's folder (which the desktop happens to be part of, C:\Users\<User>\Desktop)

@10se1ucgo perhaps we should error-proof this by adding something to the instructions on how to use it.

**Comment by novarro** [comment]
but it is on the Desktop!

**Comment by 10se1ucgo** [comment]
May be related to #112 

Is the download folder you're running it from restricted in some way? (Read only, protected, etc.)

**Comment by 10se1ucgo** [comment]
No response.
