### ISSUE TITLE
A Trojan in .exe ?

### ISSUE THREAD

**Issue by Petrouchka** [10se1ucgo/DisableWinTracking#11]
https://www.virustotal.com/fr/file/0aca5aaa66a8029d533415b104348cda0c45775567a371585c6b5596a965c168/analysis/1439015508/

**Comment by Agazed** [comment]
This program has to write/read/delete to system files, which is common behavior of a trojan, causing some AV's to think it's a trojan.

**Comment by 10se1ucgo** [comment]
@Agazed is correct.

If you're still skeptical, you can unfreeze/decompile the exe with pyinstaller and personally inspect the code.
