### ISSUE TITLE
Reinstalling apps does not actually work (*yet*)

### ISSUE THREAD

**Issue by 10se1ucgo** [10se1ucgo/DisableWinTracking#113]
The command we're using to reinstall all of the default apps doesn't actually work. This can be solved by changing the command to installing all of the packages found in `%SYSTEMROOT%\InfusedApps\Packages.`

There is one problem however, each app seems to have multiple folders with its own AppManifest.xml file. There is one folder for each app with either x86/x64, and other folders with things such as neutral_split.scale-125/140/150/180/200.

Not sure what the proper way to deal with this is.

**Comment by NikhajZzz** [comment]
I've accidentaly clicked to reinstall all default apps and now nothing is working. There should be a warning message and having a choice to cancel or apply the operation. I've tried all the night to repair the store, calculator, note, weather...apps but nothing can be reinstalled from powershell. Got red errors. There is actually no solution to repair the problems that DWT causes. Clean boot or reinstall windows?

**Comment by 10se1ucgo** [comment]
The warning is there, in the license. Here's an excerpt.

`Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.`

**Comment by NikhajZzz** [comment]
Ok :) And who reads the license today? I know user use this sofware at own risk, no problem....but i still think a warning message should help. See how much people destroyed their OS :) I've done a clean install on my PC and heaven't found any answer for people here, how to repair their damaged OS.

**Comment by Ruined1** [comment]
@NikhajZzz Quote: `Ok :) And who reads the license today?`

People of intelligence.

Closing this and I will add a message to "warn people of the dangers of removing integrated system applications" as obvious as that should be.

**Comment by Ruined1** [comment]
I removed it all together since it wasn't functioning properly anyways.
