### ISSUE TITLE
Run As Admin - Require Admin Rights Via Manifest

### ISSUE THREAD

**Issue by war59312** [10se1ucgo/DisableWinTracking#115]
Hey,

"RUN AS ADMINISTRATOR!

I cannot stress this enough, not running the program as an administrator will result in none of the tweaks being applied."

OK, then just make it run as admin every time automatically using a manifest file with requireAdministrator.

See: https://msdn.microsoft.com/en-us/library/bb756929.aspx

I'm talking about the binary of course. And put a check in to be sure app as admin rights. Lots of examples out there.

Thanks,

Will

**Comment by 10se1ucgo** [comment]
Already been done.

**Comment by war59312** [comment]
Ok, cool. Perhaps remove those FUD warning then, so you can not as admin in the first place now. ;)

**Comment by 10se1ucgo** [comment]
Will do.
