### ISSUE TITLE
Replace dependencies with dependencies located in github or another free hostings (not on sourceforge)

### ISSUE THREAD

**Issue by firefoxForUser** [10se1ucgo/DisableWinTracking#116]
Replace dependencies with dependencies located in github or another free hosting (not on sourceforge)

**Comment by Ruined1** [comment]
I'm afraid I don't understand what you're asking?

**Comment by Draxler** [comment]
As far as i uderstand; @FirefoxForUser is asking that you should use Github as a source for dependencies not Sourceforge. And Dependencies already used from Sourceforge to be replaced with Dependencies from other free sources or Dependencies from Github. The main concerne here is the Sourceforge as source for Dependencies.

**Comment by 10se1ucgo** [comment]
That's not possible. Those are the official websites for wxPython and PyWin32. You'll have to ask Robin Dunn and Mark Hammond respectively.

**Comment by 10se1ucgo** [comment]
Though, wxPheonix (new implementation of wxPython, also compatible with Python 3) IS indeed located on GitHub, [here](https://github.com/wxWidgets/Phoenix).
