### ISSUE TITLE
Adding 'ui.skype.com' to the hosts disables some Skype features

### ISSUE THREAD

**Issue by DmitriyYukhanov** [10se1ucgo/DisableWinTracking#117]
I'm not sure why you have this included, but it totally prevents Skype updates and blocks other things in Skype, like the home page.

Would be nice to have it excluded initially to not harm Skype users.

**Comment by Ruined1** [comment]
The ui.skype.com entry is included in the "Block even more tracking domains" checkbox. Which according the code, specifically puts up a prompt:

> This option could potentially prevent you from using one or more of the following services:
>
> Skype, Hotmail, Dr. Watson, Error Reporting.
> Continue?

You must answer yes for the box to even get checked. Did you completely ignore this prompt? Or did you use an old version of DWT?

**Comment by DmitriyYukhanov** [comment]
Oh, looks like I missed that prompt or used older version.
Thanks for the clarification!

**Comment by Ruined1** [comment]
Glad I could help.

@10se1ucgo might be time to publish a new release?
