### ISSUE TITLE
[v2.5.1] Unable to modify Windows Defender keys

### ISSUE THREAD

**Issue by Jan02** [10se1ucgo/DisableWinTracking#118]
02:55:04 ERROR: Registry: Unable to modify Windows Defender Spynet key.
Traceback (most recent call last):
  File "<string>", line 575, in modifyregistry
WindowsError: [Error 5] Access is denied

02:55:04 ERROR: Registry: Unable to modify Windows Defender Sample Submission key.
Traceback (most recent call last):
  File "<string>", line 575, in modifyregistry
WindowsError: [Error 5] Access is denied

**Comment by 10se1ucgo** [comment]
This is due to Windows protecting the Windows Defender keys. I'll look for a work around soon.
