### ISSUE TITLE
GUI truncated if display DPI is not 96/default

### ISSUE THREAD

**Issue by Warudo** [10se1ucgo/DisableWinTracking#119]
If the display DPI is set higher the default of 96, the font size is scaled up, but the Window size isn't. 
Some options become unselectable.

![Example](https://cloud.githubusercontent.com/assets/1916368/11170738/3d4822d0-8bdd-11e5-8c66-0fc579030431.png)

**Comment by 10se1ucgo** [comment]
I can fix this by using `wx.BoxSizer`s but I absolutely hate them and it's annoying to get them to be in the layout I want.

 I'll see what I can do.

**Comment by 10se1ucgo** [comment]
Finally got around to start doing this, #153

**Comment by 10se1ucgo** [comment]
Should be fixed.
