### ISSUE TITLE
DiagTrack log and service.

### ISSUE THREAD

**Issue by deadscreem** [10se1ucgo/DisableWinTracking#12]
The short name for "Diagnostics Tracking Service" is actually "DiagTrack".

The problem happens on the first run and when selecting everything. It tries to clear and lock the "DiagTrack" log before it stops and disables the "DiagTrack" service. So it fails to clear the log because it's still in use. You have to stop the "DiagTrack" service before clearing the log.

Also, you may want to look into stopping and disabling the Geolocation Service (lhsvc is the short name)

**Comment by 10se1ucgo** [comment]
Thanks, I'll look into this.
