### ISSUE TITLE
Error with function

### ISSUE THREAD

**Issue by Ruined1** [10se1ucgo/DisableWinTracking#120]
I wiped my computer, so I'm unable to fix it at the moment, but
[Line 439](https://github.com/10se1ucgo/DisableWinTracking/blob/master/run.py#L439) of run.py is wrong according to [Line 451](https://github.com/10se1ucgo/DisableWinTracking/blob/master/run.py#L451)

[Line 439](https://github.com/10se1ucgo/DisableWinTracking/blob/master/run.py#L439) needs to provide 2 arguments, not one.

**Comment by 10se1ucgo** [comment]
Fixed.
