### ISSUE TITLE
bing.com blocked

### ISSUE THREAD

**Issue by Jaglag** [10se1ucgo/DisableWinTracking#121]
Hi 
i need bing.com unblocked cause i need the webmaster tools.
I already try to unblock the telemetry.bing but its still not possible to enter the page.
Which thinks i have to unblock to reach bing again?

**Comment by lenisko** [comment]
Disable __TrackingIP204.79.197.200__ rule in Windows Firewall

**Comment by Jaglag** [comment]
ty
