### ISSUE TITLE
Uninstalling apps causes collateral damage 

### ISSUE THREAD

**Issue by luisvsm** [10se1ucgo/DisableWinTracking#123]
I removed some of the apps listed (from memory it was Calendar & Mail, Get Office/Skype/Started, Groove, Maps, Money, Movies & TV, News, OneNote, People, Phone Companion and Sports) and my Calculator/Windows Store/camera app seem to have been removed with them.

My calculator now looks like this and are no longer clickable:
![My Calculator](https://cloud.githubusercontent.com/assets/2926160/11370113/50ee4b30-9316-11e5-87f8-d3e89b9dde08.PNG)

And this is my Windows store:
![My windows store](https://cloud.githubusercontent.com/assets/2926160/11370128/60a3da72-9316-11e5-8f4a-6ef091ab5e03.PNG)

I've tried the reinstall original app functionality a couple of times but it doesn't seem to work. (probably related to this ticket: https://github.com/10se1ucgo/DisableWinTracking/issues/113 ).

So after that failed I tried to uninstall the old packages manually with the hopes of manually reinstalling them:
![Calculator AppxPackage details](https://cloud.githubusercontent.com/assets/2926160/11370233/e63a4996-9316-11e5-9ca6-e8767bf9feac.PNG)

But ran into the following error:
![Now trying to remove it myself for reinstall](https://cloud.githubusercontent.com/assets/2926160/11370226/e0ba8a3a-9316-11e5-9d4e-eca9931d5c65.PNG)

A log file was created next to the DisableWinTracking executable but it's empty.

**Comment by Ruined1** [comment]
I cannot reproduce this issue after reinstalling a fresh copy of Windows 10 x64 and running uninstall on the latest release of dwt. My calculator is working fine. What version of 10 are you using, also see about section of dwt, which version of dwt are you using?

**Comment by Ruined1** [comment]
Keep in mind i applied all fixes, deleted services, and uninstalled all apps

**Comment by Jaglag** [comment]
i have same problem no store here anymore for me:

http://prntscr.com/96vcpx

**Comment by Jaglag** [comment]
![screenshot_1](https://cloud.githubusercontent.com/assets/6708499/11406259/b45c1fd0-93ac-11e5-82a4-d9debce6d98c.jpg)


:(

**Comment by refractionpcsx2** [comment]
Leaving "money" installed leaves the calculator, I can confirm uninstalling this removes the windows calculator as well. If you must remove the money component, you can download the "classic" windows 7 calc from here http://winaero.com/blog/get-calculator-from-windows-8-and-windows-7-in-windows-10/

**Comment by luisvsm** [comment]
Sorry about the delayed followup, I'll have another go at diagnosing/troubleshooting and reproducing the issue.

**Comment by refractionpcsx2** [comment]
I don't think this is your error as using some scripts to do it I found somewhere else also removed the calculator, it may be just a case of updating the labels

**Comment by luisvsm** [comment]
Here's the version that I used:
![version](https://cloud.githubusercontent.com/assets/2926160/11498202/107fc810-9872-11e5-8983-f3f393ce5340.PNG)

I just did another revert on all of the services and reboot for good measure, then selected all apps and clicked Reinstall original apps, without any luck (opened as an elevated process).

Still no DisableWinTracking log, and no relevant Event Viewer logs from what I can tell.

If you can think of any other meaningful information/help I can give you give me a yell. Otherwise don't worry about it this windows 10 install is only a fortnight old so it'll be a peace of piss to reinstall.

Thanks heaps for the quick response and sorry again it took a week for me to get back to you!

**Comment by NikhajZzz** [comment]
Had the same problem, the powershell method wont work. I have tried to kill explorer.exe and use the powershell, tried to change the ownership of the apps directory, tried safe mode....none of them works.  Somewhere on the forums i saw a message, the powershell wont work because the apps on the systems are newer then the apps that users try to reinstall - because they are updated... Program Files is not the only one directory where these apps are. You can find some of these somwehere in %systemroot% too.... Finally i have reinstalled the windows... at least the system is clean now :D

**Comment by 10se1ucgo** [comment]
#113
