### ISSUE TITLE
Some settings are managed by your organization

### ISSUE THREAD

**Issue by arnstein99** [10se1ucgo/DisableWinTracking#126]
In several panels of the Microsoft **Settings** program, I am seeing a message in red text *Some settings are managed by your organization*. My copy of Windows 10 is the Home version and there is no managing organization except me.

I am also seeing that some menu items in Settings/Privacy and Settings/Windows Update are greyed out and inaccessible. The red text is visible in the relevant panels. Also, I have one peecee that is not able to update to build 1511 of Windows 10. The Settings program tells me that no updates are available.

A Google search for that phrase *Some settings...* indicates that there is a link between programs similar to **DisableWinTracking** and Windows 10 Home. I speculate that these sorts of programs are incompatible with recent versions of Windows 10 Home. 

Any comments on this theory? Is the program still working well with recent updates of Windows 10 Pro? I am thinking about updating to Windows 10 Pro, but I probably won't spend the money needed to update to Windows 10 Enterprise.

**Comment by 10se1ucgo** [comment]
The "organization" *is* DWT. It modifies group policies to block some stuff. Just set "Allow Telemetry" in gpedit.msc to Enabled and you'll be good to go.

**Comment by arnstein99** [comment]
Hello,

Windows 10 **Home** does not have gpedit.msc in it. I found the /policy/ registry key that corresponds to this item in gpedit.msc. Changing it does cause a change to appear in an item in the Settings app. This item was something similar to "Allow data collection" "None/Basic/Enhanced/Full". However, the red text still appears, and some important settings are still greyed out. Finally, Windows Update still fails to find Build 1511 on one of my peecees.

That's why I am thinking about upgrading to Windows 10 Pro.

Best regards,
D.A.

**Comment by 10se1ucgo** [comment]
Ah right, well then the revert option should be the way to go then.

**Comment by 10se1ucgo** [comment]
Use the `revert` mode.
