### ISSUE TITLE
Skype conversation group

### ISSUE THREAD

**Issue by Pelt10** [10se1ucgo/DisableWinTracking#127]
Hello,

I'm french, and i'm not very good in english, it's why I escuse me for my bad english.

DisableWinTraking block the server of the Skype conversation group. I don't know what server is.

Pelt10

**Comment by johnneijzen** [comment]
just revert this one "Block even more tracking domains"

since it can block Skype it even written in tool tip but i wont blame you.

**Comment by CAJIO** [comment]
I suffered for a long time. Indicate so on the main page.

**Comment by 10se1ucgo** [comment]
Revert `Block even more tracking domains`.
