### ISSUE TITLE
adding IPs to hosts file is useless, did you know?

### ISSUE THREAD

**Issue by Owyn** [10se1ucgo/DisableWinTracking#13]
you can't remap an IP to IP in the hosts file, but I still saw your code try it. So it won't block those IPs, false hope.

**Comment by CrisBRM** [comment]
True. I take it it's not possible to use a script to add those IPs to the windows firewall.

**Comment by qgustavor** [comment]
The HOSTS file *isn't a firewall*, AFAIK it's a overwrite file over the normal DNS queries. In the other hand the Windows Firewall can block IPs, hostnames and ports. It can be scripted using `netsh advfirewall firewall add rule`.

**Comment by CrisBRM** [comment]
@qgustavor 
>It can be scripted using netsh advfirewall firewall add rule.


That's what I wanted to know. So it can be fixed after all.
In fact, it'd be a considerably better option. Even for certain named domains.

**Comment by 10se1ucgo** [comment]
If you'd people actually read closed issues, you would've seen that people have said these 2 times. My response has always been:

Yes, I know, I got the list from the MDL forums and didn't really care about the IPs. I'll remove them and add more domains in the next update.

**Comment by Talyrius** [comment]
Perhaps you should leave the issue open until it's resolved—it'll likely be brought up again otherwise.

**Comment by 10se1ucgo** [comment]
Someone submitted a pull request and I merged it, it's resolved.

**Comment by 10se1ucgo** [comment]
IPs are now blocked with the firewall.
