### ISSUE TITLE
Add command line switches

### ISSUE THREAD

**Issue by thenoncoder** [10se1ucgo/DisableWinTracking#130]
Example : `DisableWinTracking.exe /services delete` deletes tracking services, `/services disable` disables them, etc. Would be a great option so that I can use it in my batch scripts.

The main usage of this for me would be to run the app with the switches every while using task scheduler, as Microsoft tends to edit/rename services with each update. Would be even better for you to add it in the app itself, perhaps using PowerShell's `FileSystemWatcher`, as it only runs when files are changed, and not just every set period of time like task scheduler does.

**Comment by 10se1ucgo** [comment]
#154
