### ISSUE TITLE
On/Off switch instead of checkbox + switch font to Segoe UI

### ISSUE THREAD

**Issue by ghost** [10se1ucgo/DisableWinTracking#131]
Looks cooler imo, I mean something like the Win10 settings app on/off switch, and then Segoe UI just for more swag. It's not really needed, but would still be cool. Perhaps also  remove the useless buttons in the About/Help menu and have it all in  one page.

**Comment by W4RH4WK** [comment]
Sounds like we need a `--swag` commandline option.

**Comment by thenoncoder** [comment]
Yeah, we need DisableWinTracking to look as cool as the new Settings app.

**Comment by 10se1ucgo** [comment]
* Font is default system font. It should be Segoe UI. wxMSW is native.
* I don't think wxMSW supports that style of Metro UI.
* Rewrite being worked on now, #153

**Comment by 10se1ucgo** [comment]
Invalid for the reasons above. Also, #119 fixed (hopefully) with rewrite.

**Comment by 10se1ucgo** [comment]
As I'm rewritting DWT in C#, I'll be able to create a universal app with these features.

#186

**Comment by thenoncoder** [comment]
Well, the UI has certainly improved from the screenshots that you've posted, but, I still think that it could be improved.

Although when I originally opened this issue I did specify a more of a Metro or Modern as it's called now design language, I didn't really mean specifically that, just a better design overall

The current stable version, which appears to be 2.5, is still usable, it's fine, but I think maybe Material design is a better direction for this app than Metro/Modern design is.

Perhaps you could use something like Materialze or Material Lite to design the app using css and then convert it to whatever language that you're actually using.

**Comment by 10se1ucgo** [comment]
Yeah, the GUI toolkit I'm using is pretty messy. I'm likely going to find another one. Material sounds good.

**Comment by thenoncoder** [comment]
Well, on an unrelated note, think that you should also add a search bar to filter the options within the app.

And collapsible items. For example, clicking on an option, say, "remove services", expands it to show an explanation of what it does.

I think that this idea is good because if the text is long, then it doesn't show up until you manually click on it.
