### ISSUE TITLE
[Feature request]Add option to disable/enable windows automatic updates

### ISSUE THREAD

**Issue by Bnaya** [10se1ucgo/DisableWinTracking#135]

**Comment by W4RH4WK** [comment]
As far as I know there is no easy way to disable automatic updates, I have the Windows Update Service disabled by default and run a script every now-and-then by hand which:

1. enables the service
2. checks and installs updates in an interactive fashion
3. disables the service
4. reboots

**Comment by thenoncoder** [comment]
Is it possible to manually set them to "Download now, install when prompted" or "Ask before downloading" kind of options that Windows 7/Windows 8 had?

**Comment by boldsoon** [comment]
Disable Windows Spying allows this, to disable/enable windows updates.

**Comment by Ruined1** [comment]
The built-in apps was already a shy away from what the projects goal was, if we add this it might as well be renamed "Windows 10 Optimizer". I'm going to close this issue for now, it's not a bad idea, but "updates" are for security enhancements and the like and this is, therefor, not within the scope of the project.
