### ISSUE TITLE
Files writes not verified

### ISSUE THREAD

**Issue by wal-f** [10se1ucgo/DisableWinTracking#139]
**INFORMATION:**

* Windows Edition: Home
* Architecture: 64bit
* Options used: block tracking domains (+more domains)

Hosts file modification was blocked by my antivirus, but DWT did not seem to attempt a read on the 'updated' hosts file to ensure the data was actually written. I ran DWT again with the hosts file protection disabled, but it should have reported an error the first time.

**Comment by fitzha** [comment]
If you have third party software that will prevent writing then the onus is really on you, not DWT.

**Comment by wal-f** [comment]
Half right. Average users aren't going.to understand that your software didn't work. When writing something that modifies sensitive system files which are routinely protected by other software, it's a bit naive to think that you're writes will work and that if they don't it's not DWT's problem.

Not BitDefender.

**Comment by 10se1ucgo** [comment]
#147
