### ISSUE TITLE
Adding more hosts and IPs to block

### ISSUE THREAD

**Issue by Aldous-Huxley** [10se1ucgo/DisableWinTracking#140]
These IP & hosts lists seem to be updated regularly:
https://encrypt-the-planet.com/windows-10-anti-spy-host-file/

**Comment by fitzha** [comment]
Most are already covered, however when I get some time I'll check if there's the additional one or few that are safe to add.

I don't see any need to block Hotmail, Windows Live or Skype domains.

**Comment by Ruined1** [comment]
This was already done and never closed. Closing.
