### ISSUE TITLE
Used revert feature so i could use the app store again, however it cant connect to the internet

### ISSUE THREAD

**Issue by oliclarke** [10se1ucgo/DisableWinTracking#141]
Tried to revert so i could use the app store again but doesnt seem to work. Manually removed all extra lines from hosts file and still nothing?

**INFORMATION:**

* Windows Edition (Home/Pro/Enterprise): 
* Architecture (32bit/64bit): 
* Options used:

**LOG:**

```python
REPLACE THIS WITH DISABLEWINTRACKING.LOG
```

**Comment by wfingerdo** [comment]
I had this same problem, I had to reset the network adapter and other stuff, this brought back network connectivity, but there was still a yellow "splat" on the network adapter as it thought there was no connectivity.  I tracked it down to the IP / DNS that Microsoft uses to check to see if there is internet connectivity was blocked by DisableWinTracking.  Its "network awareness" / NCSI.  Last example is for Windows 7, I couldn't find the original link to the post about W10 that showed same info.  Hope this helps, it was frustrating for me, was understandable as DisableWinTracking was just "doing what I told it to do".  Ha!

More info on how it was fixed:

http://www.thewindowsclub.com/limited-network-connectivity-in-windows-10

http://blog.superuser.com/2011/05/16/windows-7-network-awareness/

**Comment by oliclarke** [comment]
Interesting,  I never lost connectivity,   for the whole pc.  I managed to solve my issue by manually removing the blocks in Windows Firewall. 

These seemed to have been leftover by the revert feature. 

Hopefully someone will find this info useful.

**Comment by wfingerdo** [comment]
I have used DisableWinTracking on about 100 tablets and 50 laptops 20-30 desktops, most were "upgraded" from Win7,  I only had this issue happen once and it was with a Broadcom chipset.  Who knows why it has happened this time and not before, maybe something to do with the order which I did things, weather or not the computer was connected to the internet before I ran the DisableWinTracking....etc....

**Comment by 10se1ucgo** [comment]
#113
