### ISSUE TITLE
Can't update windows store applications and install/update skype. 

### ISSUE THREAD

**Issue by pentrecode** [10se1ucgo/DisableWinTracking#142]
Windows Store:
Applications can be updated only with disabled firewall.

Skype:
Do not working text messages.
The application cannot pass installation or update. Error connecting to Skype servers.

**Comment by pentrecode** [comment]
Disabled: Services, telemetry, bloacked tracking domains and even more tckaging domains and tracking IP addresses/

**Comment by Tanagashi** [comment]
Same, have bunch of issues with Skype - can't download through the installer, can't update, can't send images or edit messages.

Have pretty much everything uninstalled except for default image viewer. Telemetry and tracking domains are blocked.

**Comment by zmsp** [comment]
same issue. Might be hosts file?

**Comment by SPMelly** [comment]
I can't access bing.com now. is this normal?

**Comment by v998** [comment]
Windows Search connects to Bing when we type in the box, so it is blocked by the rules we set in Windows Firewall.

`204.79.197.200` is the IP address of Bing

see https://github.com/10se1ucgo/DisableWinTracking/blob/master/run.py#L302

**Comment by Johandrex** [comment]
How do I fix this.. unable to revert

**Comment by 10se1ucgo** [comment]
Revert the `Block even more tracking domains` option.
