### ISSUE TITLE
doesnt work anymore with win 10

### ISSUE THREAD

**Issue by ricorius** [10se1ucgo/DisableWinTracking#146]
you should update program

**Comment by v998** [comment]
and you should describe the issue more specifically

any screenshots? errors? warnings?

**Comment by Svetomech** [comment]
Eeyup, 'casue works for me just fine.

**Comment by ricorius** [comment]
https://github.com/10se1ucgo/DisableWinTracking

No longer being developed, see issue #147.

This may no longer thoroughly disable all tracking, as some services have been added or have had their names changed. See Issue #124.

**Comment by 10se1ucgo** [comment]
Fixed
