### ISSUE TITLE
I don't work on this anymore.

### ISSUE THREAD

**Issue by 10se1ucgo** [10se1ucgo/DisableWinTracking#147]
As you can see, issues are piling up. I just want to tell you guys that I don't work on this anymore.

It's been a fun run, but if anyone with eyes and a brain looks at and reads the code they'll immediately see how bad it is. Not only that, this project has really attracted a whole lot of tin foil hattists (if that's not a word, it is now) while my only goal for this project was to make a neat looking GUI. Unfortunately, I sort of failed at that too as you can see from the issues regarding scaling.

I have now put more focus on other projects, such as the one that I released a couple days ago, which is a wrapper for the Corsair Utility Engine SDK. [You can find that here, if you're interested.](https://github.com/10se1ucgo/cue_sdk)

I'm also working on some unreleased project, which you can find pictures/previews of here:
http://i.imgur.com/aGRveB3.png
http://i.imgur.com/Nrpa8JB.gifv
http://i.imgur.com/xCVh1rp.gifv
http://i.imgur.com/mAIRGTy.gifv
I shall not explain what the project is until it is complete, however.

If, however, some of you still want to contribute, that's totally fine.
Feel free to either a. submit pull requests for me to merge, or b. fork it and do whatever pleases you.

That's it.
Have fun!

**Comment by srguglielmo** [comment]
Could you update `README.md`? Many people don't read the issues and just view the project page. They would miss that it's no longer being developed.

**Comment by 10se1ucgo** [comment]
Done

**Comment by AdKiller** [comment]
I wish an open source solution to Windows 10 spyware issues would arise... I would step up if I had the programming knowledge. oh well, thanks for the work so far.

**Comment by Johandrex** [comment]
Thanks for your hard work, could anyone take over this project thought?

**Comment by 10se1ucgo** [comment]
If anyone would like to submit pull requests, I will gladly review them and merge. I'll also compile builds for major pull requests. If someone would like to fork it and do things their way, I will provide a link in the README.

**Comment by hulr** [comment]
I created a similar tool completely in PowerShell, check it out if you like.

**Comment by war59312** [comment]
@hulr Link?

**Comment by TheNain38** [comment]
@war59312 https://github.com/hulr/BetterPrivacy

**Comment by war59312** [comment]
That's odd. 6 minutes ago it was not there. Damn unicorns again. ;)

But Ok, thanks.

**Comment by 10se1ucgo** [comment]
I'm most likely going to update this to fix a number of issues (e.g. scaling, freezes)
I've worked on some projects since the beginning of this which has taught me a lot. I've finally learned to use wxSizers and will be splitting up the files into a more organized layout.

**Comment by 10se1ucgo** [comment]
Okay, the first step here is to rewrite all of the GUI code (by hand, obviously)

I will be working on this in the coming days (whenever I have free time)

**Comment by 10se1ucgo** [comment]
#153
