### ISSUE TITLE
Replace with a short description of your problem

### ISSUE THREAD

**Issue by jeski** [10se1ucgo/DisableWinTracking#148]
**INFORMATION:**

* Windows Edition (Home): 
* Architecture (64bit): 
* Options used:

**LOG:**
Not sure if this is a problem or not, so I posted it. Everything else looks good. 
WifiSense/Defender: Unable to modify Windows Defender Spynet key.
WifiSense/Defender: Unable to modify Windows Defender Sample Submission key.

```python

```

**Comment by jeski** [comment]
Not sure if this is a problem or not, so I posted it. Everything else looks good. 
WifiSense/Defender: Unable to modify Windows Defender Spynet key.
WifiSense/Defender: Unable to modify Windows Defender Sample Submission key.

**Comment by 10se1ucgo** [comment]
Known issue. However, see #147.

If anyone would like to look into why this is happening, feel free.
