### ISSUE TITLE
Not all programs were reinstalled..! pls help

### ISSUE THREAD

**Issue by jmaheswararaj** [10se1ucgo/DisableWinTracking#151]
Hi,
I'd run the exe & wanted to revert to old setting (since i was missing some app like calculator etc. So don't know how to download the necessary other apps as well).

* Windows Edition (Home/Pro/Enterprise): Home
* Architecture (32bit/64bit): 64 bit
* Options used: All built in apps except camera & "Uninstall One drive"

**LOG:**

```python

22:52:19 INFO: DisableWinTracking Version: v2.5.1

22:52:19 INFO: Mode: Revert

22:52:19 INFO: Telemetry box ticked

22:52:19 INFO: Host box ticked

22:52:19 ERROR: Domain block: Could not remove domains.
Traceback (most recent call last):
  File "<string>", line 613, in modifyhostfile
WindowsError: [Error 5] Access is denied: 'C:\\WINDOWS\\System32\\drivers\\etc\\hosts'

22:52:19 INFO: Extra host box ticked

22:52:19 ERROR: Extra domain block: Could not remove domains.
Traceback (most recent call last):
  File "<string>", line 613, in modifyhostfile
WindowsError: [Error 5] Access is denied: 'C:\\WINDOWS\\System32\\drivers\\etc\\hosts'

22:52:19 INFO: IP block box ticked

22:52:22 INFO: Defender/Wifisense box ticked

22:52:22 ERROR: Registry: Unable to modify Windows Defender Spynet key.
Traceback (most recent call last):
  File "<string>", line 575, in modifyregistry
WindowsError: [Error 5] Access is denied

22:52:22 ERROR: Registry: Unable to modify Windows Defender Sample Submission key.
Traceback (most recent call last):
  File "<string>", line 575, in modifyregistry
WindowsError: [Error 5] Access is denied

```

**Comment by jsysenkham** [comment]
IIRC this person has stopped working on this project. but looking at the line where it says the access is denied to the host file.  This tells me that you do not have the application running as an Administrator.

*To get your programs back you can run PowerShell as an Administrator and use this command 
'Get-AppxPackage -AllUsers| Foreach {Add-AppxPackage -DisableDevelopmentMode -Register “$($_.InstallLocation)\AppXManifest.xml”}'

*reference : http://www.howtogeek.com/224798/how-to-uninstall-windows-10s-built-in-apps-and-how-to-reinstall-them/

**Comment by 10se1ucgo** [comment]
Run program as administrator.

**Comment by war59312** [comment]
Should make it always run as admin using manifest file so this does not happen:

https://stackoverflow.com/questions/2818179/how-to-force-my-net-app-to-run-as-administrator-on-windows-7

Should be a good start.

**Comment by 10se1ucgo** [comment]
There used to be. Latest version of pyinstaller broke manifests.

**Comment by war59312** [comment]
Issue # ? See old reports but all marked fixed.

Just curious. Thanks.

**Comment by 10se1ucgo** [comment]
https://github.com/pyinstaller/pyinstaller/issues/1729

**Comment by war59312** [comment]
Thanks
