### ISSUE TITLE
Rewrite

### ISSUE THREAD

**Issue by 10se1ucgo** [10se1ucgo/DisableWinTracking#153]
It's time for a rewrite.

I'm currently working on rewriting the GUI to scale properly.
Took me about ~15 minutes to get this so far: http://i.imgur.com/uasZPjO.png
Scales properly, too.

More in the coming days, hopefully.

- [ ] Re-write GUI
    - [x] Main frame
        - [x] Add all widgets
        - [ ] Make them do something
    - [x] About dialog
    - [ ] Settings dialog
    - [x] Console dialog

- [ ] Re-write functions

**Comment by 10se1ucgo** [comment]
Another 10 and we got http://i.imgur.com/wDy5MqL.png

**Comment by 10se1ucgo** [comment]
about dialog + menu bars
http://i.imgur.com/8N58c9p.png

**Comment by 10se1ucgo** [comment]
http://i.imgur.com/DTALa5d.png

**Comment by 10se1ucgo** [comment]
Base UI complete!
http://i.imgur.com/LwAXsKq.png http://i.imgur.com/ZXKPNXw.png

**Comment by Svetomech** [comment]
Cool.

**Comment by harryrlees** [comment]
Awesome. I use this for every clean install, keep it up dude

**Comment by loskutov** [comment]
Will it be written in Python anyway? It’s a little bit strange to have pretty much dependencies for such a small utility...

**Comment by 10se1ucgo** [comment]
Yes, it's still written in Python. It also doesn't have many dependencies, so I'm not really sure what you mean. wxPython for the GUI and PyWin32 for accessing the Win32 API

**Comment by highstrike** [comment]
I just want to say `Thank you` for continuing this project. I appreciate all the hard work you put into this. Thank you, once again :bow:

**Comment by 10se1ucgo** [comment]
Done.

**Comment by WillPresley** [comment]
@10se1ucgo Any reason I'm not seeing the new rewritten version in releases? Or is it just not up yet? Either way, thanks for the tool and congrats on finishing the rewrite!

**Comment by 10se1ucgo** [comment]
Oops, I forgot to build the exe. Will do in a bit.

**Comment by 10se1ucgo** [comment]
@WillPresley https://github.com/10se1ucgo/DisableWinTracking/releases/tag/v3.0
