### ISSUE TITLE
Add commandline parameters.

### ISSUE THREAD

**Issue by ghost** [10se1ucgo/DisableWinTracking#154]
Eg: `-slient` runs the app without a UI displayed.

`-noservices` deletes services.

`-domains` blocks tracking domains.

, Etc.

**Comment by 10se1ucgo** [comment]
Sure. It'll be implemented for the rewrite.

**Comment by thenoncoder** [comment]
Thanks!

**Comment by 10se1ucgo** [comment]
Opening until I implement this

**Comment by thenoncoder** [comment]
Thanks!

Ever though about Powershell/C++'s `FileSystemWatcher`?

It's like Task Scheduler except it only runs when the files are actually changed.

That way, it'll keep monitoring the stuff it disabled, and keep disabling them whenever they change.

**Comment by thenoncoder** [comment]
Thanks!

Ever though about Powershell/C++'s `FileSystemWatcher` or equivalents?

It's like Task Scheduler except that it, as far as I understand, only runs when the files/reg keys/etc you choose are changed.

That way, it can keep monitoring reg keys to make sure telemetry reg keys are not enabled in a future system update, and you could add that as an optional feature, not selected by default, but then you may need to check it has as little system load as possible, if you're going to implement it.

**Comment by Ruined1** [comment]
Done. Only added -silent which will presumably Clear DiagTrack, Disable DiagTrack, Disable WAP Push, and take care of service, telemetry, defender, wifisense, and onedrive. There will be no dialog.
