### ISSUE TITLE
Not working correctly when launching as Admin?

### ISSUE THREAD

**Issue by warmbaguettes** [10se1ucgo/DisableWinTracking#157]
**INFORMATION:**

* Windows Edition (Home/Pro/Enterprise): Enterprise
* Architecture (32bit/64bit): 64
* Options used: Delete all services

**LOG:**

Don't have

Since installing Windows, I ran the application with administrator privileges, uninstalled apps and deleted services, log threw no errors so I assumed it worked. But there still was the OneDrive icon in explorer.

Yesterday I got a bit worried, so I've installed Wireshark to see if it was still phoning MS, and indeed it was. Then, I ran DWT 2.5.1 again with NO admin privileges and it actually worked correctly, everything removed as it should, including the OneDrive icon. Tested with Wireshark and the system was not phoning MS anymore.

I'm not sure if it's a problem with DWT or a problem with Windows 10 with UAC disabled.

I just thought I write this for people having problems using DWT.

**Comment by HLFH** [comment]
Same issue...

**Comment by Stephan35** [comment]
Hi,
Here is a message , Fatal Error! Failed to execute script dwt.

thanks

**Comment by 10se1ucgo** [comment]
Read the release notes. It literally says "EVERYTHING IS BROKEN"

**Comment by 10se1ucgo** [comment]
Fixed in ada20b4. Uploading release as soon as I get my virtualenv running.

**Comment by 10se1ucgo** [comment]
https://github.com/10se1ucgo/DisableWinTracking/releases/tag/v3.0.1

**Comment by aschneid1** [comment]
Still broken for me
