### ISSUE TITLE
Outdated package names for uninstall apps

### ISSUE THREAD

**Issue by ElPumpo** [10se1ucgo/DisableWinTracking#158]
In the latest Insider builds, some apps have been renamed, for example:

- Microsoft.ZuneVideo
- Microsoft.Office.Sway (new app)
- Microsoft.BingSports
- Microsoft.Office.OneNote (new app)
Some more, two Skype apps, a "Get Office" app, etc.
http://pastebin.com/2QvJ7yT3

**Comment by 10se1ucgo** [comment]
Thanks. I'll add them to the next update.

**Comment by 10se1ucgo** [comment]
Most of these already work, but the rest were fixed in ada20b4. Uploading release as soon as I get my virtualenv running.

**Comment by 10se1ucgo** [comment]
https://github.com/10se1ucgo/DisableWinTracking/releases/tag/v3.0.1

**Comment by ElPumpo** [comment]
So you know, the package names changed yet again in the latest Insider builds.

**Comment by ElPumpo** [comment]
Here's a updated list on Insider 14332; http://pastebin.com/kdUfUp3t

**Comment by 10se1ucgo** [comment]
oooof course. thanks.

**Comment by ElPumpo** [comment]
NOTE: that's a fresh dump directly after updating to Insider 14332.
