### ISSUE TITLE
Fatal Error!

### ISSUE THREAD

**Issue by kcomp1863** [10se1ucgo/DisableWinTracking#161]
**INFORMATION:**

* Windows Edition (Home/Pro/Enterprise): Windows 10 TH2
* Architecture (32bit/64bit):64bit
* Options used:attempted to run "as administrator"

**LOG:**

```python
REPLACE THIS WITH DWT.LOG
```
Receive a fatal error everytime stating: "Failed to execute script dwt" Won't open to generate a dwt log.

**Comment by bratikha** [comment]
Windows 10.0.10240 SL
 x64-based PC
i have this error too :(
![fe](https://cloud.githubusercontent.com/assets/6857762/14774651/92410e4c-0b0c-11e6-8892-e1bba75f6e66.png)

**Comment by 10se1ucgo** [comment]
Porting to Python 2, pyinstaller has issues with Python 3 for some reason.

**Comment by kcomp1863** [comment]
Huh? I'm not understanding your response, with regard to the reported problem. What's this Python 2 and 3?

**Comment by 10se1ucgo** [comment]
This is happening because PyInstaller has some issues with loading the GUI DLLs. This only happens with Python version 3+. I'll backport DWT to Python 2 and upload a fix in a couple of minutes.

**Comment by 10se1ucgo** [comment]
Fixed in ada20b4. Uploading release as soon as I get my virtualenv running.

**Comment by kcomp1863** [comment]
Great! I'll look for your new release! Thanks!

**Comment by 10se1ucgo** [comment]
It'll be here https://github.com/10se1ucgo/DisableWinTracking/releases/tag/v3.0.1 in a little while.

**Comment by 10se1ucgo** [comment]
Done! Feel free to download. Report anything broken.

**Comment by kcomp1863** [comment]
Great! I'll look for your new release! Thanks!

**Comment by kcomp1863** [comment]
Looks like it's good to go now!, Thanks!

**Comment by drws** [comment]
Running as admin while using 64-bit Windows 10.0.10586 on x64 hardware still produces the same error in v3.0.1 (release downloaded a few minutes ago from this site)...
