### ISSUE TITLE
Some errors in log

### ISSUE THREAD

**Issue by Laminaat** [10se1ucgo/DisableWinTracking#162]
**INFORMATION:**

* Windows Edition (Home/Pro/Enterprise): Pro
* Architecture (32bit/64bit): 64bit
* Options used:

Note: Months ago I've used a previous version of this software (not sure what I selected then) but now:

Services
Clear DiagTrack log
Telemetry
Block tracking domains
Block tracking IP addresses
Windows Defender collection
WifiSense

**LOG:**

20:19:11 INFO: Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)] on win32
20:19:11 INFO: ('Windows', 'Guy', '10', '10.0.10586', 'AMD64', 'Intel64 Family 6 Model 60 Stepping 3, GenuineIntel')
20:19:11 INFO: DisableWinTracking version 3.0.1
20:27:49 CRITICAL: Traceback (most recent call last):
  File "dwt.py", line 258, in hosts_warn
AttributeError: 'CommandEvent' object has no attribute 'GetObject'

20:28:31 INFO: Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)] on win32
20:28:31 INFO: ('Windows', 'Guy', '10', '10.0.10586', 'AMD64', 'Intel64 Family 6 Model 60 Stepping 3, GenuineIntel')
20:28:31 INFO: DisableWinTracking version 3.0.1
20:29:55 INFO: IP Blocker: The IP 134.170.30.202 was successfully blocked.
20:29:55 INFO: IP Blocker: The IP 137.116.81.24 was successfully blocked.
20:29:55 INFO: IP Blocker: The IP 157.56.106.189 was successfully blocked.
20:29:55 INFO: IP Blocker: The IP 2.22.61.43 was successfully blocked.
20:29:55 INFO: IP Blocker: The IP 2.22.61.66 was successfully blocked.
20:29:55 INFO: IP Blocker: The IP 204.79.197.200 was successfully blocked.
20:29:55 INFO: IP Blocker: The IP 23.218.212.69 was successfully blocked.
20:29:55 INFO: IP Blocker: The IP 64.4.54.254 was successfully blocked.
20:29:55 INFO: IP Blocker: The IP 65.39.117.230 was successfully blocked.
20:29:56 INFO: IP Blocker: The IP 65.52.108.33 was successfully blocked.
20:29:56 INFO: IP Blocker: The IP 65.55.108.23 was successfully blocked.
20:29:56 ERROR: DiagTrack: Failed to clear DiagTrack log -- could not take ownership of file
Traceback (most recent call last):
  File "dwt_util.py", line 92, in clear_diagtrack
  File "dwt_util.py", line 263, in subprocess_handler
CalledProcessError: Command '['takeown', '/f', 'C:/ProgramData/Microsoft/Diagnosis/ETLLogs/AutoLogger/AutoLogger-Diagtrack-Listener.etl', '&&', 'icacls', 'C:/ProgramData/Microsoft/Diagnosis/ETLLogs/AutoLogger/AutoLogger-Diagtrack-Listener.etl', '/grant', 'administrators:F']' returned non-zero exit status 1
20:29:56 CRITICAL: DiagTrack: Error output:

20:29:56 INFO: Services: Succesfully removed service 'dmwappushsvc'
20:29:56 INFO: Services: Succesfully removed service 'DiagTrack'
20:29:56 INFO: Registry: Successfully modified dmwappushsvc key.
20:29:56 INFO: Registry: Successfully modified DiagTrack key.
20:29:56 INFO: Registry: Successfully modified AllowTelemetry key.
20:29:56 ERROR: Hosts: Failed to modify hosts file
Traceback (most recent call last):
  File "dwt_util.py", line 231, in host_file
IOError: [Errno 13] Permission denied: 'C:\\WINDOWS\\System32/drivers/etc/hosts'
20:29:56 ERROR: Registry: Unable to mody Windows Defender Sample Submission key.
Traceback (most recent call last):
  File "dwt_util.py", line 205, in set_registry
WindowsError: [Error 5] Toegang geweigerd
20:29:56 ERROR: Registry: Unable to mody Windows Defender Spynet key.
Traceback (most recent call last):
  File "dwt_util.py", line 205, in set_registry
WindowsError: [Error 5] Toegang geweigerd
20:29:56 INFO: Registry: Successfully modified Windows Defender Delivery Optimization Download key.
20:29:56 INFO: Registry: Successfully modified WifiSense Open-ness key.
20:29:56 INFO: Registry: Successfully modified WifiSense Credential Share key.
20:29:56 INFO: Done. It's recommended that you reboot as soon as possible for the full effect.
20:29:56 INFO: If you feel something didn't work properly, please press the 'Report an issuebutton and follow the directions

**Comment by Laminaat** [comment]
The errors with regards to the hostfiles were caused by Avira antivirus, it blocks access to these files by default.

**Comment by 10se1ucgo** [comment]
This is normal behavior if you've already used the program. You can ignore these.
