### ISSUE TITLE
WinTracking v.3 - some errors

### ISSUE THREAD

**Issue by TigerTraderHK** [10se1ucgo/DisableWinTracking#163]
14:35:02 INFO: Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)] on win32
14:35:02 INFO: ('Windows', 'LaptopG_Vaio', '10', '10.0.10586', 'AMD64', 'Intel64 Family 6 Model 37 Stepping 5, GenuineIntel')
14:35:02 INFO: DisableWinTracking version 3.0.1
14:35:22 CRITICAL: Traceback (most recent call last):
  File "dwt.py", line 258, in hosts_warn
AttributeError: 'CommandEvent' **object has no attribute 'GetObject'**

14:35:42 INFO: IP Blocker: The IP 134.170.30.202 was successfully blocked.
14:35:44 INFO: IP Blocker: The IP 137.116.81.24 was successfully blocked.
14:35:45 INFO: IP Blocker: The IP 157.56.106.189 was successfully blocked.
14:35:47 INFO: IP Blocker: The IP 2.22.61.43 was successfully blocked.
14:35:48 INFO: IP Blocker: The IP 2.22.61.66 was successfully blocked.
14:35:50 INFO: IP Blocker: The IP 204.79.197.200 was successfully blocked.
14:35:51 INFO: IP Blocker: The IP 23.218.212.69 was successfully blocked.
14:35:53 INFO: IP Blocker: The IP 64.4.54.254 was successfully blocked.
14:35:54 INFO: IP Blocker: The IP 65.39.117.230 was successfully blocked.
14:35:56 INFO: IP Blocker: The IP 65.52.108.33 was successfully blocked.
14:35:57 INFO: IP Blocker: The IP 65.55.108.23 was successfully blocked.
14:35:58 ERROR: DiagTrack: Failed to clear DiagTrack log -- **could not take ownership of file**
Traceback (most recent call last):
  File "dwt_util.py", line 92, in clear_diagtrack
  File "dwt_util.py", line 263, in subprocess_handler
CalledProcessError: Command '['takeown', '/f', 'C:/ProgramData/Microsoft/Diagnosis/ETLLogs/AutoLogger/AutoLogger-Diagtrack-Listener.etl', '&&', 'icacls', 'C:/ProgramData/Microsoft/Diagnosis/ETLLogs/AutoLogger/AutoLogger-Diagtrack-Listener.etl', '/grant', 'administrators:F']' returned non-zero exit status 1
14:35:58 CRITICAL: DiagTrack: **Error output**:

14:35:58 INFO: Registry: Successfully modified dmwappushsvc key.
14:35:58 INFO: Registry: Successfully modified DiagTrack key.
14:35:58 INFO: Registry: Successfully modified AllowTelemetry key.
14:35:58 ERROR: Registry: Unable to mody Windows Defender Sample Submission key.
Traceback (most recent call last):
  File "dwt_util.py", line 205, in set_registry
WindowsError: [Error 5] **Access is denied**
14:35:58 ERROR: Registry: **Unable to mody Windows Defender Spynet key**.
Traceback (most recent call last):
  File "dwt_util.py", line 205, in set_registry
WindowsError: [Error 5] **Access is denied**
14:35:58 INFO: Registry: Successfully modified Windows Defender Delivery Optimization Download key.
14:35:58 INFO: Registry: Successfully modified WifiSense Open-ness key.
14:35:58 INFO: Registry: Successfully modified WifiSense Credential Share key.
14:35:58 INFO: Registry: Successfully modified ListPin key.
14:35:58 INFO: Registry: Successfully modified FileSync key.
14:35:58 INFO: OneDrive: unable to uninstall
14:35:58 INFO: Done. It's recommended that you reboot as soon as possible for the full effect.
14:35:58 INFO: If you feel something didn't work properly, please press the 'Report an issuebutton and follow the directions

**Comment by tobeorla** [comment]
I'm also getting that error (executed as Admin):
`11:14:44 ERROR: DiagTrack: Failed to clear DiagTrack log -- could not take ownership of file
Traceback (most recent call last):
  File "dwt_util.py", line 92, in clear_diagtrack
  File "dwt_util.py", line 263, in subprocess_handler
CalledProcessError: Command '['takeown', '/f', 'C:/ProgramData/Microsoft/Diagnosis/ETLLogs/AutoLogger/AutoLogger-Diagtrack-Listener.etl', '&&', 'icacls', 'C:/ProgramData/Microsoft/Diagnosis/ETLLogs/AutoLogger/AutoLogger-Diagtrack-Listener.etl', '/grant', 'administrators:F']' returned non-zero exit status 1
11:14:44 CRITICAL: DiagTrack: Error output:`

Ends as shown, no more info after error output message.
