### ISSUE TITLE
An error has occured - Latest version won't work

### ISSUE THREAD

**Issue by mrHJS** [10se1ucgo/DisableWinTracking#164]
**INFORMATION:**
DWT won't work. After having started it with elevated rights I get an error message telling me something about the python script.

* Windows 10 Enterprise
* 64bit
* Latest version 3.0.1 of DWT

**LOG:**

```python
15:27:38 INFO: Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)] on win32
15:27:38 INFO: ('Windows', 'DESKTOP', '10', '10.0.10240', 'AMD64', 'Intel64 Family 6 Model 69 Stepping 1, GenuineIntel')
15:27:38 INFO: DisableWinTracking version 3.0.1
15:27:39 CRITICAL: Traceback (most recent call last):
  File "dwt.py", line 440, in <module>
  File "dwt_about.py", line 170, in update_check
  File "urllib2.py", line 154, in urlopen
  File "urllib2.py", line 431, in open
  File "urllib2.py", line 449, in _open
  File "urllib2.py", line 409, in _call_chain
  File "urllib2.py", line 1240, in https_open
  File "urllib2.py", line 1197, in do_open
URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>

**Comment by 10se1ucgo** [comment]
Ignore it. Seems like urllib2 can't find the SSL certificate for the update checker (it connects to GitHub w/ HTTPS). Not a big deal, it just means you'll have to manually check for updates.

**Comment by mrHJS** [comment]
When I click ignore, I get another error message: Failed to execute script dwt

**Comment by ImDevinC** [comment]
This is because you're computer is missing the Github.com cert where the app checks for updates. Simply navigate your browser to github.com and then re-run the application, and it should work
