### ISSUE TITLE
Failed to execute script dwt

### ISSUE THREAD

**Issue by mrHJS** [10se1ucgo/DisableWinTracking#165]
As my other thread was closed too early (https://github.com/10se1ucgo/DisableWinTracking/issues/164) I open this one.
After I click ignore I get a new error message "Failed to execute script dwt" - the program closes by itself. There are no other entries in the dwt.log than the ones mentioned in the other thread.

**INFORMATION:**
- Windows 10 Enterprise
- 64bit
- Options used:

**LOG:**

``` python
REPLACE THIS WITH DWT.LOG
```

**Comment by nextgenthemes** [comment]
I have the exact same problem.

Version 3.0.1 on fresh win 10 x64 pro install.

1. First I got windows defender detect it as trojan, I allowed it.
2. Then the ssl error that generated the dwt logfile.
3. Then the "can not execute script dwt" error.

**Comment by nextgenthemes** [comment]
Just wanted to add that after a reboot it went well, may have to do with the c++ redistributes I installed or other things I did.

**Comment by Neopluser** [comment]
Version 3.0.1
Just update win 8.1 to win 10 home.
Run with admin permision, get message "Failed to execute script dwt".

**Comment by Sogl** [comment]
Same here, same error.
Fresh windows 10 installation, run as administrator.
v. 3.0.1

**Comment by ImDevinC** [comment]
#164 is open again, and I just posted a solution that works for me. Navigate to github.com and then relaunch the app, should work fine.

**Comment by KulaGGin** [comment]
@ImDevinC 
Your solution didn't solve this error message for me.
What I do:
1. Launch DisableWinTracking.exe with or without Admin rights.
2. Get "Failed to execute script dwt".
3. Program is immediately closed after the message.
4. Navigate to Github.com.
5. Launch DisableWinTracking.exe with or without Admin rights.
6. Get "Failed to execute script dwt" error message.
7. Program is immediately closed after the message.

**Comment by 5kyw4Lk3r** [comment]
It' has a rather simple and fucked up solution really.  You simply need to be online when you run it,I don't even know why that requirement exists! Is shit like this from Microsoft not why the author wrote this awesome app, anyway I just run it from the source it's far less infuriating.  For the record though I don't mean to sound ungrateful or anything for the author compiling the various fixes in one app,I just simply hate how freaking exception handling was ignored,and the bug not noticed-was kinda right in the face-,that's all.

**Comment by nextgenthemes** [comment]
@5kyw4Lk3r I do not get what you are saying.

You ran it from source? What does this mean? You compiled the correct source and ran it? How is that different that downloading he latest exe? Or you looked and fixed the source without telling us how or making a PR? 

How did you find out that you need to be online? What does this tool actually need from the net? Why does it connect to the web?

**Comment by 5kyw4Lk3r** [comment]
Well if you  examine the error it's  a failed update check,I.e it checks for an update and if check fails,it exits,I merely removed update checking from the source and repacked it with cxfreeze for portability,though I run it from the source with python installed until I repacked it,I don't know where I was unexpressive here,python Is an interpreted language,so you can directly run the source with out compiling it...

As for how I figured you need to be online,I read the error,then tried it while offline and online and there you have it.

This really is a pretty cool app,it's knife that untethered win10 from Microsoft just like good owld win7,only reason I'm switched to win10,though one could do all the changes manually. So kudos to the author,for meeting us halfway between lazyville and the future that we had better get used to,esp for win10 exclusive directx12...

**Comment by nextgenthemes** [comment]
So you boast about how easy the error is to spot/fix but did not make a PR. I guessed right then ...

**Comment by 5kyw4Lk3r** [comment]
touché,'n I wasn't boastin,I just don't like doing pull requests so I thought put in my solution as a comment. I reckon it was a bit brash. good day sir.

**Comment by 5kyw4Lk3r** [comment]
The simple solution to this problem is to be online when you run the exe,the cause is a bug due to a failed update when network connection is unavailable. 

To the author:I recommend removing update checking,  that resolves the bug and should make unnecessary, a needless pull request on my part.

@ nextgenthemes
U made good points,I think this is a more helpfull post,that I should have posted,so touché. Good day.
