### ISSUE TITLE
Dependency on old Visual C++ Redist

### ISSUE THREAD

**Issue by bni** [10se1ucgo/DisableWinTracking#166]
**INFORMATION:**
I get the error msvcr100.dll is missing. I guess this is because I don't have "Visual C++ 2010 Service Pack 1 Redistributable Package" installed. I dont feel like installing this ancient library on my computer. Why does DisableWinTracking require such an old runtime? It could depend on Visual C++ 2015 redist instead.

* Windows Edition (Home/Pro/Enterprise): Pro
* Architecture (32bit/64bit): x64
* Options used:

**LOG:**

```python
REPLACE THIS WITH DWT.LOG
```

**Comment by 10se1ucgo** [comment]
There are very little programs that have even begun to use msvc140. Most of them use old ones like 2012 or sometimes 2010. It's a requirement for Python 2 w/ Pyinstaller. I would use 2015 (I'd have to use Python 3) but pyinstaller + wxPython on Python 3 doesn't work on some machines.

**Comment by 10se1ucgo** [comment]
Also, if you think that's bad, look at [Maya](http://i.imgur.com/MS14UI3.png).

**Comment by wodim** [comment]
This should be addressed in some way. This app does not run in a clean installation of Windows 10. This is not acceptable. You should at least have a link to the required redistributable from the page that lists the releases.

**Comment by 10se1ucgo** [comment]
Get off your high horse pal, I'm not asking people to run this program.

**Comment by wodim** [comment]
Yeah dude you don't ask anybody to use your software and you can do whatever you want and I have no rights to complain and blablabla. That's fine to me. Now fix the problem.

**Comment by 10se1ucgo** [comment]
lol, there is no way to fix the problem. Complain elsewhere. Again, get off your high horse.

**Comment by wodim** [comment]
Of course there is a way to solve it:

>You should at least have a link to the required redistributable from the page that lists the releases.

Or link against a VC++ runtime from this century (Windows 10 comes with a few ones, but not 2010's).

Take off your horse blinders.

**Comment by 10se1ucgo** [comment]
I explained this before.  

> It's a requirement for Python 2 w/ Pyinstaller. I would use 2015 (I'd have to use Python 3) but pyinstaller + wxPython on Python 3 doesn't work on some machines.

**Comment by wodim** [comment]
Then recompile Pyinstaller yourself, linking it against a more recent version of the VC++ runtime.

**Comment by 10se1ucgo** [comment]
Next your gonna tell me to compile Python 2.7 myself, and then wxPython (and then even PyWin32) because they run on 2008. Mmm, nah.

**Comment by 10se1ucgo** [comment]
Also, if you read the text under "License" in the README, you'd find this block of text:

```
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details. 
```

**Comment by wodim** [comment]
If you read my previous comments, you'll find this block of text:

>Yeah dude you don't ask anybody to use your software and you can do whatever you want and I have no rights to complain and blablabla. That's fine to me. Now fix the problem.

**Comment by 10se1ucgo** [comment]
If you red the comment before yours, to you'd notice that I don't have to do shit for you. Especially not when you're being a rude fuck.
