### ISSUE TITLE
Windows Defender reports Trojan: Win32/Pocyx.C!cl 

### ISSUE THREAD

**Issue by joshuatee** [10se1ucgo/DisableWinTracking#168]
Windows Defender reports [Trojan: Win32/Pocyx.C!cl ](https://www.microsoft.com/security/portal/threat/encyclopedia/entry.aspx?name=Trojan%3AWin32%2FPocyx.C!cl)

**Comment by 10se1ucgo** [comment]
Can't do much about that. Though, if you're sceptical you can reverse the binary with pyinstxtractor and decompile the pyc files.

**Comment by JorisBolsens** [comment]
same issue, even with windows defender real-time turned off, it still kept removing it while i was trying to run it.

Had to add an exclusion for the folder before it would let me run it.

**Comment by rfnx** [comment]
https://www.virustotal.com/fr/file/d4c00704e0888c2b630b9fc61ca93ca222ad30767c6f998f219e96075a12ebfe/analysis/1463780795/ why ?

**Comment by 10se1ucgo** [comment]
Because those 3 are unreliable chinese anti-viruses?
