### ISSUE TITLE
Trojan in your app

### ISSUE THREAD

**Issue by MajidCS** [10se1ucgo/DisableWinTracking#17]
I find Trojan !!

https://www.virustotal.com/en/file/0aca5aaa66a8029d533415b104348cda0c45775567a371585c6b5596a965c168/analysis/

**Comment by 10se1ucgo** [comment]
I find idiot !!

If you think there is a Trojan, reverse the binary with pyinstxtractor and read the code for yourself and think twice about being a moron.

**Comment by ATouhou** [comment]
lool it's called heuristics Majid.  It react to things that other trojan/etc. does. 
Like adding/editing certain registry strings,  copying/editing files in "suspect folders" etc.  
Hope you understand this, else feel free to ask

**Comment by MajidCS** [comment]
10se1ucgo: You talk with users , they don't have any experience .

when they get this message form this site : 
https://www.virustotal.com/en/file/0aca5aaa66a8029d533415b104348cda0c45775567a371585c6b5596a965c168/analysis/

They will not immediately use the application .

It must be your response to people decently.

**Comment by 10se1ucgo** [comment]
If you seriously believe the response of 2 no-name AVs with, I quote, "generic and broad-reaching signatures on a packing utility" then you shouldn't be using this tool.

@ATouhou has provided a good enough explanation, if you still believe it's a Trojan, don't use it.

**Comment by piqus** [comment]
Guys, could you please stop arguing and send a notice to AV Company for **false report**? Both AV programs aren't very well-known and I am sure their heuristics are not excellent also. It would be great if @10se1ucgo as code/repo owner will spend his valuable few minutes to write an e-mail about this "heuristics-misunderstanding" problem. Could you? :wink:
