### ISSUE TITLE
Permission denied for hosts

### ISSUE THREAD

**Issue by petsto** [10se1ucgo/DisableWinTracking#173]
**INFORMATION:**
- Windows Edition (Home/Pro/Enterprise):
- Architecture (32bit/64bit):
- Options used: Used with Run as Administrator

**LOG:**

15:30:30 ERROR: Hosts: Failed to modify hosts file
Traceback (most recent call last):
  File "dwt_util.py", line 231, in host_file
IOError: [Errno 13] Permission denied: 'C:\Windows\System32/drivers/etc/hosts'

**Comment by 10se1ucgo** [comment]
Have you ran the program before?

**Comment by neuhaus** [comment]
Did you run it as administrator?
