### ISSUE TITLE
Windblows Defender telling users the exe contains a trojan

### ISSUE THREAD

**Issue by TeoTwawki** [10se1ucgo/DisableWinTracking#174]
**INFORMATION:**

`win32/pocyx.C!cl`
in the version 3.0.1  release - I presume that is just MS trying to scare ppl away from using this.

The are also wiping out my changes after reboot, even after I nuked win defender and ran as admin. I believe that is from the update the OS just did..

Thought you'd want to know they are getting more aggressive about the spyware in the OS..

* Windows Edition (Home/Pro/Enterprise): pro
* Architecture (32bit/64bit): 64
* Options used: n/a

**LOG:** n/a

**Comment by ageisen2000** [comment]
Can we get some sort of explanation for this please?

**Comment by 10se1ucgo** [comment]
#168

**Comment by TeoTwawki** [comment]
Strange, I know I did a search before bothering to open this, yet there sits proof it had already been reported. Sorry bout that!

**Comment by 10se1ucgo** [comment]
lol, no worries :)
