### ISSUE TITLE
Unable to open application. Error 0xc000007b

### ISSUE THREAD

**Issue by MSaIim** [10se1ucgo/DisableWinTracking#175]
I just downloaded v3.0.1 and am unable to run it. I get this message:

![](http://i.imgur.com/3DxKAAg.png)

> The application was unable to start correctly (0xc000007b). Click OK to close the application.

I tried running as administrator and without. Same error both times. I am using Windows 10 Pro 64bit. There are no logs to post. I just get that window pop up.

**Comment by hmksq** [comment]
I have no issues on Windows 10 Pro 64 bit. Not sure where the problem would be.

**Comment by PWN1109** [comment]
https://www.microsoft.com/en-us/download/details.aspx?id=8328
It has to be 32-bit version

**Comment by 10se1ucgo** [comment]
Never encountered this before. I'll try to reproduce this on a VM some time.

**Comment by naldo541** [comment]
me too
windows 10 pro 64bits

**Comment by Krood** [comment]
Win10 x64 version needs to install **x86** "Microsoft Visual C++ 2010 SP1 Redistributable Package (x86)", not x64. It works!
