### ISSUE TITLE
Missing dll

### ISSUE THREAD

**Issue by bmarkey** [10se1ucgo/DisableWinTracking#177]
Windows 10 pro
Version 1511
OS-Build 10586.318
64 bit

Ran as administrator

Error:
The program can't start because msvcr100.dll is missing from your computer.

**Comment by Daniil1288** [comment]
probably this:
https://github.com/10se1ucgo/DisableWinTracking/issues/166

if so, then download:
https://www.microsoft.com/en-us/download/details.aspx?id=8328

**Comment by 10se1ucgo** [comment]
@Daniil1288 is correct.

**Comment by bmarkey** [comment]
That did it, thanks all.
