### ISSUE TITLE
This ip should not be blocked

### ISSUE THREAD

**Issue by IceLancerSR** [10se1ucgo/DisableWinTracking#178]
**INFORMATION:**

* Windows Edition (Enterprise):
* Architecture (64bit):
* Options used:
Privacy
**LOG:**

```python
REPLACE THIS WITH DWT.LOG
```
[Used for Downloading]
191.232.139.2
Blocking this IP prevents windows store from downloading anything from it.
Trowing error: Error 0x80240438
Either add as option to block/not block , or remove from blocking?

**Comment by 10se1ucgo** [comment]
There are options already.

**Comment by IceLancerSR** [comment]
What do u mean there are options?that ip is not listed in IP adresses to be blocked nor do i see option to click for this specific one anywhere.

**Comment by 10se1ucgo** [comment]
If the IP is not in the settings, then it's not blocked by DWT.
