### ISSUE TITLE
It's not reverseable...

### ISSUE THREAD

**Issue by Morthawt** [10se1ucgo/DisableWinTracking#18]
So far from my tests in VMware (glad I tried it there and not on my main PC) this is not reverseable. Please add the ability to disable all the tracking and then to re-enable the tracking if needed.

**Comment by 10se1ucgo** [comment]
The program's name is "DisableWinTracking"

If for whatever stupid reason you want to re-enable it, you're looking in the wrong place. Read the code and do the opposite of it.

**Comment by Morthawt** [comment]
The point is sometimes things break. If you make a technical program like this which alters critical system settings it is customary to provide an ability for the user to undo what they did. Else a "normal" user who downloads this with the hopes of becoming more private and secure, who later finds out important things like feedback apps and other things no longer work then have no idea how to make it work. Your program/you get the flack with their comments like "it broke my windows". But of course it is your choice, I am just making a recommendation here. I cannot endorse this without the ability for users to undo what was done.

**Comment by 10se1ucgo** [comment]
Undoing it is extremely easy, just remove all of the entries in C:\Windows\System32\drivers\etc\hosts

None of the other fixes will affect the examples you've given.

**Comment by Morthawt** [comment]
Well it was only an example. My point was there are always possible unforeseen consequences for "tweaking" the operating system and the program used to tweak them should let the user untweak them. Like msconfig, people can make changes to the OS but they can also undo those changes. While I can alter a host file in my sleep "normal" users would have no hope of pulling it off easily or even realise they would need to in order to undo what the program did. It should be possible for the program to check the status of the individual things and provide a screen to undo changes. For the host file perhaps you could encapsulate your rules inside a commented area so you could find and replace everything in that section to undo what was done. I just strongly recommend you do something to allow users to undo the changes because I know what normal users are like and it would save you a lot of support in the long run and avoid possible negative opinions being shared online.

**Comment by 10se1ucgo** [comment]
Just for you, I'll make a small tool to do it. But I won't offer support for it.

**Comment by Morthawt** [comment]
Thanks. If it is something a user can choose to download the same way they can download your tool and it gets updated to reflect undo-operations of what ever newer upgrades can do to the system I think it will be incredibly helpful for users and save you from a lot of potential negativity, as this tool is starting to be reported by news websites which as you might expect will draw in far more normal users than just having it online if people know how to locate it.

**Comment by nathan-alden** [comment]
Why the hostility? This request is completely standard, and all the reasons given for you to provide it are perfectly justified. Calm down; no one's attacking your ego, or the work you've already done. I agree with the need to undo the changes; if it's so simple to do, it should be simple to code, no?

**Comment by RaedsLab** [comment]
:+1:  Users want to undo anything that could have broke their system. This is pretty standard.

**Comment by Talyrius** [comment]
Indeed.

**Comment by 10se1ucgo** [comment]
It's an open source project, you wan't to reverse something? Read the code and write it yourself. I'm not doing any favors.

**Comment by ocdtrekkie** [comment]
@10se1ucgo Some friendly advice: It's really cool you're a 13-year-old, because a lot of smart people are paying attention to your project! I found your project through Hacker News, which is heavily perused by many of the smartest people in Silicon Valley!

Many open source authors choose a very narrow scope for their project and reject requests for large additional work (or they invite other users to contribute the code themselves via a pull request). It's perfectly okay to just say "I'm not doing this".

But I'd recommend against calling people 'stupid'. Just say 'I'm not planning to develop this feature'. Or even 'I'm not planning to develop this feature, but if you'd like to contribute it, I'll accept the PR'.

**Comment by nathan-alden** [comment]
For anyone reading this issue: I've rewritten this project in PowerShell and added undo capabilities. You can find it here: https://github.com/nathan-alden/windows-10-tracking

**Comment by piqus** [comment]
+1 @nathan-alden

**Comment by 10se1ucgo** [comment]
@nathan-alden I'll look into those and provide similar functionality, thanks.

**Comment by rythmshifter** [comment]
this actually throttled my net connection to 1mb/sec from the 5mb/sec I was getting previously.  removing the entries in the HOSTS file has not changed anything.  any other ideas what might have broken?

**Comment by 10se1ucgo** [comment]
Hello all, I can finally say that being able to revert everything is now implemented in c286ab3fa81484d244a95bff8688f34bfd149afe

I'll be uploading a build with the new feature in a couple of minutes.

**Comment by Morthawt** [comment]
Very nice indeed. Such revert/undo functionality is truly crucial to the success of a program like this and the protection of it's users in case of strange effects.

**Comment by 10se1ucgo** [comment]
Apologies to everyone for my previous behavior, the build is now up and you can download it [here](https://github.com/10se1ucgo/DisableWinTracking/releases/tag/v2.1).
