### ISSUE TITLE
msvcr100.dll missing

### ISSUE THREAD

**Issue by Cephel** [10se1ucgo/DisableWinTracking#184]
**INFORMATION:**

* Windows 10 Pro
* 64bit
* Options used: Not applicable

**LOG:**

```python
Not applicable
```

Specified library is part of Microsoft Visual C++ 2010 Redistributable, specifically the x86 version. The link to it can be found here: http://www.microsoft.com/download/en/details.aspx?id=5555

Picture for reference:
![](http://i.imgur.com/fNM1T4N.png)

I recently reinstalled Windows 10 and it does not seem to come with the runtime. Consider displaying a more user friendly error in this case.

**Comment by 10se1ucgo** [comment]
I don't create those error messages. They're created by the operating system.
