### ISSUE TITLE
Certain items failed, unexpected functionality loss

### ISSUE THREAD

**Issue by ckasdf** [10se1ucgo/DisableWinTracking#188]
**INFORMATION:**
I ran this as admin, but a few things didn't work, and I had an unexpected functionality loss, both described below.  I used all the options at the top except for "more tracking domains," since skype is used.  Everything but what's listed below completed successfully.

Functionality loss: searching from the start menu for a local program (Firefox, LibreOffice, etc) doesn't work at this point.  What would I need to re-enable to fix this? 
- Windows Edition (Home/Pro/Enterprise): Home
- Architecture (32bit/64bit): 64
- Options used:
  -Clear DiagTrack log
  -Windows Defender collection
  -Uninstall OneDrive

**LOG:**
12:41:05 INFO: Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)] on win32
12:41:05 INFO: ('Windows', 'kw-gate', '10', '10.0.10586', 'AMD64', 'Intel64 Family 6 Model 42 Stepping 7, GenuineIntel')
12:52:30 ERROR: DiagTrack: Failed to clear DiagTrack log -- could not take ownership of file
Traceback (most recent call last):
  File "dwt_util.py", line 92, in clear_diagtrack
  File "dwt_util.py", line 263, in subprocess_handler
CalledProcessError: Command '['takeown', '/f', 'C:/ProgramData/Microsoft/Diagnosis/ETLLogs/AutoLogger/AutoLogger-Diagtrack-Listener.etl', '&&', 'icacls', 'C:/ProgramData/Microsoft/Diagnosis/ETLLogs/AutoLogger/AutoLogger-Diagtrack-Listener.etl', '/grant', 'administrators:F']' returned non-zero exit status 1
12:52:30 CRITICAL: DiagTrack: Error output:

12:52:30 ERROR: Registry: Unable to mody Windows Defender Sample Submission key.
Traceback (most recent call last):
  File "dwt_util.py", line 205, in set_registry
WindowsError: [Error 5] Access is denied
12:52:30 ERROR: Registry: Unable to mody Windows Defender Spynet key.
Traceback (most recent call last):
  File "dwt_util.py", line 205, in set_registry
WindowsError: [Error 5] Access is denied
12:52:30 INFO: OneDrive: unable to uninstall
12:52:30 INFO: Done. It's recommended that you reboot as soon as possible for the full effect.
12:52:30 INFO: If you feel something didn't work properly, please press the 'Report an issuebutton and follow the directions

``` python
REPLACE THIS WITH DWT.LOG
```

**Comment by Didey** [comment]
I would assume that it has something to do with Cortana, is it disabled on your machine?
