### ISSUE TITLE
Might have used this in the past, Skype not working

### ISSUE THREAD

**Issue by abdusamed91** [10se1ucgo/DisableWinTracking#189]
- Windows 10 Enterprise
- 64bit

I don't know which "privacy fix' I used exactly but it's starting to bother me a lot. Skype and onedrive started not to work after the fix.

Is there a way to undo it and reply privacy fix?

**Comment by 10se1ucgo** [comment]
Try undoing both of the domain blocks + IP block.

**Comment by Daniil1288** [comment]
remove `apps.skype.com, ui.skype.com, m.hotmail.com, s.gateway.messenger.live.com` from your hosts file. should work then.

**Comment by leannecrow** [comment]
It didn't have Skype though in the host file which I guess was removed when I ran an earlier version of the tool. I removed everything related to msedge but still the application doesn't work. Skype is working but msedge isn't
