### ISSUE TITLE
Remove hosts file tweaking

### ISSUE THREAD

**Issue by CrisBRM** [10se1ucgo/DisableWinTracking#19]
>While the inital reflex may be to block all of the above servers via HOSTS, it turns out this won't work: Microsoft has taken the care to hardcode certain IPs, meaning that there is no DNS lookup and no HOSTS consultation. However, if the above servers are blocked via HOSTS, Windows will pretend to be crippled by continuously throwing errors, while still maintaining data collection in the background. Other than an increase in errors, HOSTS blocking did not affect the volume, frequency, or rate of data being transmitted. 

http://localghost.org/posts/a-traffic-analysis-of-windows-10

**Comment by ATouhou** [comment]
Wow... That's pure evil

Thnx 4 info Cris
Den 12/08/2015 8.03 PM skrev "Cris" <notifications@github.com>:

**Comment by mr-flibble** [comment]
Hello, thank you for this text. 
I just want to say that I dont belive http://aeronet.cz/ (source) - This web is Rusin/Putin propaganda 
(Czech Security Information Service say so) - https://cs.wikipedia.org/wiki/Aeronet.cz 

Did anyone else who not get paid from Kremlin analyzed Windows 10?:-)
PS: sorry for bad english.

**Comment by 10se1ucgo** [comment]
The only IPs that are white listed in the DNS dll are update servers, activation servers, support and MSDN.
