### ISSUE TITLE
Incorrect tab order in the "preinstalled apps" section

### ISSUE THREAD

**Issue by jimbo1qaz** [10se1ucgo/DisableWinTracking#190]
When I tab through the "Built-in Apps" section, the highlight jumps from the bottom of the first column to the top of the third, then jumps around randomly. You should fix the tab order.

**Comment by 10se1ucgo** [comment]
Wish I could, but I can't. The check boxes are generated on the fly.

**Comment by jimbo1qaz** [comment]
Maybe you could sort apps before inserting them as checkboxes?

Or you could manually insert tab index properties (I'm not sure how Win32 works)?

**Comment by 10se1ucgo** [comment]
I could, but it would be difficult to add new boxes. I'll look into it in the future. It's not a big deal right now.
