### ISSUE TITLE
“The program can’t start because MSVCR100.dll is missing from your computer.”

### ISSUE THREAD

**Issue by Masterstone** [10se1ucgo/DisableWinTracking#192]
Some users may get this error when running this as administrator. 
**“The program can’t start because MSVCR100.dll is missing from your computer.”**

What hides behind this name is the Microsoft Visual C++ Redistributable which can easily be downloaded on the Microsoft website as x86 or x64 edition:

32 bit: http://www.microsoft.com/download/en/details.aspx?id=5555

64 bit: http://www.microsoft.com/download/en/details.aspx?id=14632

**To fix this I had to download and install both  32/64 bit versions of this**

**INFORMATION:**
- Windows Edition (Home/Pro/Enterprise): Pro
- Architecture (32bit/64bit): 64bit
- Options used: ALL

**LOG:**
21:41:56 INFO: Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)] on win32
21:41:56 INFO: ('Windows', 'W764VM-PC', '10', '10.0.10586', 'AMD64', 'Intel64 Family 6 Model 23 Stepping 7, GenuineIntel')
21:41:56 INFO: DisableWinTracking version 3.0.1
21:43:37 INFO: Successfully removed app 'getstarted'
21:43:58 INFO: Successfully removed app 'bingnews'
21:44:39 INFO: Successfully removed app 'zunevideo'
21:44:39 INFO: Successfully removed app 'windowsphone'
21:44:39 INFO: Successfully removed app 'skypeapp'
21:44:39 INFO: Successfully removed app 'bingfinance'
21:44:39 INFO: Successfully removed app 'solitairecollection'
21:44:39 INFO: Successfully removed app 'officehub'
21:44:39 INFO: Successfully removed app 'bingweather'
21:44:39 INFO: Successfully removed app 'zunemusic'
21:44:39 INFO: Successfully removed app 'photos'
21:44:39 INFO: Successfully removed app '3dbuilder'
21:44:39 INFO: Successfully removed app 'xboxapp'
21:44:39 INFO: Successfully removed app 'soundrecorder'
21:44:39 INFO: Successfully removed app 'onenote'
21:44:39 INFO: Successfully removed app 'windowscommunicationsapps'
21:45:03 INFO: Successfully removed app 'windowsmaps'
21:45:03 INFO: Successfully removed app 'sway'
21:45:03 INFO: Successfully removed app 'bingsports'
21:45:03 INFO: Successfully removed app 'people'
21:45:03 INFO: Successfully removed app 'windowscamera'
21:48:58 INFO: IP Blocker: The IP 134.170.30.202 was successfully blocked.
21:48:59 INFO: IP Blocker: The IP 137.116.81.24 was successfully blocked.
21:48:59 INFO: IP Blocker: The IP 157.56.106.189 was successfully blocked.
21:48:59 INFO: IP Blocker: The IP 2.22.61.43 was successfully blocked.
21:49:00 INFO: IP Blocker: The IP 2.22.61.66 was successfully blocked.
21:49:00 INFO: IP Blocker: The IP 204.79.197.200 was successfully blocked.
21:49:00 INFO: IP Blocker: The IP 23.218.212.69 was successfully blocked.
21:49:01 INFO: IP Blocker: The IP 64.4.54.254 was successfully blocked.
21:49:01 INFO: IP Blocker: The IP 65.39.117.230 was successfully blocked.
21:49:01 INFO: IP Blocker: The IP 65.52.108.33 was successfully blocked.
21:49:02 INFO: IP Blocker: The IP 65.55.108.23 was successfully blocked.
21:49:02 ERROR: DiagTrack: Failed to clear DiagTrack log -- could not take ownership of file
Traceback (most recent call last):
  File "dwt_util.py", line 92, in clear_diagtrack
  File "dwt_util.py", line 263, in subprocess_handler
CalledProcessError: Command '['takeown', '/f', 'C:/ProgramData/Microsoft/Diagnosis/ETLLogs/AutoLogger/AutoLogger-Diagtrack-Listener.etl', '&&', 'icacls', 'C:/ProgramData/Microsoft/Diagnosis/ETLLogs/AutoLogger/AutoLogger-Diagtrack-Listener.etl', '/grant', 'administrators:F']' returned non-zero exit status 1
21:49:02 CRITICAL: DiagTrack: Error output:

21:49:03 INFO: Services: Succesfully removed service 'dmwappushsvc'
21:49:03 INFO: Services: Succesfully removed service 'DiagTrack'
21:49:03 INFO: Registry: Successfully modified dmwappushsvc key.
21:49:03 INFO: Registry: Successfully modified DiagTrack key.
21:49:03 INFO: Registry: Successfully modified AllowTelemetry key.
21:49:03 ERROR: Registry: Unable to mody Windows Defender Sample Submission key.
Traceback (most recent call last):
  File "dwt_util.py", line 205, in set_registry
WindowsError: [Error 5] Access is denied
21:49:03 ERROR: Registry: Unable to mody Windows Defender Spynet key.
Traceback (most recent call last):
  File "dwt_util.py", line 205, in set_registry
WindowsError: [Error 5] Access is denied

``` python
REPLACE THIS WITH DWT.LOG
```

**Comment by mackonsti** [comment]
Thank you, this worked for me too, on a clean Windows 10 installation. Indeed, even if my Win10 is x64, one needs to setup both x86 and x64 of the MSVCR100.dll redistributable run-time package. Many thanks, mate.
