### ISSUE TITLE
Urllib2 does not exist in Python 3.5

### ISSUE THREAD

**Issue by FolkertRA** [10se1ucgo/DisableWinTracking#196]
When starting dwt with Python 3.5, it cannot import urllib2 (in dwt_about.py). This is becasue this library has been merged with urllib.
Solution: 
change the import statement to
"import urllib.request as urllib2"

**Comment by 10se1ucgo** [comment]
I backported the tool from Python 3 to 2 because pyinstaller was having issues for a number of people. I'll look into whether or not pyinstaller seems to be fixed now and port it back to Python 3.

**Comment by Ruined1** [comment]
Python 2 is still relevant, going to 3 wouldn't really be an enhancement. Going to close this issue for now.
