### ISSUE TITLE
Didn't uninstall OneDrive as indicated by arrows in report. Thank you for this amazing program :D

### ISSUE THREAD

**Issue by tartooth** [10se1ucgo/DisableWinTracking#197]
17:38:03 INFO: Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)] on win32
17:38:03 INFO: ('Windows', 'Betty-Fruits', '10', '10.0.10586', 'AMD64', 'Intel64 Family 6 Model 58 Stepping 9, GenuineIntel')
17:38:03 INFO: DisableWinTracking version 3.0.1
17:38:27 INFO: Successfully removed app 'getstarted'
17:38:27 INFO: Successfully removed app 'bingnews'
17:38:28 INFO: Successfully removed app 'zunevideo'
17:38:29 INFO: Successfully removed app 'windowsphone'
17:38:30 INFO: Successfully removed app 'skypeapp'
17:38:30 INFO: Successfully removed app 'bingfinance'
17:38:30 INFO: Successfully removed app 'officehub'
17:38:31 INFO: Successfully removed app 'zunemusic'
17:38:31 INFO: Successfully removed app 'xboxapp'
17:38:31 INFO: Successfully removed app 'onenote'
17:38:31 INFO: Successfully removed app 'windowscommunicationsapps'
17:38:31 INFO: Successfully removed app 'windowsmaps'
17:38:31 INFO: Successfully removed app 'sway'
17:38:31 INFO: Successfully removed app 'bingsports'
17:38:31 INFO: Successfully removed app 'people'
17:38:31 INFO: Successfully removed app 'windowscamera'
17:38:40 INFO: Registry: Successfully modified ListPin key.
17:38:40 INFO: Registry: Successfully modified FileSync key.
17:38:40 INFO: OneDrive: unable to uninstall <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
17:38:40 INFO: Done. It's recommended that you reboot as soon as possible for the full effect.
17:38:40 INFO: If you feel something didn't work properly, please press the 'Report an issuebutton and follow the directions

**Comment by tartooth** [comment]
I did a little digging, and I may have "disabled" one drive, but it's still installed from what I can tell.

May have been just my configuration on my PC.

Again, thank you for this great program!

**Comment by 10se1ucgo** [comment]
I think it has something to do with the installer exit codes. Normally, a non-zero exit code indicates an error, but considering how Windows goes against all standards it might not be the case for Windows. I have the same error, but OneDrive is indeed off. I think you should be okay.
