### ISSUE TITLE
A Couple of Errors

### ISSUE THREAD

**Issue by George-R-O** [10se1ucgo/DisableWinTracking#198]
**INFORMATION:**

* Windows 10 Pro:
* Architecture 64bit:
* Options used:

15:28:11 INFO: Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)] on win32
15:28:11 INFO: ('Windows', 'Noddy-V', '10', '10.0.10586', 'AMD64', 'Intel64 Family 6 Model 58 Stepping 9, GenuineIntel')
15:28:11 INFO: DisableWinTracking version 3.0.1
15:29:28 INFO: Successfully removed app 'getstarted'
15:29:29 INFO: Successfully removed app 'windowsphone'
15:29:29 INFO: Successfully removed app 'zunevideo'
15:29:30 INFO: Successfully removed app 'windowsmaps'
15:29:30 INFO: Successfully removed app 'skypeapp'
15:29:30 INFO: Successfully removed app 'bingfinance'
15:29:30 INFO: Successfully removed app 'officehub'
15:29:30 INFO: Successfully removed app 'zunemusic'
15:29:30 INFO: Successfully removed app 'photos'
15:29:31 INFO: Successfully removed app 'xboxapp'
15:29:31 INFO: Successfully removed app 'bingsports'
15:29:31 INFO: Successfully removed app 'people'
15:29:35 INFO: IP Blocker: The IP 134.170.30.202 was successfully blocked.
15:29:35 INFO: IP Blocker: The IP 137.116.81.24 was successfully blocked.
15:29:35 INFO: IP Blocker: The IP 157.56.106.189 was successfully blocked.
15:29:35 INFO: IP Blocker: The IP 2.22.61.43 was successfully blocked.
15:29:35 INFO: IP Blocker: The IP 2.22.61.66 was successfully blocked.
15:29:36 INFO: IP Blocker: The IP 204.79.197.200 was successfully blocked.
15:29:36 INFO: IP Blocker: The IP 23.218.212.69 was successfully blocked.
15:29:36 INFO: IP Blocker: The IP 64.4.54.254 was successfully blocked.
15:29:36 INFO: IP Blocker: The IP 65.39.117.230 was successfully blocked.
15:29:36 INFO: IP Blocker: The IP 65.52.108.33 was successfully blocked.
15:29:36 INFO: IP Blocker: The IP 65.55.108.23 was successfully blocked.
15:29:36 ERROR: DiagTrack: **Failed to clear DiagTrack log -- could not take ownership of file
Traceback (most recent call last):**
  File "dwt_util.py", line 92, in clear_diagtrack
  File "dwt_util.py", line 263, in subprocess_handler
CalledProcessError: Command '['takeown', '/f', 'C:/ProgramData/Microsoft/Diagnosis/ETLLogs/AutoLogger/AutoLogger-Diagtrack-Listener.etl', '&&', 'icacls', 'C:/ProgramData/Microsoft/Diagnosis/ETLLogs/AutoLogger/AutoLogger-Diagtrack-Listener.etl', '/grant', 'administrators:F']' returned non-zero exit status 1
15:29:36 CRITICAL: DiagTrack: **Error output**:

15:29:36 INFO: Services: Succesfully removed service 'dmwappushsvc'
15:29:36 INFO: Services: Succesfully removed service 'DiagTrack'
15:29:36 INFO: Registry: Successfully modified dmwappushsvc key.
15:29:36 INFO: Registry: Successfully modified DiagTrack key.
15:29:36 INFO: Registry: Successfully modified AllowTelemetry key.
15:29:36 ERROR: Registry: **Unable to mody Windows Defender Sample Submission key.
Traceback (most recent call last):**
  File "dwt_util.py", line 205, in set_registry
WindowsError: [Error 5] Access is denied
15:29:36 ERROR: Registry: **Unable to mody Windows Defender Spynet key**.
Traceback (most recent call last):
  File "dwt_util.py", line 205, in set_registry
WindowsError: [Error 5] **Access is denied**
15:29:36 INFO: Registry: Successfully modified Windows Defender Delivery Optimization Download key.
15:29:36 INFO: Registry: Successfully modified WifiSense Open-ness key.
15:29:36 INFO: Registry: Successfully modified WifiSense Credential Share key.
15:29:36 INFO: Registry: Successfully modified ListPin key.
15:29:36 INFO: Registry: Successfully modified FileSync key.
15:29:36 INFO: OneDrive**: unable to uninstall**
15:29:36 INFO: Done. It's recommended that you reboot as soon as possible for the full effect.
15:29:36 INFO: If you feel something didn't work properly, please press the 'Report an issuebutton and follow the directions

**Comment by 10se1ucgo** [comment]
DiagTrack error is normal, especially if you've ran a similar tweak before.

Windows Defender error discussed here #88 

OneDrive error discused here: #197
