### ISSUE TITLE
Doing a similar thing

### ISSUE THREAD

**Issue by W4RH4WK** [10se1ucgo/DisableWinTracking#2]
I started a similar project a few hours ago, you might want to have a look at it and see if you can scavenge some things.

https://github.com/W4RH4WK/Debloat-Windows-10

**Comment by 10se1ucgo** [comment]
Ah! I knew I was missing something.

I'll work on Windows Defender and OneDrive in a couple days.

Thanks for this.

**Comment by W4RH4WK** [comment]
I am still far from having a complete collection, do note that i haven't found time for extensive testing.

**Comment by maci0** [comment]
maybe you should work together ;)

**Comment by W4RH4WK** [comment]
We'll both benefit from using the same settings but while @10se1ucgo will probably advance his python based GUI tool i will stick to plain Powershell scripts.

**Comment by urras** [comment]
@W4RH4WK @10se1ucgo I recently worked on [similar stuff](https://github.com/hahndorf/Set-Privacy/issues/2) in [hahndorf/Set-Privacy](https://github.com/hahndorf/Set-Privacy). You might find a few helpful reg keys in there

**Comment by W4RH4WK** [comment]
@urras thanks for the link, will have a look at it later.

**Comment by Ruined1** [comment]
I added the suggested improvements from Set-Privacy several commits ago.

Closing and marking complete.
