### ISSUE TITLE
UnDo - Is there such a function?

### ISSUE THREAD

**Issue by George-R-O** [10se1ucgo/DisableWinTracking#216]
Once DisableWinTracking has been run on a PC is there any way to undo all the "fixes" that it applied without re-installing Windows 10?

Clearly I can switch back "on" all the privacy settings that were switched "off" but how can I re-enable all the other background tasks that were disabled, telemetry etc.?

Thanks

**Comment by speedt3st** [comment]
There is not any botton actually in this software able to do that. I think it's focusing on figure out help prevent hassles from Windows's tracking services.

**Comment by Atavic** [comment]
Backup the registry and the host file before applying.
