### ISSUE TITLE
Consquences of blocking some host names

### ISSUE THREAD

**Issue by simplypeachy** [10se1ucgo/DisableWinTracking#22]
I do a lot of work with tracking/advert blocking so would like to share my experiences.

atdmt.com
Sometimes used by web sites to serve their own internal links. This is third-party tracking without a doubt, but blocking view.atdmt.com may stop users from browsing a web site that employs this method. For this reason, I (begrudgingly) do not block view.atdmt.com. Ironically, the example I have recorded is within microsoft.com :-)

s0.2mdn.net
I have come across this host name being used in streaming video sites, blocking of which prevents the user from viewing the video at all.

fe2.update.microsoft.com.akadns.net
statsfe2.update.microsoft.com.akadns.net
statsfe2.update.microsoft.com.akadns.net
I would strongly recommend against blocking any host names with "update.microsoft.com" in them at all, as blocking any part of Windows Update's core functionality is a bad idea. Some of these do look statistics-related, but I am always very cautious about reducing the security of a customer's computer.

schemas.microsoft.akadns.net
This is a (CDN'd) host name used by various core parts of Microsoft's web site.

www.msftncsi.com
This is used (IME, exclusively) by a Windows machine to check to see if it's online, and adjust the systray's Network icon as appropriate.

watson.microsoft.com
reports.wes.df.telemetry.microsoft.com
services.wes.df.telemetry.microsoft.com
watson.telemetry.microsoft.com
watson.ppe.telemetry.microsoft.com
wes.df.telemetry.microsoft.com
survey.watson.microsoft.com
watson.telemetry.microsoft.com.nsatc.net
The "Watson" part of these host names refer to Microsoft's Windows Error Reporting system, where mis-behaving drivers, programs and part of Windows are recorded and, if permitted, sent to Microsoft for analysis. As a guy who fixes computers for a living, with 15 years experience, I can testify that WER is a Good Thing. It does not report to Microsoft without permission (Win10's ignorance of privacy settings not included). Without it I would have had a much more difficult life, and as a result, as would my customers! Of all the telemetry that a system can send back, I always try to enable this sort of reporting as I believe it genuinely makes a positive difference. Maybe it's worth having a "Extra paranoid" option that goes as far as disabling this sort of "important" telemetry? Especially with all the Windows 10 bugs!

**Comment by 10se1ucgo** [comment]
I'm working on a 2.0 rewrite, I'll probably add these to a button of the sort you suggested.

As for the update domains/error reporting domains, all the important ones are whitelisted (along with MSDN and activation domains) in the DNS dll.

**Comment by Owyn** [comment]
Yes, a button or checkbox for "soft mode" might be good, to leave upates or error reporting functioning for example.

**Comment by 10se1ucgo** [comment]
Fixed in 2.0

Now there is an "extra hosts" checkbox.

**Comment by HappySkyPoodle** [comment]
how do we know you're not an NSA employee tricking us into re-enabling hidden backdoors

**Comment by 10se1ucgo** [comment]
@HappySkyPoodle Because if you have any level of intelligence you can read the source code.
