### ISSUE TITLE
Can't shut down computer?

### ISSUE THREAD

**Issue by bzsl** [10se1ucgo/DisableWinTracking#221]
**INFORMATION:**
- Windows Edition (Home/Pro/Enterprise): Pro
- Architecture (32bit/64bit): 64
- Options used: All top options except for OneDrive, Disable | Privacy. Removed "Get Office App" "Get Skype App" "Get Started App"

After running Disable Windows 10 Tracking, it seems that the Shut Down command no longer works. Instead, it takes several minutes for the command to register. My best guess is that it's waiting on a remote call of some kind to something that's been blocked, and waiting for it to time out. Restart still works, but I have to do a hard power-off in order to simply turn off the machine.

Stop-Computer -Force in powershell doesn't behave any differently.

**LOG:**
No longer have log. Problems discovered after execution.

``` python
REPLACE THIS WITH DWT.LOG
```

**Comment by pLesur** [comment]
Same problem here.
Screen just goes black then I am back at the login screen.

**Comment by nukebloodaxe** [comment]
Sounds curious, just for clarification (for 10se1ucgo) are you using a 
local account, or a windows live account to login to your machine?

I've seen this behaviour happen on machines before without 
DisableWinTracking, and a clarification here would allow me to narrow 
the problem down a bit.

**Comment by bzsl** [comment]
I set up my account as a local account initially, then joined it to a domain; after the machine was joined, I signed in with a domain account and used DisableWinTracking. For what it's worth, my domain account is associated with my microsoft account on this machine, but I don't remember if I associated it before or after running DisableWinTracking, unfortunately.
