### ISSUE TITLE
Anniversary Update Issues

### ISSUE THREAD

**Issue by Teumer** [10se1ucgo/DisableWinTracking#225]
**INFORMATION:**
- Windows Edition (Home/Pro/Enterprise): Pro
- Architecture (32bit/64bit): 64
- Options used: Select All Used, Service Method: Disabled

**LOG:**

21:00:24 INFO: Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)] on win32
21:00:24 INFO: ('Windows', 'Omitted', '10', '10.0.14393', 'AMD64', 'Intel64 Family 6 Model 94 Stepping 3, GenuineIntel')
21:00:24 INFO: DisableWinTracking version 3.0.1
21:00:59 INFO: IP Blocker: The IP 134.170.30.202 was successfully blocked.
21:00:59 INFO: IP Blocker: The IP 137.116.81.24 was successfully blocked.
21:00:59 INFO: IP Blocker: The IP 157.56.106.189 was successfully blocked.
21:00:59 INFO: IP Blocker: The IP 2.22.61.43 was successfully blocked.
21:00:59 INFO: IP Blocker: The IP 2.22.61.66 was successfully blocked.
21:00:59 INFO: IP Blocker: The IP 204.79.197.200 was successfully blocked.
21:00:59 INFO: IP Blocker: The IP 23.218.212.69 was successfully blocked.
21:00:59 INFO: IP Blocker: The IP 64.4.54.254 was successfully blocked.
21:00:59 INFO: IP Blocker: The IP 65.39.117.230 was successfully blocked.
21:00:59 INFO: IP Blocker: The IP 65.52.108.33 was successfully blocked.
21:00:59 INFO: IP Blocker: The IP 65.55.108.23 was successfully blocked.
21:01:00 ERROR: DiagTrack: Failed to clear DiagTrack log -- could not take ownership of file
Traceback (most recent call last):
  File "dwt_util.py", line 92, in clear_diagtrack
  File "dwt_util.py", line 263, in subprocess_handler
CalledProcessError: Command '['takeown', '/f', 'C:/ProgramData/Microsoft/Diagnosis/ETLLogs/AutoLogger/AutoLogger-Diagtrack-Listener.etl', '&&', 'icacls', 'C:/ProgramData/Microsoft/Diagnosis/ETLLogs/AutoLogger/AutoLogger-Diagtrack-Listener.etl', '/grant', 'administrators:F']' returned non-zero exit status 1
21:01:00 CRITICAL: DiagTrack: Error output:

21:01:00 INFO: Services: Succesfully removed service 'dmwappushsvc'
21:01:00 INFO: Services: Succesfully removed service 'DiagTrack'
21:01:00 INFO: Registry: Successfully modified dmwappushsvc key.
21:01:00 INFO: Registry: Successfully modified DiagTrack key.
21:01:00 INFO: Registry: Successfully modified AllowTelemetry key.
21:01:00 ERROR: Registry: Unable to mody Windows Defender Sample Submission key.
Traceback (most recent call last):
  File "dwt_util.py", line 205, in set_registry
WindowsError: [Error 5] Access is denied
21:01:00 ERROR: Registry: Unable to mody Windows Defender Spynet key.
Traceback (most recent call last):
  File "dwt_util.py", line 205, in set_registry
WindowsError: [Error 5] Access is denied
21:01:00 INFO: Registry: Successfully modified Windows Defender Delivery Optimization Download key.
21:01:00 INFO: Registry: Successfully modified WifiSense Open-ness key.
21:01:00 INFO: Registry: Successfully modified WifiSense Credential Share key.
21:01:00 INFO: Registry: Successfully modified ListPin key.
21:01:00 INFO: Registry: Successfully modified FileSync key.
21:01:00 INFO: OneDrive: unable to uninstall
21:01:00 INFO: Done. It's recommended that you reboot as soon as possible for the full effect.
21:01:00 INFO: If you feel something didn't work properly, please press the 'Report an issuebutton and follow the directions

**Comment by Atavic** [comment]
Maybe Onedrive was connecting to MS?
Was your PC online while running this?
