### ISSUE TITLE
AllowTelemetry can't be disabled in non-server OS

### ISSUE THREAD

**Issue by ImDevinC** [10se1ucgo/DisableWinTracking#23]
From Microsoft's Policy CSP at https://msdn.microsoft.com/en-us/library/windows/hardware/dn904962(v=vs.85).aspx

This isn't necessarily an issue with your software as it's not something you can fix due to how MS designed it, but you may want to update wording so people are a bit more aware.

<img width="681" alt="screen shot 2015-08-13 at 12 40 48 pm" src="https://cloud.githubusercontent.com/assets/3997333/9256984/a9db1840-41b8-11e5-878f-85555f162fc1.png">

**Comment by 10se1ucgo** [comment]
Yeah, I know. It's why selecting telemetry auto enables the host modification, as the hosts mod works as a decent workaround. I'll change the tooltip to reflect on this.
