### ISSUE TITLE
Replace with a short description of your problem

### ISSUE THREAD

**Issue by richsketchy** [10se1ucgo/DisableWinTracking#233]
**INFORMATION:**
- Windows Edition (Home/Pro/Enterprise): 
- Architecture (32bit/64bit): 
- Options used:

**LOG:**

``` python
REPLACE THIS WITH DISABLEWINTRACKING.LOG
```

**Comment by richsketchy** [comment]
I was wondering if there is a way to fix this or is there a better program to make sure I am safe?

**Comment by Svetomech** [comment]
To fix what, exactly?

**Comment by hweidi** [comment]
I believe the tool is no longer working with the latest Windows 10 update
