### ISSUE TITLE
Console log showed handful of errors.  Not sure if they are expected errors.

### ISSUE THREAD

**Issue by bduhbya** [10se1ucgo/DisableWinTracking#235]
**INFORMATION:**
- Windows Edition (Home/Pro/Enterprise):
- Architecture (32bit/64bit):
- Options used:

**LOG:**

``` python
REPLACE THIS WITH DWT.LOG
```

**Comment by Atavic** [comment]
No log report here.

**Comment by bduhbya** [comment]
My mistake. When I get back to the house I will take a look for the logs and attach them. I think I thought the upload was automated.

**Comment by bduhbya** [comment]
Totally forgot to come back and do this:

22:20:01 ERROR: DiagTrack: Failed to clear DiagTrack log -- could not take ownership of file
Traceback (most recent call last):
  File "dwt_util.py", line 92, in clear_diagtrack
  File "dwt_util.py", line 263, in subprocess_handler
CalledProcessError: Command '['takeown', '/f', 'C:/ProgramData/Microsoft/Diagnosis/ETLLogs/AutoLogger/AutoLogger-Diagtrack-Listener.etl', '&&', 'icacls', 'C:/ProgramData/Microsoft/Diagnosis/ETLLogs/AutoLogger/AutoLogger-Diagtrack-Listener.etl', '/grant', 'administrators:F']' returned non-zero exit status 1
22:20:01 CRITICAL: DiagTrack: Error output:

22:20:01 INFO: Registry: Successfully modified AllowTelemetry key.
22:20:07 ERROR: Hosts: Failed to modify hosts file
Traceback (most recent call last):
  File "dwt_util.py", line 231, in host_file
IOError: [Errno 13] Permission denied: 'C:\\Windows\\System32/drivers/etc/hosts'
22:20:07 ERROR: Registry: Unable to mody Windows Defender Sample Submission key.
Traceback (most recent call last):
  File "dwt_util.py", line 205, in set_registry
WindowsError: [Error 5] Access is denied
22:20:07 ERROR: Registry: Unable to mody Windows Defender Spynet key.
Traceback (most recent call last):
  File "dwt_util.py", line 205, in set_registry
WindowsError: [Error 5] Access is denied
