### ISSUE TITLE
"Trojan" detected

### ISSUE THREAD

**Issue by GunArm** [10se1ucgo/DisableWinTracking#240]
Has anyone else reported this?  I'm not certain if it's a failed heuristic, MS flinging poo at an app they don't like, or if some other actual malware on my computer has infected this file
![capture](https://cloud.githubusercontent.com/assets/6316933/18896807/5965f4f4-84ea-11e6-92c9-47496ec3f77c.PNG)

I restored the file to check the SHA

MD5 94caac2f248a9d490e7dae02e77effe6
SHA1 e4ae88857a00f7ae0d1745c7b3c00a0d868e66b5
CRC32 9cf421f3
(It's possible that the process of having been quarantined and then restored by windows defender might have modified the file)
As far as the version, the best I can say is the Date modified (probably when I downloaded it) is July 26 2016, size is 6,921,701 bytes.

Windows 10 Home x64

**Comment by kbandla** [comment]
Just noticed this too. Windows Defender detects this as [Win32/Rundas!plock](https://www.microsoft.com/security/portal/threat/encyclopedia/entry.aspx?name=Trojan%3aWin32%2fRundas!plock&threatid=2147711527).

**Comment by GiveMeAnthony** [comment]
This project is open-source and it looks fine to me. Windows Defender is probably upset because it tries to take ownership of AutoLogger-Diagtrack-Listener.etl (in order to disable it) which is basically the built-in keylogger for Windows.

**Comment by 10se1ucgo** [comment]
Hi, sorry for the lack of responses. I haven't really been paying too much to this project (in pursuit of other, more interesting ones).

[The hash does appear to be correct](http://i.imgur.com/PKs37av.png), so it likely is just a false-positive from Windows Defender.

If anyone would like instructions on how to "decompile" the executable and reverse the code to indeed confirm that I haven't tampered with anything, feel free to ask.

**Comment by Atavic** [comment]
M$ defending its shady OS, there's another [False Positive](https://github.com/fdorg/flashdevelop/issues/1272).

**Comment by XE2XPK** [comment]
Well not only MS, but other antivirus firms are now "Detecting" DisableWinTracking
as a PUA.gen  Potencially Unwanted Application  I am using WebRoot SecureAnywere
and it was detected as: pua.gen
