### ISSUE TITLE
more domains to block

### ISSUE THREAD

**Issue by Owyn** [10se1ucgo/DisableWinTracking#25]
http://aeronet.cz/news/analyza-windows-10-ve-svem-principu-jde-o-pouhy-terminal-na-sber-informaci-o-uzivateli-jeho-prstech-ocich-a-hlasu/
and here http://habrahabr.ru/company/pt/blog/264763/
name some more webhosts to where windows 10 send info

**Comment by mr-flibble** [comment]
Hello. I just want to say that I dont belive http://aeronet.cz/ (source) - This web is Rusin/Putin propaganda 
(Czech Security Information Service say so) - https://cs.wikipedia.org/wiki/Aeronet.cz

**Comment by jardicc** [comment]
I am also from the Czech Republic and I think that this site is crap.

I turned off the all tracking in Win Control panels and investigate all communication via Fiddler web debugger and an hour watching I could not find anything suspicious.

Or Fiddler can not reveal it? Through which communication protocols it works?
