### ISSUE TITLE
Sticky Notes Deleted 

### ISSUE THREAD

**Issue by abdusamed91** [10se1ucgo/DisableWinTracking#259]
Out of the blue, my sticky notes deleted along with notes on it! *Didn't expect this coming*  Data loss occurred. 

I tried using the "Revert" menu from the application but it isn't working. Window's Store can open and access the data but it can't download the application I have selected.

What could be going on? The host setting aren't reverting back.

**Comment by Didey** [comment]
Although there is no reason for this to be happening with native features of RWT, this could be caused by some relationship with sticky notes and other MS software that is effected by RWT. Although this is unlikely, please verify that it was RWT that removed your notes, and not something else.

**Comment by leannecrow** [comment]
It was the only thing I ran before losing sticky note app. Managed to
get it back and noticed Store didn't work in my country and only managed
to download it via VPN based in the US.

Does RWT block store ?
