### ISSUE TITLE
Up to date?

### ISSUE THREAD

**Issue by boelle** [10se1ucgo/DisableWinTracking#262]
Hi

As I will be forced to use win10 to get DX12 i wonder if this app is up to date with the latest b$ from m$?

I'm not paranoid, i just believe in that the only trafic windows should do is updates, virus updates and a clock adjust now and then. 

I do plan to use 64 bit, and as this is only a gaming pc i will aim for home edition which i think i got for free. Are there any reasons to go pro or enterprise?

**Comment by Didey** [comment]
It should be. If you see any weird traffic on your PC from [Wireshark](https://www.wireshark.org/), let us know in a new issue.

**Comment by boelle** [comment]
I will.... reason i asked is that there are so many tools and so many guides and people that talk like they have stolen their mouth.

my first thought was just to setup a firewall app to block anything outgoing except for those apps i can approve

**Comment by x-a-n-a-x** [comment]
Go for Enterprise (if you can). It sends the least data thanks to the "Secure" updates channel.

A good article to read: http://www.pcworld.com/article/3146925/windows/how-windows-10-data-collection-trades-privacy-for-security.html

You can also use other tools like **Winaero Tweaker 0.6.0.8** which has options to disable unnecessary services.

**Comment by boelle** [comment]
all i'm after is that it does not send data... only what is needed for updates etc... just like in the old days

**Comment by x-a-n-a-x** [comment]
Then don't use Windows10. 
Windows10 does send data, and there's almost nothing that you can do to stop this behaviour. :-(

What you can do is using [DisableWinTracking](https://github.com/10se1ucgo/DisableWinTracking), (it kind of works but still has bugs) or [Destroy Windows 10 Spying](https://github.com/Nummer/Destroy-Windows-10-Spying) (I think it worths a try) or [Winareo Tweaker](http://winaero.com/) (I advice it, it offers other nice customization features). 

You can also add new outgoing rules into your **Windows firewall with advanced security** (blocking IP ranges or softwares). Note that you can also directly add IP adresses in your host file (but I prefer the firewall way).

I would also advice you to try these freewares: [CurrPorts](http://www.nirsoft.net/utils/cports.html) and [SocketSniff](http://www.nirsoft.net/utils/socket_sniffer.html), they can help you find which softwares send data.

**Comment by boelle** [comment]
problem is that win10 is the only os that offers DX12 (so far i know)

will try the different options... thou i lean to block everything and do manual updates and only allow my games etc to do traffic
