### ISSUE TITLE
DWT crashes on startup if there's no Internet access. Remove the automatic update check. 

### ISSUE THREAD

**Issue by manad777** [10se1ucgo/DisableWinTracking#264]
UPDATE months later: it appears that DMT is no longer maintained. I suggest people use Spybot Anti-beacon as a superior alternative, though it's not open-source. 

I have a fresh Win10 system, and I wanted to apply DWT before I connected it to the Internet, because I think it's smarter this way.

I copied the installer by USB key, but it won't run because there's no Internet. I get an exception as soon as I launch it. This is poorly thought-out.

EDIT because I see from a different issue that @10se1ucgo  is aware of the problem, but laughed it off. Here's why this should be fixed: by leaving the buggy update check, you force the user to connect to the Internet before they can disable the tracking. By doing this, the tracking services can upload all the information accumulated up to that point while offline. In other words, even if DWT stops *future* tracking, it helps Win10 report tracked data accumulated prior to its installation. This should be considered a critical flaw.

It's like changing the door on a barn, without tying the horse to a post first so he doesn't bolt. "Oh, this door is only for stopping future horses, sorry about the existing ones".

**INFORMATION:**

* Windows Edition (Home/Pro/Enterprise): Home
* Architecture (32bit/64bit): 64-bit
* Options used:

**LOG:**

```python
17:07:51 INFO: Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)] on win32
17:07:51 INFO: ('Windows', 'DESKTOP-3VIFGI2', '10', '10.0.14393', 'AMD64', 'Intel64 Family 6 Model 69 Stepping 1, GenuineIntel')
17:07:51 INFO: DisableWinTracking version 3.0.1
17:07:52 CRITICAL: Traceback (most recent call last):
  File "dwt.py", line 440, in <module>
  File "dwt_about.py", line 170, in update_check
  File "urllib2.py", line 154, in urlopen
  File "urllib2.py", line 431, in open
  File "urllib2.py", line 449, in _open
  File "urllib2.py", line 409, in _call_chain
  File "urllib2.py", line 1240, in https_open
  File "urllib2.py", line 1197, in do_open
URLError: <urlopen error [Errno 11001] getaddrinfo failed>
```

**Comment by manad777** [comment]
The app should be fully functional offline. Especially given its nature.

**Comment by manad777** [comment]
Got you a pull request to fix this: https://github.com/10se1ucgo/DisableWinTracking/pull/265

**Comment by dufferzafar** [comment]
I don't have internet connection on my Windows 10 machine and having this would be really great.

**Comment by manad777** [comment]
This tool, although well-meaning, is to be considered abandoned. 

I'm not blaming the dev, he/she is free to spend their time however they want.

I suggest anyone interested in a superior tool with more features and that works online to install Spybot Anti-Beacon. I know it's not open-source, but this is from an established computer security company.

**Comment by Ruined1** [comment]
@manad777 @dufferzafar this tool is not abandoned. Sometimes things come up in life, so please be open-minded about that. I'm merging pull requests and fixing issues myself ocassionally on @10se1ucgo's behalf. We aren't paid to do this and we definitely do what we can. Thank you for your understanding.
