### ISSUE TITLE
DiagTrack ownership

### ISSUE THREAD

**Issue by paulprince** [10se1ucgo/DisableWinTracking#275]
**INFORMATION:**

* Windows Edition (Home/Pro/Enterprise):
* Architecture (32bit/64bit):
* Options used:

**LOG:**
23:59:14 INFO: Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)] on win32
23:59:14 INFO: ('Windows', 'DESKTOP-F31GFTR', '10', '10.0.14393', 'AMD64', 'Intel64 Family 6 Model 69 Stepping 1, GenuineIntel')
23:59:14 INFO: DisableWinTracking version 3.0.1
23:59:23 ERROR: DiagTrack: Failed to clear DiagTrack log -- could not take ownership of file
Traceback (most recent call last):
  File "dwt_util.py", line 92, in clear_diagtrack
  File "dwt_util.py", line 263, in subprocess_handler
CalledProcessError: Command '['takeown', '/f', 'C:/ProgramData/Microsoft/Diagnosis/ETLLogs/AutoLogger/AutoLogger-Diagtrack-Listener.etl', '&&', 'icacls', 'C:/ProgramData/Microsoft/Diagnosis/ETLLogs/AutoLogger/AutoLogger-Diagtrack-Listener.etl', '/grant', 'administrators:F']' returned non-zero exit status 1
23:59:23 CRITICAL: DiagTrack: Error output:

23:59:23 INFO: Done. It's recommended that you reboot as soon as possible for the full effect.
23:59:23 INFO: If you feel something didn't work properly, please press the 'Report an issuebutton and follow the directions

```python
REPLACE THIS WITH DWT.LOG
```

**Comment by ASBaumgarten** [comment]
I got the same issue

14:10:34 ERROR: DiagTrack: Failed to clear DiagTrack log -- could not take ownership of file
Traceback (most recent call last):
  File "dwt_util.py", line 92, in clear_diagtrack
  File "dwt_util.py", line 263, in subprocess_handler
CalledProcessError: Command '['takeown', '/f', 'C:/ProgramData/Microsoft/Diagnosis/ETLLogs/AutoLogger/AutoLogger-Diagtrack-Listener.etl', '&&', 'icacls', 'C:/ProgramData/Microsoft/Diagnosis/ETLLogs/AutoLogger/AutoLogger-Diagtrack-Listener.etl', '/grant', 'administrators:F']' returned non-zero exit status 1
14:10:34 CRITICAL: DiagTrack: Error output:
