### ISSUE TITLE
Blocking IP addresses?

### ISSUE THREAD

**Issue by odan** [10se1ucgo/DisableWinTracking#28]
Blocking MS hostnames by using the "hosts" file is ok, but how to block this MS IP addresses?

2.22.61.43
2.22.61.66
157.56.106.189

**Comment by HristoKolev** [comment]
Why can't you just add them to the hosts file? What is the problem?

**Comment by W4RH4WK** [comment]
@HristoKolev because it does not work as far as I know. The hosts file is used for DNS lookup, apparently there once was a way to block IPs by adding something like `0.0.0.0 1.3.3.7` (whereby `1.3.3.7` is the IP to block). I tried that in Win10 and it did not work. Maybe I am holding it wrong or we need another way to block traffic to certain IP addresses. Windows Firewall would be an option but that did not work either for me (a few years ago in Win7 regarding some UDP packages send outbound by a certain application).

Routing table would be another option.

**Comment by HristoKolev** [comment]
Yes. You are right. I had a temporary lapse in my understanding of what the hosts file does.

**Comment by HristoKolev** [comment]
BTW there are lots of ip addresses that are being pushed in the hosts file by the code and are not blocked by other means.

**Comment by odan** [comment]
The hosts file contains only the mappings of IP addresses to host names and not IP addresses to IP addresses.
 
The following command creates an outbound rule to block all traffic from the local computer to a IP address like "2.22.61.43"

netsh advfirewall firewall add rule name="Block MS IP Address 2.22.61.43" dir=out protocol=any remoteip="2.22.61.43" profile=any action=block

Test if it's working
> ping 2.22.61.43
> General error.

**Comment by lallousx86** [comment]
So, to implement this is basically a matter of going over all the host names in hosts.txt, resolve names to ip addresses and run the netsh command.

**Comment by HristoKolev** [comment]
Something like that. The thing is that when I wrote about hosts.txt having ip addresses I was talking about the addresses that the release version put in my hosts file. Apparently someone removed them after that along with duplicated hosts names. So, here are the addresses that where added by the release version: 

65.55.108.23
65.39.117.230
23.218.212.69
134.170.30.202
137.116.81.24
204.79.197.200

**Comment by W4RH4WK** [comment]
I now create a new Firewall rule blocking outbound traffic to the IPs. Domains are still redirected to `0.0.0.0` via the hosts file. Seems to work (for now).

**Comment by lallousx86** [comment]
Ok, I implemented it: https://github.com/10se1ucgo/DisableWinTracking/pull/29

**Comment by x-a-n-a-x** [comment]
Hi all.

Windows 10 is getting scarier each day.

https://www.microsoft.com/en-us/servicesagreement
Check in section *Updates to the Services or Software, and Changes to These Terms*.

To sum up: they reserve the right to scan your computer and send you patches and updates for pirated games or softwares..

This is why this tool (DisableWinTracking) is really needed to help users protect their lives. 
Thanks.

**Comment by stockmaster** [comment]
@x-a-n-a-x you miss reading, those terms only apply for Microsoft Services. Which would apply to any microsoft games i guess. Not ALL games or software. google it up, lots of in depth comments on it.

**Comment by Red5d** [comment]
@stockmaster , It's a slippery slope though. This could potentially be used in the future as an excuse for them to do more scanning and modification of things on your computer beyond just MS software/services.

**Comment by 10se1ucgo** [comment]
I'm working on it

**Comment by NetworkPro** [comment]
please do not use 0.0.0.0 and 127.0.0.1 to block with hosts file as these are wrongfully representing all network interfaces and localhost in some programs that resolve them like this

use 127.0.0.0 :)

**Comment by 10se1ucgo** [comment]
That makes absolutely no sense. Pretty much everywhere I've looked 0.0.0.0 was suggested. Unless you give me a good reason, my answer is no.

**Comment by NetworkPro** [comment]
Sorry.

Please do not use in hosts file blocking by 0.0.0.0 or 127.0.0.1.

There are apps that try to resolve these - 0.0.0.0 as "all IPv4 interfaces" and 127.0.0.1 as "the local host". Such an app is Process Explorer among others. The blocked hosts start appearing in the app gui where 0.0.0.0 and 127.0.0.1 are used. This interferes with the functionality and usability of such apps.

Please use 127.0.0.0 instead which works perfectly for blocking.

The error message when an app tries to send to 127.0.0.0 is "general failure" which is the same "no route to host" or "can't send packet" basically. (I'm not a developer).

I have tested this and it works.

Thank you.

**Comment by 10se1ucgo** [comment]
@NetworkPro done.

**Comment by 10se1ucgo** [comment]
IP blocking now implemented, v2.2 will be up to download shortly.

**Comment by lallousx86** [comment]
Good work.
