### ISSUE TITLE
Low Prio: App is not DPI aware?

### ISSUE THREAD

**Issue by PeterCodar** [10se1ucgo/DisableWinTracking#288]
* Windows Edition (Home/Pro/Enterprise): Pro
* Architecture (32bit/64bit): 64bit
* Options used: none
* Screenfont-Size: 125%

Low priority Issue:
This nice and useful app is not DPI aware and looks ugly on 125% font-size.
Example screen: 
http://fs5.directupload.net/images/170218/6f5yor3r.png

**Comment by Choppra** [comment]
Turn off windows scaling.. might help

**Comment by Didey** [comment]
Since this was written in the most convoluted UI library in existence, this will not be fixed unless 10se1ucgo is called down by the Gods to do so, unless you want to take a crack at it.
