### ISSUE TITLE
Offenders

### ISSUE THREAD

**Issue by harvestry-of-ghosts** [10se1ucgo/DisableWinTracking#3]
I've noticed traffic to MS domains from all of the following. If not already included maybe you can add them to be blocked in some manner:

taskhostw.exe
CompatTelRunner.exe
SearchUI.exe
sihclient.exe
wermgr.exe
wsqmcons.exe

Also, does your app disable/delete all three of the following?

Diagnostics Tracking Service
Geolocation Service
Windows Error Reporting Service

**Comment by 10se1ucgo** [comment]
It only disables/deletes Diagnostics Tracking Service.
The others I'd prefer not to touch, the Error Reporting Service especially
