### ISSUE TITLE
virus + not work

### ISSUE THREAD

**Issue by mat41997** [10se1ucgo/DisableWinTracking#309]
virus
https://www.virustotal.com/pl/file/01d06c18c9a9496801f18a625423502c9572e4e0dd450d350da8eab8347f086a/analysis/1492111109/

not work on win 10 pro x64

![2017-04-13 21_21_29-fatal error](https://cloud.githubusercontent.com/assets/5884000/25020574/392a5914-208f-11e7-8be9-7a66894afc5f.png)

**Comment by Ruined1** [comment]
There is not virus in the source code. I just looked through the main code and both required files source to make sure. Will have to look into this error

**Comment by Ruined1** [comment]
Works just fine for me, using the latest DisableWinTracking on a Windows 10 Pro x64 install that has never had DisableWinTracking run on it before (other that the errors in the log which have already been reported in another issue).
![Working as Expected](http://i.imgur.com/13hxpPE.png)

**Comment by mat41997** [comment]
ok. works now, thx
