### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by rufuswilson** [10se1ucgo/DisableWinTracking#311]
Hi,

Would it be possible to have a new release uploaded? The last one dates back from last year.

Feel free to delete/close this issue if you don't agree.

Thanks,
Rufus

**Comment by Ruined1** [comment]
I definitely agree it's time for a new release. I will try to upload one this week.

**Comment by Ruined1** [comment]
@rufuswilson New release is published. Just thought you might like to know.

**Comment by rufuswilson** [comment]
@ruined1 Thanks!

Would you happen to know if the changes propagate to all basic users or only the admin?
