### ISSUE TITLE
Error on "AutoLogger-Diagtrack-Listener"

### ISSUE THREAD

**Issue by Maekess** [10se1ucgo/DisableWinTracking#320]
**INFORMATION:**

* Windows Edition (Home/Pro/Enterprise): Pro
* Architecture (32bit/64bit): 64bits
* Options used: I checked all, in "Service Delete" Method and "Privacy Mode"

**LOG:**

12:16:30 INFO: Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)] on win32
12:16:30 INFO: ('Windows', 'PhantomW1', '10', '10.0.14393', 'AMD64', 'Intel64 Family 6 Model 60 Stepping 3, GenuineIntel')
12:16:30 INFO: DisableWinTracking version 3.1.1
12:17:33 INFO: IP Blocker: The IP 134.170.30.202 was successfully blocked.
12:17:33 INFO: IP Blocker: The IP 137.116.81.24 was successfully blocked.
12:17:33 INFO: IP Blocker: The IP 157.56.106.189 was successfully blocked.
12:17:33 INFO: IP Blocker: The IP 2.22.61.43 was successfully blocked.
12:17:33 INFO: IP Blocker: The IP 2.22.61.66 was successfully blocked.
12:17:33 INFO: IP Blocker: The IP 204.79.197.200 was successfully blocked.
12:17:33 INFO: IP Blocker: The IP 23.218.212.69 was successfully blocked.
12:17:33 INFO: IP Blocker: The IP 64.4.54.254 was successfully blocked.
12:17:33 INFO: IP Blocker: The IP 65.39.117.230 was successfully blocked.
12:17:33 INFO: IP Blocker: The IP 65.52.108.33 was successfully blocked.
12:17:33 INFO: IP Blocker: The IP 65.55.108.23 was successfully blocked.
12:17:33 INFO: DiagTrack: Take Ownership of AutoLogger-Diagtrack-Listener.etl was successful
12:17:33 INFO: DiagTrack: Grant Admin Privilege of AutoLogger-Diagtrack-Listener.etl was successful
12:17:33 CRITICAL: Traceback (most recent call last):
  File "dwt.py", line 282, in go
  File "dwt_util.py", line 115, in clear_diagtrack
AttributeError: 'int' object has no attribute 'decode'

**Comment by Ruined1** [comment]
@Maekess Fixed in latest release 3.1.2 - Thank you for your contribution. If you find any other issues, let us know!
