### ISSUE TITLE
Unable to block tracking files

### ISSUE THREAD

**Issue by Freddo98** [10se1ucgo/DisableWinTracking#324]
Console output below. Program was run as administrator on win 10 x64bit machine
++++++++++++++++++++++
08:29:38 INFO: Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)] on win32
08:29:38 INFO: ('Windows', 'XXXXXXX', '10', '10.0.10586', 'AMD64', 'Intel64 Family 6 Model 94 Stepping 3, GenuineIntel')
08:29:38 INFO: DisableWinTracking version 3.1.2
08:30:25 ERROR: Hosts: Failed to modify hosts file
Traceback (most recent call last):
  File "dwt_util.py", line 244, in host_file
IOError: [Errno 13] Permission denied: 'C:\\Windows\\System32/drivers/etc/hosts'
08:30:25 INFO: Done. It's recommended that you reboot as soon as possible for the full effect.
08:30:25 INFO: If you feel something didn't work properly, please press the 'Report an issue' button and follow the directions
++++++++++++++++++++++++++++

Tried, rebooted and tried again without success

98freddo@gmail.com

**Comment by Ruined1** [comment]
Permission denied to the hosts file is almost always due to anti-virus/anti-malware. Please disable any and try running again. Let me know what your results are.

**Comment by Ruined1** [comment]
Unable to reproduce on Windows 10 Pro x64.
