### ISSUE TITLE
URLError is not defined

### ISSUE THREAD

**Issue by ogamespec** [10se1ucgo/DisableWinTracking#325]
20:09:41 INFO: Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)] on win32
20:09:41 INFO: ('Windows', 'CUT', '10', '10.0.14393', 'AMD64', 'Intel64 Family 6 Model 58 Stepping 9, GenuineIntel')
20:09:41 INFO: DisableWinTracking version 3.1.2
20:09:41 CRITICAL: Traceback (most recent call last):
  File "dwt.py", line 486, in <module>
  File "dwt_about.py", line 172, in update_check
NameError: global name 'URLError' is not defined

**Comment by 10se1ucgo** [comment]
@Ruined1 told you xd

**Comment by ogamespec** [comment]
Told what?

**Comment by Ruined1** [comment]
@10se1ucgo well YOU tell ME how to fix it then lol, because according to the documentation, this is legitimate:
```
**exception urllib2.URLError**
The handlers raise this exception (or derived exceptions) when they run into a problem. It is a subclass of IOError.

reason
The reason for this error. It can be a message string or another exception instance (socket.error for remote URLs, OSError for local URLs).
```
https://docs.python.org/2/library/urllib2.html#urllib2.URLError

**Comment by 10se1ucgo** [comment]
change `except URLError` to `except urllib2.URLError`

**Comment by Ruined1** [comment]
Yea, I figured that out lol. I figured the library the exception was defined in would by implied by the `try:`
