### ISSUE TITLE
Can't disable telemetry and adding known domain

### ISSUE THREAD

**Issue by RobertWWong** [10se1ucgo/DisableWinTracking#329]
**INFORMATION:**

* Windows Edition (Home/Pro/Enterprise):
* Architecture (32bit/64bit):
* Options used:

**LOG:**

```python
REPLACE THIS WITH DWT.LOG
```

**Comment by A-Casual-Guy** [comment]
Dude, you forgot to edit the template.
Add in your log and your system info.

**Comment by Ruined1** [comment]
Closing for obvious reasons.
