### ISSUE TITLE
Can prevent Forza Horizons and Gears of War 4 from launching

### ISSUE THREAD

**Issue by TyThompson** [10se1ucgo/DisableWinTracking#330]
Just giving a heads up this program can prevent Forza Horizons and Gears of War 4 from launching. I'm not sure which specific setting does it though.

**Comment by Ruined1** [comment]
It's probably "Block tracking IP Addresses". It's well known that this breaks microsoft services. Along with licensing servers, skype, dr watson, and anything else microsoft driven.
