### ISSUE TITLE
Fail

### ISSUE THREAD

**Issue by joeparkerz** [10se1ucgo/DisableWinTracking#331]
04:04:32 INFO: Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)] on win32
04:04:32 INFO: ('Windows', 'DESKTOP-919LHMH', '10', '10.0.14393', 'AMD64', 'Intel64 Family 6 Model 15 Stepping 11, GenuineIntel')
04:04:32 INFO: DisableWinTracking version 3.1.2
04:04:34 CRITICAL: Traceback (most recent call last):
  File "dwt.py", line 486, in <module>
  File "dwt_about.py", line 172, in update_check
NameError: global name 'URLError' is not defined

**Comment by sjug** [comment]
Getting the same issue

**Comment by Ruined1** [comment]
This happens when you don't have an internet connection (or dwt is denied from using it) because the error checking was broken. 3.1.3 no longer has this issue.
