### ISSUE TITLE
65.52.108.33 is also a Microsoft licensing server

### ISSUE THREAD

**Issue by mattcarras** [10se1ucgo/DisableWinTracking#336]
While trying to figure out why I couldn't install Store Apps, failing after 'Acquiring licensing', and even after using 'Revert' in your tool, I figured out that 65.52.108.33 is the local Akamai CDN served license server for licensing.mp.microsoft.com:
```
>nslookup licensing.mp.microsoft.com
Server:  resolver1.opendns.com
Address:  208.67.222.222

Non-authoritative answer:
Name:    bn2.licensing.md.mp.microsoft.com.akadns.net
Address:  65.52.108.33
Aliases:  licensing.mp.microsoft.com
          licensing.md.mp.microsoft.com.akadns.net
          licensing-useast.md.mp.microsoft.com.akadns.net
```
Thus if your DNS gives back bn2.licensing.md.mp.microsoft.com.akadns.net for licensing.mp.microsoft.com you can't install any apps from the Store. Note OpenDNS's result is the same as from my ISP's DNS server, though Google DNS gives a different result.

I suggest it be removed from the app or added to 'Even more tracking IP domains'.

Just wanted everyone to know -- it's an otherwise useful little tool.

**Comment by Ruined1** [comment]
This is not a domain. It is, in fact, an IP address, and therefor a part of the tracking IP address option. We won't be changing this, though I truly appreciate your well-constructed feedback. It's known that the options in this tool can break Microsoft services, such as this, Skype, Dr Watson, and other things.

Thank you again!
