### ISSUE TITLE
Unable to remove OneDrive

### ISSUE THREAD

**Issue by Huntinho** [10se1ucgo/DisableWinTracking#345]
**INFORMATION:**

* Windows Edition (Home/Pro/Enterprise): Pro
* Architecture (32bit/64bit): 64bit
* Options used:

-Remove OneDrive as part of Batch
-Remove OneDrive in isolation
- above attempted with both service methods

**LOG:**

14:29:37 INFO: Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)] on win32
14:29:37 INFO: ('Windows', 'GizzleSurface', '10', '10.0.14393', 'AMD64', 'Intel64 Family 6 Model 69 Stepping 1, GenuineIntel')
14:29:37 INFO: DisableWinTracking version 3.1.2
14:29:45 INFO: Registry: Successfully modified ListPin key.
14:29:45 INFO: Registry: Successfully modified FileSync key.
14:29:45 INFO: OneDrive: unable to uninstall
14:29:45 INFO: Done. It's recommended that you reboot as soon as possible for the full effect.
14:29:45 INFO: If you feel something didn't work properly, please press the 'Report an issue' button and follow the directions
```

**Comment by Ruined1** [comment]
Please try the [latest release](https://github.com/10se1ucgo/DisableWinTracking/releases/latest) and the issue should be resolved. If you still need help, please create a new issue.
