### ISSUE TITLE
Onedrive Failed to uninstall

### ISSUE THREAD

**Issue by nickisghosty** [10se1ucgo/DisableWinTracking#349]
**INFORMATION:**

* Windows Edition (Home/Pro/Enterprise):
* Architecture (32bit/64bit):
* Options used:

**LOG:**

```python
REPLACE THIS WITH DWT.LOG
```

**Comment by pkorzh** [comment]
i have the same issue

**Comment by nickisghosty** [comment]
No worries, was just seeing if youre aware, thanks for the script anyhow

**Comment by Ruined1** [comment]
You can get the "unable to uninstall" message if OneDrive has already been uninstalled. Show me where OneDrive has not be uninstalled from this system.

**Comment by Ruined1** [comment]
Please try the [latest release](https://github.com/10se1ucgo/DisableWinTracking/releases/latest) and the issue should be resolved. If you still need help, please create a new issue.
