### ISSUE TITLE
unable to uninstall onedrive

### ISSUE THREAD

**Issue by 77Israel** [10se1ucgo/DisableWinTracking#351]
**INFORMATION:**

* Windows Edition (Home/Pro/Enterprise):
* Architecture (32bit/64bit):
* Options used:

**LOG:**

```python
REPLACE THIS WITH DWT.LOG
```

**Comment by Ruined1** [comment]
You can get the "unable to uninstall" message if OneDrive has already been uninstalled. Show me where OneDrive has not be uninstalled from this system.

**Comment by Ruined1** [comment]
Please try the [latest release](https://github.com/10se1ucgo/DisableWinTracking/releases/latest) and the issue should be resolved. If you still need help, please create a new issue.
