### ISSUE TITLE
OneDrive: unable to uninstall

### ISSUE THREAD

**Issue by dimao** [10se1ucgo/DisableWinTracking#356]
**INFORMATION:**

* Windows Edition (Pro):
* Architecture (64bit):
* Options used: 

17:18:03 INFO: Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)] on win32
17:18:03 INFO: ('Windows', 'dimao', '10', '10.0.15063', 'AMD64', 'Intel64 Family 6 Model 42 Stepping 7, GenuineIntel')
17:18:03 INFO: DisableWinTracking version 3.1.2
17:18:28 INFO: IP Blocker: The IP 134.170.30.202 was successfully blocked.
17:18:28 INFO: IP Blocker: The IP 137.116.81.24 was successfully blocked.
17:18:28 INFO: IP Blocker: The IP 157.56.106.189 was successfully blocked.
17:18:28 INFO: IP Blocker: The IP 2.22.61.43 was successfully blocked.
17:18:28 INFO: IP Blocker: The IP 2.22.61.66 was successfully blocked.
17:18:29 INFO: IP Blocker: The IP 204.79.197.200 was successfully blocked.
17:18:29 INFO: IP Blocker: The IP 23.218.212.69 was successfully blocked.
17:18:29 INFO: IP Blocker: The IP 64.4.54.254 was successfully blocked.
17:18:29 INFO: IP Blocker: The IP 65.39.117.230 was successfully blocked.
17:18:29 INFO: IP Blocker: The IP 65.52.108.33 was successfully blocked.
17:18:29 INFO: IP Blocker: The IP 65.55.108.23 was successfully blocked.
17:18:29 INFO: DiagTrack: Take Ownership of AutoLogger-Diagtrack-Listener.etl was successful
17:18:29 ERROR: 1
None
17:18:29 INFO: DiagTrack: Grant Admin Privilege of AutoLogger-Diagtrack-Listener.etl was successful
17:18:29 ERROR: 2
None
17:18:29 INFO: DiagTrack: Cleared AutoLogger-Diagtrack-Listener.etl
17:18:29 INFO: DiagTrack: Deny System Privilege of AutoLogger-Diagtrack-Listener.etl was successful
17:18:29 INFO: DiagTrack: Successfully cleared and locked DiagTrack log.
17:18:30 INFO: Services: Succesfully removed service 'dmwappushsvc'
17:18:30 INFO: Services: Succesfully removed service 'DiagTrack'
17:18:30 INFO: Registry: Successfully modified dmwappushsvc key.
17:18:30 INFO: Registry: Successfully modified DiagTrack key.
17:18:30 INFO: Registry: Successfully modified AllowTelemetry key.
17:18:30 INFO: Registry: Successfully modified WifiSense Open-ness key.
17:18:30 INFO: Registry: Successfully modified WifiSense Credential Share key.
17:18:30 INFO: Registry: Successfully modified ListPin key.
17:18:30 INFO: Registry: Successfully modified FileSync key.
17:18:30 INFO: OneDrive: unable to uninstall
17:18:30 INFO: Done. It's recommended that you reboot as soon as possible for the full effect.
17:18:30 INFO: If you feel something didn't work properly, please press the 'Report an issue' button and follow the directions

**Comment by Ruined1** [comment]
You can get the "unable to uninstall" message if OneDrive has already been uninstalled. Show me where OneDrive has not be uninstalled from this system.

**Comment by Ruined1** [comment]
Please try the [latest release](https://github.com/10se1ucgo/DisableWinTracking/releases/latest) and the issue should be resolved. If you still need help, please create a new issue.
