### ISSUE TITLE
Crappy SW still installing

### ISSUE THREAD

**Issue by Kubikx** [10se1ucgo/DisableWinTracking#360]
Few days ago I reinstall the PC (formatted all drives) and I can not get rid of some apps that install with windows automatically.
I uninstall it run the DisableWinTracking and reboot the PC. 
Wait 10 minutes.
Opened start and that crap is there again.
Crap/Apps:

1. March of Empires: War of Lords
2. Candy Crush soda Saga
3. Minecraft for Windows 10
4. Bubble witch 3 Saga

I already try to disable it in settings:
Settings > Personalization > Start > Occasionally show suggestions in Start **Off**
Two registry keys:
HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\CloudContent\DisableWindowsConsumerFeatures = 1
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\WindowsStore\WindowsUpdate\AutoDownload = 2
And policy setting:
[Steps I followed](url=https://winaero.com/blog/stop-windows-10-anniversary-update-from-installing-candy-crush-and-other-unwanted-apps/)
Nothing of it work.
I hope you planning new version that will prevent that Microsoft´s crap from installing.
Disabling windows defender will be welcome too.

**INFORMATION:**

* Windows 10 Pro:
* Architecture 64bit:
* Options used:
  - Services
  - Clear
  - DiagTrack log
  - Telemetry
  - Block tracking domains
  - Block tracking IP addresses
  - WifiSense

- Modes:
  - Delete
  - Privacy

**LOG:**

```python
17:17:45 INFO: Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)] on win32
17:17:45 INFO: ('Windows', 'DESKTOP-TSO5512', '10', '10.0.15063', 'AMD64', 'Intel64 Family 6 Model 63 Stepping 2, GenuineIntel')
17:17:45 INFO: DisableWinTracking version 3.1.2
17:21:01 INFO: IP Blocker: The IP 134.170.30.202 was successfully blocked.
17:21:01 INFO: IP Blocker: The IP 137.116.81.24 was successfully blocked.
17:21:02 INFO: IP Blocker: The IP 157.56.106.189 was successfully blocked.
17:21:02 INFO: IP Blocker: The IP 2.22.61.43 was successfully blocked.
17:21:02 INFO: IP Blocker: The IP 2.22.61.66 was successfully blocked.
17:21:02 INFO: IP Blocker: The IP 204.79.197.200 was successfully blocked.
17:21:02 INFO: IP Blocker: The IP 23.218.212.69 was successfully blocked.
17:21:02 INFO: IP Blocker: The IP 64.4.54.254 was successfully blocked.
17:21:02 INFO: IP Blocker: The IP 65.39.117.230 was successfully blocked.
17:21:02 INFO: IP Blocker: The IP 65.52.108.33 was successfully blocked.
17:21:02 INFO: IP Blocker: The IP 65.55.108.23 was successfully blocked.
17:21:02 INFO: DiagTrack: Take Ownership of AutoLogger-Diagtrack-Listener.etl was successful
17:21:02 INFO: DiagTrack: Grant Admin Privilege of AutoLogger-Diagtrack-Listener.etl was successful
17:21:02 INFO: DiagTrack: Cleared AutoLogger-Diagtrack-Listener.etl
17:21:02 INFO: DiagTrack: Deny System Privilege of AutoLogger-Diagtrack-Listener.etl was successful
17:21:02 INFO: DiagTrack: Successfully cleared and locked DiagTrack log.
17:21:02 INFO: Registry: Successfully modified dmwappushsvc key.
17:21:02 INFO: Registry: Successfully modified DiagTrack key.
17:21:02 INFO: Registry: Successfully modified AllowTelemetry key.
17:21:02 INFO: Registry: Successfully modified WifiSense Open-ness key.
17:21:02 INFO: Registry: Successfully modified WifiSense Credential Share key.
17:21:02 INFO: Registry: Successfully modified ListPin key.
17:21:02 INFO: Registry: Successfully modified FileSync key.
17:21:02 INFO: Done. It's recommended that you reboot as soon as possible for the full effect.
17:21:02 INFO: If you feel something didn't work properly, please press the 'Report an issue' button and follow the directions

```

**Comment by Biswa96** [comment]
>  I reinstall the PC (formatted all drives) and I can not get rid of some apps that install with windows automatically.

How did games install automatically after a clean Windows 10 install? Did you connect Windows with internet automatically after that clean install? If you get the `app_name` from `Get-AppxPackage` command then you can remove it with PowerShell command: `Get-AppxPackage *<app_name>* | Remove-AppxPackage`

You may remove all the metro apps including Calculator, Store, Calendar, Notes etc. with the following command::
```

PowerShell "Get-AppxPackage -AllUsers | Remove-AppxPackage"
PowerShell "Get-AppXProvisionedPackage -online | Remove-AppxProvisionedPackage -online"
```

**Comment by Kubikx** [comment]
> How did games install automatically after a clean Windows 10 install? Did you connect Windows with internet automatically after that clean install?
It is not normal on win 10? I think these (or similar named) games install automatically on all win 10 versions if `Settings > Personalization > Start > Occasionally show suggestions in Start` was **On**, and it switched to **On** with every bigger update. But this is(was) the first time when switching it off not help. But until yesterday I was trying to use "Skype preview", that also came pre-installed with win 10, but it not work. It was saying "we have problem with connecting to your Skype account, please try later.", or something like this. I was using "Skype preview" since it came out with one of the first versions of win 10. But yesterday I ran out of patience with the the error message, I uninstall the "Skype preview" and install the "old" desktop version. The "old" Skype have no problem connecting to my account, and what is weirder the crap apps not installed again in more than 12 hours.

So I guess the automatic installation was related to "Skype preview". You should add checkbox "Uninstall Skype preview", maybe it help someone 😃

**Comment by Kubikx** [comment]
no the PowerShell commands not work too. 😭

**Comment by Kubikx** [comment]
![image](https://user-images.githubusercontent.com/5793444/31052665-a49b0eb4-a68b-11e7-9a36-e5115ebc7e4d.png)
I have installed:
- Google drive
- Google chrome
- Blizzard App
- Blockstorm (STEAM)
- Divinity: Original Sin 2 (GOG)
- ImDisk
- Java
- Medieval Engineers (STEAM)
- MS Visual studio
- MSI Afterburner (+RivaTuner)
- Notepad++
- Nvidia GeForce Experience
- Skype ("old" Desktop version)
- Steam
- Unity
- WinRAR

That 4 crap apps are not even listed there. Any idea how to remove them from Start PERMANENTLY?

**Comment by Ruined1** [comment]
@Kubikx none of the features we ever implemented were designed to do what you're asking. I don't believe these apps are actually installed on the machine, but "links" or "shortcuts" to them on the app store. I simply right click and remove everything in the start menu that I don't need.
