### ISSUE TITLE
OneDrive issue

### ISSUE THREAD

**Issue by GibrielSpiteri** [10se1ucgo/DisableWinTracking#363]
**INFORMATION:**

OneDrive was unable to uninstall

* Windows Edition (Home/Pro/Enterprise):
* Architecture (32bit/64bit):
* Options used:

**LOG:**

```python
REPLACE THIS WITH DWT.LOG
```
10:25:50 INFO: Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)] on win32
10:25:50 INFO: ('Windows', 'Gib-PC', '10', '10.0.15063', 'AMD64', 'Intel64 Family 6 Model 58 Stepping 9, GenuineIntel')
10:25:50 INFO: DisableWinTracking version 3.1.2
10:25:55 INFO: Registry: Successfully modified ListPin key.
10:25:55 INFO: Registry: Successfully modified FileSync key.
10:25:55 INFO: OneDrive: unable to uninstall
10:25:55 INFO: Done. It's recommended that you reboot as soon as possible for the full effect.
10:25:55 INFO: If you feel something didn't work properly, please press the 'Report an issue' button and follow the directions

**Comment by Ruined1** [comment]
You can get the "unable to uninstall" message if OneDrive has already been uninstalled. Show me where OneDrive has not be uninstalled from this system.

**Comment by Ruined1** [comment]
Please try the [latest release](https://github.com/10se1ucgo/DisableWinTracking/releases/latest) and the issue should be resolved. If you still need help, please create a new issue.
