### ISSUE TITLE
MS Compatibility Telemetry continues to be restored after IPL

### ISSUE THREAD

**Issue by billsmart** [10se1ucgo/DisableWinTracking#366]
It just keeps coming back and hogging all my disc at startup.

[dwt.log](https://github.com/10se1ucgo/DisableWinTracking/files/1453228/dwt.log)

What's the downside of deleting it?

**Comment by Ruined1** [comment]
I couldn't answer that question, I think you'd be better off googling the repercussions of deleting that.
