### ISSUE TITLE
Add non-admin mode

### ISSUE THREAD

**Issue by phly95** [10se1ucgo/DisableWinTracking#367]
**INFORMATION:**

* Windows Edition (Home/Pro/Enterprise): Enterprise
* Architecture (32bit/64bit): 64bit
* Options used:

**LOG:**

```python
REPLACE THIS WITH DWT.LOG
```

Many of us use organizational computers which do not have to access to admin rights. Currently, Shutup10 is able to apply as many settings as possible without admin, so when I'm at the university, I have to use closed source software to disable tracking.

**Comment by Ruined1** [comment]
You shouldn't be running this program without Administrator permission in the first place. If you don't have admin rights, you shouldn't be playing around with these settings on these systems. If someone else wants to invest the time to issue a pull request that resolves this, I might consider implementing it, but as it is that feature won't be added.
