### ISSUE TITLE
Blocking Akamai - false positives

### ISSUE THREAD

**Issue by simplypeachy** [10se1ucgo/DisableWinTracking#37]
One needs to exercise extreme care when blocking generic host names at Akamai. I have logs of fetching from a248.e.akamai.net for web content for the web site http://www.johnlewis.com/ , a UK retailer. It looks like Amazon, eBay and IMDB may also use it to serve content. I would be surprised if all of the other a[0-9].*akamai host names were not used elsewhere as well; the host names probably point at shared CDNs.

I would expect blocking these to cause subtle but frustrating problems such as thumbnail images, CSS and Javascript not working on seemingly-random web sites.

**Comment by 10se1ucgo** [comment]
Yep, this is removed in 2.0.

**Comment by 10se1ucgo** [comment]
2.0 pushed
