### ISSUE TITLE
Why does DisableWinTracking connect to 192.30.253.116 ?

### ISSUE THREAD

**Issue by xan2622** [10se1ucgo/DisableWinTracking#370]
As soon as I launched DisableWinTracking, I noticed that it tried to connect to 192.30.253.116 (to Github).

http://www.iplocationfinder.com/192.30.253.116

Why ?
Does DisableWinTracking spy on users? :-/

**Comment by Ruined1** [comment]
This program does not spy on it's users. The outward connection to this repository is to see if you have the latest version. Nothing more, nothing less.
