### ISSUE TITLE
WinDefend Service Disabled

### ISSUE THREAD

**Issue by muthukumar143** [10se1ucgo/DisableWinTracking#372]
**INFORMATION:**

* Windows Edition (Home/Pro/Enterprise):
* Architecture (32bit/64bit):
* Options used:

**LOG:**

```python
REPLACE THIS WITH DWT.LOG
```
Hi,I am using windows 10.After installing 2018 Cumulative Update(KB4056892) windows defender is disabled.And WinDefend service is also disabled.

In the below image the path to executable is also changed.Help me to solve it.
![screenshot 167](https://user-images.githubusercontent.com/25875778/34706960-9d457412-f530-11e7-851e-b752a4ee8a33.png)

**Comment by Ruined1** [comment]
Windows Defender support is currently disabled in DWT due to windows limitations. Look for resolution in future updates.
