### ISSUE TITLE
what is that abot?

### ISSUE THREAD

**Issue by mohdalyahri** [10se1ucgo/DisableWinTracking#373]
**INFORMATION:**

* Windows Edition (Home/Pro/Enterprise):
* Architecture (32bit/64bit):
* Options used:

**LOG:**

```python
REPLACE THIS WITH DWT.LOG
```

**Comment by Ruined1** [comment]
You provided zero troubleshooting information. Closed.

**Comment by def14nt** [comment]
abot tho
