### ISSUE TITLE
Idea on: I cannot stress this enough, not running the program as an administrator will result in none of the tweaks being applied.

### ISSUE THREAD

**Issue by Dmitrij-Polyanin** [10se1ucgo/DisableWinTracking#378]
But I think there is a way to make exe file to ask elevated privileges. You tel users to make it themself by using mouse right menu, but program can itself ask this privileges.

One way to do this is to use manifest file, i used it when making one program on C#, dont know is there any way to make it using Pyton, hope it is.

Some programs icons has special icons-label to administrator privileges, so there are ways how to make it.

**Comment by Dmitrij-Polyanin** [comment]
Here to read about manifest - https://msdn.microsoft.com/en-us/library/windows/desktop/aa374191(v=vs.85).aspx

look "autoElevate" parameter.

**Comment by Ruined1** [comment]
This didn't used to be possible, but I took another look since you brought it up again. Turns out it's now an easy fix. It will be implemented in version 3.2.1
