### ISSUE TITLE
Windows 10 Pro, Version 10.0.16299 Build 16299 errors

### ISSUE THREAD

**Issue by ttiberio** [10se1ucgo/DisableWinTracking#379]
**INFORMATION:**

* Windows Edition (Home/Pro/Enterprise):
* Microsoft Windows 10 Pro, Version 10.0.16299 Build 16299 (just did an update), x64

all options checked or 'disable' except windows defender which was grayed out.
two major errors

15:15:16 INFO: Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)] on win32
15:15:16 INFO: ('Windows', 'HAMMER', '10', '10.0.16299', 'AMD64', 'Intel64 Family 6 Model 94 Stepping 3, GenuineIntel')
15:15:16 INFO: DisableWinTracking version 3.2.0
15:24:16 INFO: IP Blocker: The IP 134.170.30.202 was successfully blocked.
15:24:16 INFO: IP Blocker: The IP 137.116.81.24 was successfully blocked.
15:24:16 INFO: IP Blocker: The IP 157.56.106.189 was successfully blocked.
15:24:16 INFO: IP Blocker: The IP 2.22.61.43 was successfully blocked.
15:24:16 INFO: IP Blocker: The IP 2.22.61.66 was successfully blocked.
15:24:16 INFO: IP Blocker: The IP 204.79.197.200 was successfully blocked.
15:24:17 INFO: IP Blocker: The IP 23.218.212.69 was successfully blocked.
15:24:17 INFO: IP Blocker: The IP 64.4.54.254 was successfully blocked.
15:24:17 INFO: IP Blocker: The IP 65.39.117.230 was successfully blocked.
15:24:17 INFO: IP Blocker: The IP 65.52.108.33 was successfully blocked.
15:24:17 INFO: IP Blocker: The IP 65.55.108.23 was successfully blocked.
15:24:17 INFO: 1072
15:24:17 ERROR: DiagTrack: Failed Part 1/3
None
15:24:17 CRITICAL: DiagTrack: Error code: 1072 - ('[SC] DeleteService FAILED 1072:\r\n\r\nThe specified service has been marked for deletion.\r\n\r\n', '')
15:24:17 INFO: DiagTrack: dmwappushservice service doesn't exist. This is OK, you likely removed it already.
15:24:17 INFO: DiagTrack: Completed Part 2/3
15:24:17 INFO: DiagTrack: Successfully erased tracking log.
15:24:17 INFO: DiagTrack: Completed Part 3/3
15:24:17 INFO: DiagTrack: Complete. Errors were recorded.
15:24:17 ERROR: Services: Failed to remove service 'DiagTrack'
Traceback (most recent call last):
  File "dwt_util.py", line 166, in delete_service
  File "site-packages\win32\lib\win32serviceutil.py", line 303, in RemoveService
error: (1072, 'DeleteService', 'The specified service has been marked for deletion.')
15:24:17 INFO: Registry: Successfully modified dmwappushsvc key.
15:24:17 INFO: Registry: Successfully modified DiagTrack key.
15:24:17 INFO: Registry: Successfully modified AllowTelemetry key.
15:24:17 INFO: Registry: Successfully modified WifiSense Open-ness key.
15:24:17 INFO: Registry: Successfully modified WifiSense Credential Share key.
15:24:18 INFO: Registry: Successfully modified ListPin key.
15:24:18 INFO: Registry: Successfully modified ListPin64Bit key.
15:24:18 INFO: Registry: Successfully modified FileSync key.
15:24:19 INFO: OneDrive: successfully uninstalled
15:24:19 INFO: Done. It's recommended that you reboot as soon as possible for the full effect.
15:24:19 INFO: If you feel something didn't work properly, please press the 'Report an issue' button and follow the directions

**Comment by Ruined1** [comment]
@ttiberio I think this might not be an actual error, but just an oversight on MY part while handling return codes.
If you can do me a huge favor, on the machine you ran this on, follow a couple steps:

1. Restart your computer entirely (I cannot stress how important this is)

2. Open services
https://i.imgur.com/KGxRVna.png

3. Look and see if the Diagnostics Tracking (DiagTrack) service even exists anymore, or if it's gone.
https://i.imgur.com/VP5WJzS.png

**Comment by ttiberio** [comment]
Unfortunately i've made a ton of changes and i don't think i could reproduce this - my output has changed though. this is what the log looks like now

14:07:39 INFO: Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)] on win32
14:07:39 INFO: ('Windows', 'HAMMER', '10', '10.0.16299', 'AMD64', 'Intel64 Family 6 Model 94 Stepping 3, GenuineIntel')
14:07:39 INFO: DisableWinTracking version 3.2.0
14:08:02 INFO: IP Blocker: The IP 134.170.30.202 was successfully blocked.
14:08:03 INFO: IP Blocker: The IP 137.116.81.24 was successfully blocked.
14:08:03 INFO: IP Blocker: The IP 157.56.106.189 was successfully blocked.
14:08:03 INFO: IP Blocker: The IP 2.22.61.43 was successfully blocked.
14:08:03 INFO: IP Blocker: The IP 2.22.61.66 was successfully blocked.
14:08:03 INFO: IP Blocker: The IP 204.79.197.200 was successfully blocked.
14:08:03 INFO: IP Blocker: The IP 23.218.212.69 was successfully blocked.
14:08:04 INFO: IP Blocker: The IP 64.4.54.254 was successfully blocked.
14:08:04 INFO: IP Blocker: The IP 65.39.117.230 was successfully blocked.
14:08:04 INFO: IP Blocker: The IP 65.52.108.33 was successfully blocked.
14:08:04 INFO: IP Blocker: The IP 65.55.108.23 was successfully blocked.
14:08:04 INFO: DiagTrack: DiagTrack service doesn't exist. This is OK, you likely removed it already.
14:08:04 INFO: DiagTrack: Completed Part 1/3
14:08:04 INFO: DiagTrack: dmwappushservice service doesn't exist. This is OK, you likely removed it already.
14:08:04 INFO: DiagTrack: Completed Part 2/3
14:08:04 INFO: DiagTrack: Successfully erased tracking log.
14:08:04 INFO: DiagTrack: Completed Part 3/3
14:08:04 INFO: DiagTrack: Completed successfully, without errors.
14:08:05 INFO: Registry: Successfully modified dmwappushsvc key.
14:08:05 INFO: Registry: Successfully modified DiagTrack key.
14:08:05 INFO: Registry: Successfully modified AllowTelemetry key.
14:08:05 INFO: Registry: Successfully modified WifiSense Open-ness key.
14:08:05 INFO: Registry: Successfully modified WifiSense Credential Share key.
14:08:05 INFO: Registry: Successfully modified ListPin key.
14:08:05 INFO: Registry: Successfully modified ListPin64Bit key.
14:08:05 INFO: Registry: Successfully modified FileSync key.
14:08:07 INFO: OneDrive: successfully uninstalled
14:08:07 INFO: Done. It's recommended that you reboot as soon as possible for the full effect.
14:08:07 INFO: If you feel something didn't work properly, please press the 'Report an issue' button and follow the directions

**Comment by Ruined1** [comment]
@ttiberio EXCELLENT! That works too! Yea it ran perfectly the first time, I just have bad checking (I didn't know the code 1072 existed for when it's marked for deletion after rebooting the system) So, long story short, it reports perfectly normal operation, as an error.

I will add a catch for that in version 3.2.1. Thank you for contributing!
