### ISSUE TITLE
Что то пошло не так

### ISSUE THREAD

**Issue by DO2TS** [10se1ucgo/DisableWinTracking#381]
[dwt.log](https://github.com/10se1ucgo/DisableWinTracking/files/1681672/dwt.log)
**INFORMATION:**

* Windows Edition (Home/Pro/Enterprise):
* Architecture (32bit/64bit):
* Options used:

**LOG:**

```python
REPLACE THIS WITH DWT.LOG
```

**Comment by Ruined1** [comment]
Вы должны скопировать и вставить журнал. Я не могу исправить ошибку, если я не знаю, какую ошибку.

**Comment by Ruined1** [comment]
Это нормально, вы можете игнорировать это.
