### ISSUE TITLE
Error Found

### ISSUE THREAD

**Issue by sheikmeeran** [10se1ucgo/DisableWinTracking#385]
**INFORMATION:**

* Windows Edition (Home/Pro/Enterprise):
* Architecture (32bit/64bit):
* Options used:

**LOG:**

```python
 ERROR: Services: Failed to remove service 'DiagTrack'
Traceback (most recent call last):
  File "dwt_util.py", line 168, in delete_service
  File "site-packages\win32\lib\win32serviceutil.py", line 303, in RemoveService
error: (1072, 'DeleteService', 'The specified service has been marked for deletion.')
```

**Comment by Ruined1** [comment]
"The specified service has been marked for deletion" means it worked just find. Don't know why this shows up as an error, but it was successful.
