### ISSUE TITLE
Error while working

### ISSUE THREAD

**Issue by kav4ik** [10se1ucgo/DisableWinTracking#387]
**INFORMATION:**

* Windows Edition (Home/Pro/Enterprise):
* Architecture (32bit/64bit):
* Options used:

**LOG:**
[dwt.log](https://github.com/10se1ucgo/DisableWinTracking/files/1830499/dwt.log)

```python
REPLACE THIS WITH DWT.LOG
```

**Comment by Ruined1** [comment]
Can't help you without a log pasted into the issue tracker. I'm not downloading files from an unknown source and opening them.
