### ISSUE TITLE
Seems to be blocking Windows updates on Education edition

### ISSUE THREAD

**Issue by russkel** [10se1ucgo/DisableWinTracking#388]
**INFORMATION:**

* Windows Edition (Home/Pro/Enterprise): Education
* Architecture (32bit/64bit): 64bit
* Options used: All

I was surprised about the lack of updates to my Windows partition on my computer, having not used it for a couple of weeks. I removed all the tracking IPs and domains using DWT and then did a refresh on windows update, sure enough the Cumulative Updates started coming down.

**Comment by Ruined1** [comment]
This is a very real possibility. Remember, microsoft owns those servers and can do whatever they like with them. So what may have just been a tracking/telemetry server at one point could also be hosting education edition updates too now. There is no good way to do this. If you still want to use it, I recommend cherrypicking groups of ips (maybe 5 at a time) until you find which group lets your update through, and then figuring out which of those 5 are the one you want to remove with the next update that comes out.

Nothing we can do with this one, sorry.
