### ISSUE TITLE
Traceback at launch

### ISSUE THREAD

**Issue by mben42** [10se1ucgo/DisableWinTracking#390]
**INFORMATION:**

* Windows Edition (Home/Pro/Enterprise): Education
* Architecture (32bit/64bit): 64
* Options used: none

Traceback (most recent call last):
  File "dwt.py", line 492, in <module>
  File "dwt.py", line 92, in __init__
  File "dwt.py", line 467, in check_elevated
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe9 in position 4: ordinal not in range(128)
Failed to execute script dwt

**Comment by Ruined1** [comment]
You're running windows in another language. Move DisableWinTracking.exe to C:\DisableWinTracking.exe and run as administrator again.
