### ISSUE TITLE
Could not access my host files and delete the DNS's with 0.0.0.0

### ISSUE THREAD

**Issue by Haim1989** [10se1ucgo/DisableWinTracking#391]
**INFORMATION:**

* Windows Edition (Home/Pro/Enterprise):
* Architecture (32bit/64bit):
* Options used:

**LOG:**

```python
REPLACE THIS WITH DWT.LOG
```

**Comment by Ruined1** [comment]
host files have to be accessed using a notepad that is running as an administrator, otherwise, you cannot modify them manually.
