### ISSUE TITLE
host file

### ISSUE THREAD

**Issue by Maverick119** [10se1ucgo/DisableWinTracking#392]
**INFORMATION:**

* Windows Edition (Home/Pro/Enterprise):
* Architecture (32bit/64bit):
* Options used:

**LOG:**

```python
REPLACE THIS WITH DWT.LOG
```

**Comment by Maverick119** [comment]
I have just recieved this error. Is there a possible way around it ?

**Comment by Maverick119** [comment]
File "dwt_util.py", line 305, in host_file
IOError: [Errno 13] Permission denied: 'C:\\WINDOWS\\System32/drivers/etc/hosts'

**Comment by TZocker** [comment]
The backspace look strange 'C:\WINDOWS\System32/drivers/etc/hosts'

also an Antivirus Programm can protect the host file ....

greetz

**Comment by Maverick119** [comment]
Ok next time I shall disable the AV before I run it. However cleaner often
reports up to 500 tracking files deleted even after I have run it.

**Comment by Maverick119** [comment]
That’s Ccleaner by the way

**Comment by Ruined1** [comment]
`02:53:39 INFO: Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)] on win32
02:53:39 INFO: ('Windows', 'DESKTOP-9G26HTS', '10', '10.0.17134', 'AMD64', 'AMD64 Family 21 Model 19 Stepping 1, AuthenticAMD')
02:53:39 INFO: DisableWinTracking version 3.2.1
02:53:58 INFO: Done. It's recommended that you reboot as soon as possible for the full effect.`

Unable to reproduce, works fine for me, you likely have something blocking it, like an antivirus.
