### ISSUE TITLE
IOError: [Errno 13] Permission denied: 'C:\\WINDOWS\

### ISSUE THREAD

**Issue by Georges-Ivanoff** [10se1ucgo/DisableWinTracking#394]
**INFORMATION:**

* Windows Edition (Home/Pro/Enterprise):
* Architecture (32bit/64bit):
* Options used:

**LOG:**

```python
REPLACE THIS WITH DWT.LOG
```

**Comment by Ruined1** [comment]
Can't tell you anything without a log.
