### ISSUE TITLE
UNABLE TO START the EXE

### ISSUE THREAD

**Issue by GamingPilot2** [10se1ucgo/DisableWinTracking#397]
**INFORMATION:**

* Windows Edition (Home/Pro/Enterprise): home
* Architecture (32bit/64bit): 64

**Comment by GamingPilot2** [comment]
here the image 
![image](https://user-images.githubusercontent.com/14299286/42968477-a1a01440-8ba3-11e8-9135-8405997d2044.png)

**Comment by majed17** [comment]
I love your software and am very thankful that I would love to donate! is it possible?

**Comment by Ruined1** [comment]
@majed17 no it is not possible to donate, but all developers appreciate your kind words

@GamingPilot2 You're running it on a foreign language. Move DWT to C:\DisableWinTracking.exe and try to run it as administrator again.

**Comment by majed17** [comment]
well it is a pity to read that. others have subscribed to buy me a coffee to accept donations :)
