### ISSUE TITLE
ASP.NET IIS Service Issue?

### ISSUE THREAD

**Issue by RailsCod3rFuture** [10se1ucgo/DisableWinTracking#4]
I used your tool earlier today, and I was wondering if it had anything to do with Visual Studio not being able to connect to IIS services. Let me know if there are IIS settings related to your strategy being disabled. Thanks.

I'm getting this message "Unable to connect to the configured development Web Server"

**Comment by 10se1ucgo** [comment]
I don't believe there is, but what you can try is to go to

    C:\WINDOWS\System32\drivers\etc

And open the hosts file and clear all of the entries.

**Comment by 10se1ucgo** [comment]
No response? Closing.
