### ISSUE TITLE
certain parameters are managed by your company

### ISSUE THREAD

**Issue by th0m1** [10se1ucgo/DisableWinTracking#40]
i ran the program and i have this on my privacy notification : 
certain parameters are managed by your company 
how i can resoleve it ? 

when i go to confidentiality > Comments and Diagnostics  > diagnostic data and use i can't set it to "complete (recommanded)" because it don't save my changes 
what i should modify in the registry to set it back ?

**Comment by th0m1** [comment]
i solved the prolem
To make the change in the Group Policy, do the following:

    Tap on the Windows-key, type gpedit.msc and hit enter.
    Navigate to Computer Configuration > Administrative Templates > Windows Components > Data Collection (It may be listed as Data Collection and Preview Builds).
    Set Allow Telemetry to Off if you are using an Enterprise account, to Basic if you are not.

To make the change using the Windows Registry, do the following:

    Tap on the Windows-key, type regedit and hit enter.
    Confirm the UAC prompt if it comes up.
    Navigate to HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\DataCollection.
    Set the value of AllowTelemetry to 0 if you are on Enterprise, to 1 if you are not.

**Comment by SuperMasterBlasterLaser** [comment]
Is it possible to include your solution to this application?

**Comment by 10se1ucgo** [comment]
It's already included. Press the "Revert" button in version 2.1 and above.
