### ISSUE TITLE
unable to run DisableWinTracking.exe

### ISSUE THREAD

**Issue by osobucodonosor** [10se1ucgo/DisableWinTracking#400]
I have not been able to run the exe file and install the software. I did it as administrator after following al the instructions, including those referred to windows defender. Files are in a folder out fo defender´s scope.

**Comment by Ruined1** [comment]
Related to a windows update. Click your Windows 10 Start menu > Settings > Privacy App Permissions - Microphone > Hit "Change" button, make sure it's turned on > Below change button is another slider, make sure it is also turned on. Has nothing to do with DWT.

**Comment by Ruined1** [comment]
Unable to reproduce, no one else is reporting this issue, worked fine for me in Windows 10 Version 1803 (OS Build 17134.285)
