### ISSUE TITLE
networtk Scanner

### ISSUE THREAD

**Issue by avidflyer17** [10se1ucgo/DisableWinTracking#411]
Hello,
Since I use this tool, my network dcan isn't detect anymore ...

**INFORMATION:**

* Windows Edition (Home/Pro/Enterprise):
* Architecture (32bit/64bit):
* Options used:

**LOG:**

```python
REPLACE THIS WITH DWT.LOG
```

**Comment by Ruined1** [comment]
Please define your "network scan". I have no clue what you're referring to.

**Comment by Meepss** [comment]
Pretty sure he is talking about not being able to connect to wifi

**Comment by Ruined1** [comment]
As there is no response from the person who opened the ticket for 2 weeks, and DWT doesn't affect Wifi capabilities, I'm going to mark this as invalid. Please open a new ticket with more detail if the issue persists.
