### ISSUE TITLE
error on launch, no arguments usable

### ISSUE THREAD

**Issue by dominix** [10se1ucgo/DisableWinTracking#415]
**INFORMATION:**

* Windows Edition (Home/Pro/Enterprise): Home (update 1809)
* Architecture (32bit/64bit):64
* Options used: none usable

**LOG:**

```python
REPLACE THIS WITH DWT.LOG  => there is no log
```
DisableWinTracking.exe
Traceback (most recent call last):
  File "dwt.py", line 494, in <module>
  File "dwt.py", line 96, in __init__
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe9 in position 10: invalid continuation byte
[11548] Failed to execute script dwt

**Comment by Ruined1** [comment]
@dominix looks to me like you're using a language other than English for you windows install. Is that correct? How did you try to run the program? From the command line using the -silent argument or just running it normally as administrator?

Try placing DisableWinTracking.exe directly onto the primary hard drive (usually C:\) and run it as administrator from there.

**Comment by GoldRamAncestor** [comment]
Hi, guys. 
I also have problem with launch of new 3.2.2 version.
* Windows Edition (Home/Pro/Enterprise): Win 7 SP1 Ent
* Architecture (32bit/64bit): 32 bit
* Options used: none usable

I got error about incompatible Windows architecture, but hadn't any problems with version 3.2.1 on same OS:
This verison of this file is not compatible with the version of Windows you're running. Check your computer's system information to see whether you need an x86 (32-bit) or x64 (64-bit) verion of the program.

**Comment by dominix** [comment]
@Ruined1  I just have downloadded the zip file, unzip it in "Downloads" folder and run DisableWinTracking.exe  as administrator. Error messages came directly with no influence on parameters, same error from explorer or from cmd.
regards.

**Comment by dominix** [comment]
BTW language on the machine is French, on the last windows 10 update (1809).

**Comment by Ruined1** [comment]
> Hi, guys.
> I also have problem with launch of new 3.2.2 version.
> 
> * Windows Edition (Home/Pro/Enterprise): Win 7 SP1 Ent
> * Architecture (32bit/64bit): 32 bit
> * Options used: none usable
> 
> I got error about incompatible Windows architecture, but hadn't any problems with version 3.2.1 on same OS:
> This verison of this file is not compatible with the version of Windows you're running. Check your computer's system information to see whether you need an x86 (32-bit) or x64 (64-bit) verion of the program.
> 
> File was launched from c:\Temp with administrator rights.

This is my fault, I compiled it on 64-bit python like a cabbage. Please creaate a new issue, I will solve that shortly.. Sorry.

**Comment by Ruined1** [comment]
> @Ruined1 I just have downloadded the zip file, unzip it in "Downloads" folder and run DisableWinTracking.exe as administrator. Error messages came directly with no influence on parameters, same error from explorer or from cmd.
> regards.

I'm going to release a new version within the hour. please extract it directly to your main drive and run as administrator. This would usually mean your file path will be C:\DisableWinTracking.exe

**Comment by Ruined1** [comment]
@GoldRamAncestor Try redownloading the release. I recompiled it for 32-bit.

**Comment by Ruined1** [comment]
@dominix Try re-downloading the release and run it directly from your main drive. This would usually mean your file path will be C:\DisableWinTracking.exe

**Comment by GoldRamAncestor** [comment]
@Ruined1, hi.
I redownloaded the release and relaunched exe-file, but now I have another error:

C:\Users\Administrator>c:\Temp\dwt-3.2.2-cp27-win_x86\DisableWinTracking.exe
Traceback (most recent call last):
  File "dwt.py", line 29, in <module>
  File "c:\users\winbox\appdata\local\temp\pip-install-w9ip7k\pyinstaller\PyInst
aller\loader\pyimod03_importers.py", line 395, in load_module
  File "dwt_util.py", line 21, in <module>
ImportError: No module named pywintypes
[228] Failed to execute script dwt

Error is same on the Win7 SP1 Ent x32 RU and W2K12 R2 Std x64 En.

**Comment by Ruined1** [comment]
@GoldRamAncestor Yea, that was patched in code last night, I'll upload the new release momentarily

**Comment by Ruined1** [comment]
@GoldRamAncestor ok, try 3.2.3 from https://github.com/10se1ucgo/DisableWinTracking/releases/tag/3.2.3

**Comment by GoldRamAncestor** [comment]
Hi, Ruined1. Now It's working without erros, thanks. 


От: "Ruined1" <notifications@github.com> 
Кому: "10se1ucgo/DisableWinTracking" <DisableWinTracking@noreply.github.com> 
Копия: "GoldRamAncestor" <nvn@jarvis.tk>, "Mention" <mention@noreply.github.com> 
Отправленные: Воскресенье, 17 Февраль 2019 г 0:30:18 
Тема: Re: [10se1ucgo/DisableWinTracking] error on launch, no arguments usable (#415) 



[ https://github.com/GoldRamAncestor | @GoldRamAncestor ] ok, try 3.2.3 from [ https://github.com/10se1ucgo/DisableWinTracking/releases/tag/3.2.3 | https://github.com/10se1ucgo/DisableWinTracking/releases/tag/3.2.3 ]

**Comment by Ruined1** [comment]
Wonderful, thank you for working with me on this.
