### ISSUE TITLE
Critical error: DiagTrack: Failed Part 3/3

### ISSUE THREAD

**Issue by GoldRamAncestor** [10se1ucgo/DisableWinTracking#417]
Hi, guys.
There are errors with part 3 for diagtrack tasks.
File launching made with admin rights, of course.

**INFORMATION:**

* Windows Edition (Home/Pro/Enterprise): Pro
* Architecture (32bit/64bit): 64 bit
* Options used: none

**LOG:**

```python
12:59:57 INFO: Python 2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:22:17) [MSC v.1500 32 bit (Intel)] on win32
12:59:57 INFO: ('Windows', 'pc', '7', '6.1.7601', 'AMD64', 'Intel64 Family 6 Model 69 Stepping 1, GenuineIntel')
12:59:57 INFO: DisableWinTracking version 3.2.3
...
13:00:24 ERROR: DiagTrack: Failed Part 3/3
None
13:00:24 CRITICAL: DiagTrack: Error code: 1 - ('', '\x8e\xe2\xaa\xa0\xa7\xa0\xad\xae \xa2 \xa4\xae\xe1\xe2\xe3\xaf\xa5.\r\n')
...

On the W2K12 R2 x64 Std error there is little bit another kind of error:
11:43:55 INFO: Python 2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:22:17) [MSC v.1500 32 bit (Intel)] on win32
11:43:56 INFO: ('Windows', 'server', '2012ServerR2', '6.3.9600', 'AMD64', 'Intel64 Family 6 Model 42 Stepping 7, GenuineIntel')
...
11:44:17 ERROR: DiagTrack: Failed Part 3/3
None
11:44:17 CRITICAL: DiagTrack: Error code: 1 - ('', 'Access is denied.\r\n')
...

**Comment by Ruined1** [comment]
> Hi, guys.
> There are errors with part 3 for diagtrack tasks.
> File launching made with admin rights, of course.
> 
> **INFORMATION:**

> 12:59:57 INFO: ('Windows', 'pc', '7', '6.1.7601', 'AMD64', 'Intel64 Family 6 Model 69 Stepping 1, GenuineIntel')

> 11:43:56 INFO: ('Windows', 'server', '2012ServerR2', '6.3.9600', 'AMD64', 'Intel64 Family 6 Model 42 

This is for Windows 10 only, no other version of windows. You're trying to run this on Windows 7 and Windows 2012 Server...
