### ISSUE TITLE
Silent mode does not perform all available options

### ISSUE THREAD

**Issue by ghost** [10se1ucgo/DisableWinTracking#419]
**INFORMATION:**

* Windows Edition: Enterprise
* Architecture: 64
* Options used: silent

Cross-referencing the settings for [silent](https://github.com/10se1ucgo/DisableWinTracking/blob/master/dwt.py#L479) vs [window](https://github.com/10se1ucgo/DisableWinTracking/blob/master/dwt.py#L294) mode, the following are missing in silent mode.

- `dwt_util.ip_block`
- `dwt_util.host_file`
- `dwt_util.dvr`

Also `dwt_util.defender` is present but commented.

It seems like it's impossible for `dwt_util.app_manager` to ever be called, otherwise that would be missing as well.

**Comment by rytakahashi** [comment]
Note this is not necessarily an issue, however misleading since the following is stated in the [readme](https://github.com/10se1ucgo/DisableWinTracking/blob/master/README.md#silent).

> This will perform all available options of the version you're using.

**Comment by Ruined1** [comment]
It likely doesn't include the Xbox DVR option that was recently added, an oversight by the person who added it and an oversight by myself in review, other than that, it would help to know which options you feel aren't being performed.

**Comment by rytakahashi** [comment]
The 3 calls that I think are not being made are in the main post.

Primarily I'm noticing that the host file isn't getting updated when run in silent mode, also from the code it looks like the IP blocking is also not happening, but I haven't verified in any runs.

**Comment by Ruined1** [comment]
I believe there was an original reason why those were left out of the silent run, but I can't remember specifically why. The silent parameter was added so long ago...

**Comment by rytakahashi** [comment]
I ran a quick search for all [issues with "silent"](https://github.com/10se1ucgo/DisableWinTracking/issues?utf8=✓&q=silent) and it seems none of them discuss the host file.

I think whether or not it's added is not as big of an issue as correctly indicating in the readme what is done and what isn't.

Or even better, allow passing parameters for what the user wants to run. But not necessary. I think most people who go to the extent to run something like this will likely be checking all the boxes anyways.
