### ISSUE TITLE
exe Not working on my Windows 10 Pro PT-BR

### ISSUE THREAD

**Issue by fabianod** [10se1ucgo/DisableWinTracking#426]
**INFORMATION:**

* Windows Edition (Home/Pro/Enterprise): Pro 1809
* Architecture (32bit/64bit): 64bits
* Options used: no options used

$ DisableWinTracking.exe
Traceback (most recent call last):
  File "dwt.py", line 501, in <module>
  File "dwt.py", line 94, in __init__
  File "dwt.py", line 476, in check_elevated
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe7 in position 37: ordinal not in range(128)
[13088] Failed to execute script dwt

**Comment by Ruined1** [comment]
Move DisableWinTracking.exe to your root drive (Usually C:\) and run it again as administrator.

This is addressed in the [Readme](https://github.com/10se1ucgo/DisableWinTracking/blob/master/README.md)
