### ISSUE TITLE
Exited with code: -2147219823 - ('', '')

### ISSUE THREAD

**Issue by RazorJin** [10se1ucgo/DisableWinTracking#435]
**INFORMATION:** i cannot uninstal one drive. All the other options worked out for me except for one drive 

* Windows Edition (10 Pro/):
* Architecture (64bit):
* Options used: uninstall one drive 

**LOG:**

20:37:40 INFO: Python 2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:22:17) [MSC v.1500 32 bit (Intel)] on win32
20:37:40 INFO: ('Windows', 'KENNETH-PC', '10', '10.0.17134', 'AMD64', 'Intel64 Family 6 Model 61 Stepping 4, GenuineIntel')
20:37:40 INFO: DisableWinTracking version 3.2.3
20:37:48 INFO: Registry: Successfully modified ListPin key.
20:37:48 INFO: Registry: Successfully modified FileSync key.
20:37:49 INFO: OneDrive: unable to uninstall. Exited with code: -2147219823 - ('', '')
20:37:49 INFO: Done. It's recommended that you reboot as soon as possible for the full effect.
20:37:49 INFO: If you feel something didn't work properly, please press the 'Report an issue' button and follow the directions

**Comment by fbrzoz** [comment]
From what I can see, x86_64 versions of Windows contain the OneDrive setup executable in a different place - namely, at `%SystemRoot%\SysWOW64\OneDriveSetup.exe`. If I understand correctly, this should be as simple as an architecture check - I'll see what I can do about making a PR later.
