### ISSUE TITLE
HOSTS file getting messed up with 2.2

### ISSUE THREAD

**Issue by RowanDDR** [10se1ucgo/DisableWinTracking#44]
When I ran 2.2, it appeared to delete existing lines in my HOSTS file!

Like a lot of people I get my HOSTS file from here: http://winhelp2002.mvps.org/hosts.htm (it blocks loads of adverts etc).

After running your run.exe, all the hundreds of lines from the MVPS HOSTS file are now deleted!

e.g.
> `# [1&1 Internet][AS8560][195.20.243.0 - 195.20.255.255]`
> `0.0.0.0 madclient.uimserv.net`

has now become just this:
> `# [1&1 Internet][AS8560][195.20.243.0 - 195.20.255.255]`

**Comment by 10se1ucgo** [comment]
Unreadable. Provide me a download to your hosts file so I can attempt to recreate this.

**Comment by RowanDDR** [comment]
I'm not just using hosts file to block ads, I'm using it to block programs that call home too. Windows 10 isn't the only one.

The hosts file can be downloaded from the link I provided. It is this:
http://winhelp2002.mvps.org/hosts.txt

Thanks for looking into this and creating this program by the way!

**Comment by 10se1ucgo** [comment]
OK, confirmed that its broken.

I believe it has to do with my program erasing every line that begins with 0.0.0.0 for some odd reason, I'm looking into it now.

**Comment by 10se1ucgo** [comment]
Ahhh, I'm an idiot.

I added 0.0.0.0 to the list, and forgot to exclude it in the reversion process, so it assumed everything with 0.0.0.0 was a tracking domain added by my program. I'll be pushing a fix soon.

**Comment by 10se1ucgo** [comment]
Fixed via 0d1ac5ed516d5bb2a9f69e17334347651bed4d7f

Download: https://github.com/10se1ucgo/DisableWinTracking/releases/tag/v2.2.1
