### ISSUE TITLE
Suggestions/request

### ISSUE THREAD

**Issue by Chaython** [10se1ucgo/DisableWinTracking#440]
An option to auto-run after an update.
Add filters for other programs with telemetry
-Nvidia
-FireFox
-Chrome
 ... As the title is "DisableWinTracking" not "DisableMSTracking" so viable to support other windows apps.

[REDACTED] Don't liken people to other software from the issue page. You're passing responsibility on to us to verify these programs that people may go download, destroy their computer with, and then blame us for.

**Comment by DeeJayhX** [comment]
This software is no longer in development.
