### ISSUE TITLE
Selected disable but services removed?

### ISSUE THREAD

**Issue by Roki100** [10se1ucgo/DisableWinTracking#442]
why did it remove services when i selected disable?
**INFORMATION:**

* Windows Edition (Home/Pro/Enterprise): home
* Architecture (32bit/64bit): 64bit
* Options used: services, telemetry, privacy, disable mode

**LOG:**

```python
18:24:49 INFO: DisableWinTracking version 3.2.3
18:25:56 INFO: Services: Succesfully removed service 'dmwappushsvc'
18:25:56 INFO: Services: Succesfully removed service 'DiagTrack'
18:25:57 INFO: Registry: Successfully modified dmwappushsvc key.
18:25:57 INFO: Registry: Successfully modified DiagTrack key.
18:25:57 INFO: Registry: Successfully modified AllowTelemetry key.
```

**Comment by DeeJayhX** [comment]
It's been a while since the code was maintained. Did you check your actual services to see if they were removed or if it's just a logging typo?

**Comment by Chaython** [comment]
As this is dead, how about we suggest alternatives in the read me.
SimpleWall https://github.com/henrypp/simplewall an open source GUI for WFP has disable/block for all MS services and common ports.
They have their own list including those sourced here https://github.com/crazy-max/WindowsSpyBlocker which is very active

**Comment by Chaython** [comment]
You should never remove their telementry garbage, only disable it. As removing it may [and has for me] broken windows update.

**Comment by Roki100** [comment]
> It's been a while since the code was maintained. Did you check your actual services to see if they were removed or if it's just a logging typo?

yeah these services are gone
