### ISSUE TITLE
This coule be updated to support different versions of windows 10

### ISSUE THREAD

**Issue by modz2014** [10se1ucgo/DisableWinTracking#443]
hey can this is not really a big issue bu this could be updated to 
windows Version 1903 OS Build 18362 as the layout is different and diagnostics stuff is also different so it doesn't Privacy settings on like it does on the previous version of windows 10 please look into this as i love this app i use all the time i install windows 10

**Comment by Chaython** [comment]
The default script should block telemetry servers so the diagnostic settings are redundant.
Use Simplewall and w10privacy if you want to disable further stuff and watch packets.

**Comment by DeeJayhX** [comment]
The last commit was 8 months before this issue was opened. This software isn't being developed anymore.

**Comment by modz2014** [comment]
This is issue was opened a year ago how does that work

**Comment by DeeJayhX** [comment]
You should read the first 2 lines of the readme:
https://github.com/10se1ucgo/DisableWinTracking/blob/master/README.md
