### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by eSargin** [10se1ucgo/DisableWinTracking#446]
**INFORMATION:**

* Windows Edition (Home/Pro/Enterprise):
* Architecture (32bit/64bit):
* Options used:

**LOG:**

```python
REPLACE THIS WITH DWT.LOG
```

**Comment by Chaython** [comment]
Why create a ticket without info?

**Comment by JonasHau** [comment]
Hello @eSargin,
What is the issue that you encountered, if there is any ?

**Comment by DeeJayhX** [comment]
No log
