### ISSUE TITLE
bello

### ISSUE THREAD

**Issue by nana058** [10se1ucgo/DisableWinTracking#452]
**INFORMATION:**

* Windows Edition (Home/Pro/Enterprise):
* Architecture (32bit/64bit):
* Options used:

**LOG:**

```python
REPLACE THIS WITH DWT.LOG
```

**Comment by Chaython** [comment]
Why the spam?

**Comment by JonasHau** [comment]
Hello @nana058,
What is the issue that you encountered, if there is any ?

**Comment by DeeJayhX** [comment]
No log
