### ISSUE TITLE
0

### ISSUE THREAD

**Issue by mkkhime** [10se1ucgo/DisableWinTracking#454]
**INFORMATION:**

* Windows Edition (Home/Pro/Enterprise):
* Architecture (32bit/64bit):
* Options used:

**LOG:**

```python
REPLACE THIS WITH DWT.LOG
```
14:20:03 INFO: Python 2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:22:17) [MSC v.1500 32 bit (Intel)] on win32
14:20:03 INFO: ('Windows', 'DESKTOP-OFBH1P9', '10', '10.0.18362', 'AMD64', 'Intel64 Family 6 Model 61 Stepping 4, GenuineIntel')
14:20:03 INFO: DisableWinTracking version 3.2.3
14:20:27 INFO: IP Blocker: The IP 134.170.30.202 was successfully blocked.
14:20:27 INFO: IP Blocker: The IP 137.116.81.24 was successfully blocked.
14:20:27 INFO: IP Blocker: The IP 157.56.106.189 was successfully blocked.
14:20:28 INFO: IP Blocker: The IP 2.22.61.43 was successfully blocked.
14:20:28 INFO: IP Blocker: The IP 2.22.61.66 was successfully blocked.
14:20:28 INFO: IP Blocker: The IP 204.79.197.200 was successfully blocked.
14:20:28 INFO: IP Blocker: The IP 23.218.212.69 was successfully blocked.
14:20:28 INFO: IP Blocker: The IP 64.4.54.254 was successfully blocked.
14:20:28 INFO: IP Blocker: The IP 65.39.117.230 was successfully blocked.
14:20:28 INFO: IP Blocker: The IP 65.52.108.33 was successfully blocked.
14:20:28 INFO: IP Blocker: The IP 65.55.108.23 was successfully blocked.
14:20:29 INFO: DiagTrack: DiagTrack service doesn't exist. This is OK, you likely removed it already.
14:20:29 INFO: DiagTrack: Completed Part 1/3
14:20:29 INFO: DiagTrack: dmwappushservice service doesn't exist. This is OK, you likely removed it already.
14:20:29 INFO: DiagTrack: Completed Part 2/3
14:20:29 INFO: DiagTrack: Successfully erased tracking log.
14:20:29 INFO: DiagTrack: Completed Part 3/3
14:20:29 INFO: DiagTrack: Completed successfully, without errors.
14:20:30 INFO: Registry: Successfully modified dmwappushsvc key.
14:20:30 INFO: Registry: Successfully modified DiagTrack key.
14:20:30 INFO: Registry: Successfully modified AllowTelemetry key.
14:20:30 INFO: Registry: Successfully modified WifiSense Open-ness key.
14:20:30 INFO: Registry: Successfully modified WifiSense Credential Share key.
14:20:30 INFO: Registry: Successfully modified ListPin key.
14:20:30 INFO: Registry: Successfully modified ListPin64Bit key.
14:20:30 INFO: Registry: Successfully modified FileSync key.
14:21:05 INFO: OneDrive: successfully uninstalled
14:21:05 INFO: Registry: Successfully modified GameDVR_Enabled key.
14:21:05 INFO: Registry: Successfully modified AllowGameDVR key.
14:21:05 INFO: Xbox DVR: successfully disabled
14:21:05 INFO: Done. It's recommended that you reboot as soon as possible for the full effect.
14:21:05 INFO: If you feel something didn't work properly, please press the 'Report an issue' button and follow the directions
14:21:08 INFO: IP Blocker: The IP 134.170.30.202 was successfully blocked.
14:21:08 INFO: IP Blocker: The IP 137.116.81.24 was successfully blocked.
14:21:09 INFO: IP Blocker: The IP 157.56.106.189 was successfully blocked.
14:21:09 INFO: IP Blocker: The IP 2.22.61.43 was successfully blocked.
14:21:09 INFO: IP Blocker: The IP 2.22.61.66 was successfully blocked.
14:21:09 INFO: IP Blocker: The IP 204.79.197.200 was successfully blocked.
14:21:09 INFO: IP Blocker: The IP 23.218.212.69 was successfully blocked.
14:21:09 INFO: IP Blocker: The IP 64.4.54.254 was successfully blocked.
14:21:09 INFO: IP Blocker: The IP 65.39.117.230 was successfully blocked.
14:21:09 INFO: IP Blocker: The IP 65.52.108.33 was successfully blocked.
14:21:09 INFO: IP Blocker: The IP 65.55.108.23 was successfully blocked.
14:21:09 INFO: DiagTrack: DiagTrack service doesn't exist. This is OK, you likely removed it already.
14:21:09 INFO: DiagTrack: Completed Part 1/3
14:21:10 INFO: DiagTrack: dmwappushservice service doesn't exist. This is OK, you likely removed it already.
14:21:10 INFO: DiagTrack: Completed Part 2/3
14:21:10 INFO: DiagTrack: Successfully erased tracking log.
14:21:10 INFO: DiagTrack: Completed Part 3/3
14:21:10 INFO: DiagTrack: Completed successfully, without errors.
14:21:10 INFO: Registry: Successfully modified dmwappushsvc key.
14:21:10 INFO: Registry: Successfully modified DiagTrack key.
14:21:10 INFO: Registry: Successfully modified AllowTelemetry key.
14:21:10 INFO: Registry: Successfully modified WifiSense Open-ness key.
14:21:10 INFO: Registry: Successfully modified WifiSense Credential Share key.
14:21:10 INFO: Registry: Successfully modified ListPin key.
14:21:10 INFO: Registry: Successfully modified ListPin64Bit key.
14:21:10 INFO: Registry: Successfully modified FileSync key.
14:21:34 INFO: OneDrive: successfully uninstalled
14:21:34 INFO: Registry: Successfully modified GameDVR_Enabled key.
14:21:34 INFO: Registry: Successfully modified AllowGameDVR key.
14:21:34 INFO: Xbox DVR: successfully disabled
14:21:34 INFO: Done. It's recommended that you reboot as soon as possible for the full effect.
14:21:34 INFO: If you feel something didn't work properly, please press the 'Report an issue' button and follow the directions

**Comment by Chaython** [comment]
No errors? Why create an issue?

**Comment by JonasHau** [comment]
Hello @mkkhime,
What is the issue that you encountered, if there is any ?
