### ISSUE TITLE
Deletes services with Disable method selected

### ISSUE THREAD

**Issue by BvDoesburg** [10se1ucgo/DisableWinTracking#459]
After downoad and start of the exe, checking all boxes I hit the Go! button. Everything looked ok but there was a message that said the services were deleted, even though the "Disable" method was selected. And checking the services they were indeed gone.

* Windows Edition Pro
* Architecture 64bit
* Options used: All

**LOG:**
22:46:21 INFO: Python 2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:22:17) [MSC v.1500 32 bit (Intel)] on win32
22:46:21 INFO: ('Windows', 'xxx', '10', '10.0.18362', 'AMD64', 'Intel64 Family 6 Model 58 Stepping 9, GenuineIntel')
22:46:21 INFO: DisableWinTracking version 3.2.3
22:48:38 INFO: IP Blocker: The IP 134.170.30.202 was successfully blocked.
22:48:38 INFO: IP Blocker: The IP 137.116.81.24 was successfully blocked.
22:48:39 INFO: IP Blocker: The IP 157.56.106.189 was successfully blocked.
22:48:39 INFO: IP Blocker: The IP 2.22.61.43 was successfully blocked.
22:48:39 INFO: IP Blocker: The IP 2.22.61.66 was successfully blocked.
22:48:39 INFO: IP Blocker: The IP 204.79.197.200 was successfully blocked.
22:48:40 INFO: IP Blocker: The IP 23.218.212.69 was successfully blocked.
22:48:40 INFO: IP Blocker: The IP 64.4.54.254 was successfully blocked.
22:48:40 INFO: IP Blocker: The IP 65.39.117.230 was successfully blocked.
22:48:41 INFO: IP Blocker: The IP 65.52.108.33 was successfully blocked.
22:48:41 INFO: IP Blocker: The IP 65.55.108.23 was successfully blocked.
22:48:41 INFO: DiagTrack: Successfully deleted service 'DiagTrack'
22:48:41 INFO: DiagTrack: Completed Part 1/3
22:48:41 INFO: DiagTrack: Successfully deleted service 'dmwappushservice'
22:48:41 INFO: DiagTrack: Completed Part 2/3
22:48:41 INFO: DiagTrack: Successfully erased tracking log.
22:48:41 INFO: DiagTrack: Completed Part 3/3
22:48:41 INFO: DiagTrack: Completed successfully, without errors.
22:48:42 INFO: Registry: Successfully modified dmwappushsvc key.
22:48:42 INFO: Registry: Successfully modified DiagTrack key.
22:48:42 INFO: Registry: Successfully modified AllowTelemetry key.
22:48:43 INFO: Registry: Successfully modified WifiSense Open-ness key.
22:48:43 INFO: Registry: Successfully modified WifiSense Credential Share key.
22:48:43 INFO: Registry: Successfully modified ListPin key.
22:48:43 INFO: Registry: Successfully modified ListPin64Bit key.
22:48:43 INFO: Registry: Successfully modified FileSync key.
22:49:09 INFO: OneDrive: successfully uninstalled
22:49:09 INFO: Registry: Successfully modified GameDVR_Enabled key.
22:49:09 INFO: Registry: Successfully modified AllowGameDVR key.
22:49:09 INFO: Xbox DVR: successfully disabled
22:49:09 INFO: Done. It's recommended that you reboot as soon as possible for the full effect.
22:49:09 INFO: If you feel something didn't work properly, please press the 'Report an issue' button and follow the directions

```python
REPLACE THIS WITH DWT.LOG
```

**Comment by DeeJayhX** [comment]
Notice that there is a services checkbox for the services method:
![image](https://user-images.githubusercontent.com/1514573/103203125-1a216080-48a9-11eb-80de-7e20d31e1bdc.png)

From the log you provided:
`22:48:41 INFO: DiagTrack: Successfully deleted service 'DiagTrack'`

That is the second checkbox. Honestly, I can see where there is some disconnect between the Services checkbox and the Service Method group on the right, but they are mutually exclusive from DiagTrack fix. If you merely disable it, it will re-enable itself. Microsoft wants that sweet sweet telemetry data.
