### ISSUE TITLE
"File not found" when trying to remove OneDrive

### ISSUE THREAD

**Issue by Tom-Evers** [10se1ucgo/DisableWinTracking#460]
**INFORMATION:**

* Windows Edition (Home/Pro/Enterprise): Pro
* Architecture (32bit/64bit): 64 bit
* Options used: Uninstall OneDrive (mode: Disable)

![image](https://user-images.githubusercontent.com/10848631/92371483-8127c900-f0b0-11ea-8a1d-06d82ce7b4e7.png)

**Comment by Tom-Evers** [comment]
I'm able to run ```wmic os get OSArchitecture``` in both cmd and powershell

**Comment by DeeJayhX** [comment]
No log.

**Comment by Tom-Evers** [comment]
> No log.

Err, then ask for one, don't just close the issue.

I'll try reproducing this problem I diligently reported several months ago.

**Comment by DeeJayhX** [comment]
> > No log.
> 
> Err, then ask for one, don't just close the issue.

## Allow me to post the default issue text for you that has been there for YEARS.

**INFORMATION:**

* Windows Edition (Home/Pro/Enterprise):
* Architecture (32bit/64bit):
* Options used:

**LOG:**

# >>>>> REPLACE THIS WITH DWT.LOG <<<<<

In addition, You should read the first 2 lines of the readme:
https://github.com/10se1ucgo/DisableWinTracking/blob/master/README.md

Have a nice day.
