### ISSUE TITLE
First time user. Everything worked but one drive.

### ISSUE THREAD

**Issue by webadage** [10se1ucgo/DisableWinTracking#461]
* problem was: unable to disable ONE DRIVE, exited with error code [included in log]

* Windows Edition (Home/Pro/Enterprise):  Pro
* Architecture (32bit/64bit): 64bit
* Options used: all

**LOG:**
09:22:26 INFO: Python 2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:22:17) [MSC v.1500 32 bit (Intel)] on win32
09:22:26 INFO: ('Windows', 'Phoenix0', '10', '10.0.16299', 'AMD64', 'Intel64 Family 6 Model 94 Stepping 3, GenuineIntel')
09:22:26 INFO: DisableWinTracking version 3.2.3
09:24:35 INFO: IP Blocker: The IP 134.170.30.202 was successfully blocked.
09:24:35 INFO: IP Blocker: The IP 137.116.81.24 was successfully blocked.
09:24:35 INFO: IP Blocker: The IP 157.56.106.189 was successfully blocked.
09:24:35 INFO: IP Blocker: The IP 2.22.61.43 was successfully blocked.
09:24:35 INFO: IP Blocker: The IP 2.22.61.66 was successfully blocked.
09:24:35 INFO: IP Blocker: The IP 204.79.197.200 was successfully blocked.
09:24:35 INFO: IP Blocker: The IP 23.218.212.69 was successfully blocked.
09:24:36 INFO: IP Blocker: The IP 64.4.54.254 was successfully blocked.
09:24:36 INFO: IP Blocker: The IP 65.39.117.230 was successfully blocked.
09:24:36 INFO: IP Blocker: The IP 65.52.108.33 was successfully blocked.
09:24:36 INFO: IP Blocker: The IP 65.55.108.23 was successfully blocked.
09:24:36 INFO: DiagTrack: Successfully deleted service 'DiagTrack'
09:24:36 INFO: DiagTrack: Completed Part 1/3
09:24:36 INFO: DiagTrack: Successfully deleted service 'dmwappushservice'
09:24:36 INFO: DiagTrack: Completed Part 2/3
09:24:36 INFO: DiagTrack: Successfully erased tracking log.
09:24:36 INFO: DiagTrack: Completed Part 3/3
09:24:36 INFO: DiagTrack: Completed successfully, without errors.
09:24:36 INFO: Registry: Successfully modified dmwappushsvc key.
09:24:36 INFO: Registry: Successfully modified DiagTrack key.
09:24:36 INFO: Registry: Successfully modified AllowTelemetry key.
09:24:37 INFO: Registry: Successfully modified ListPin key.
09:24:37 INFO: Registry: Successfully modified ListPin64Bit key.
09:24:37 INFO: Registry: Successfully modified FileSync key.
09:24:38 INFO: OneDrive: unable to uninstall. Exited with code: -2147219823 - ('', '')
09:24:38 INFO: Registry: Successfully modified GameDVR_Enabled key.
09:24:38 INFO: Registry: Successfully modified AllowGameDVR key.
09:24:38 INFO: Xbox DVR: successfully disabled
09:24:38 INFO: Done. It's recommended that you reboot as soon as possible for the full effect.
09:24:38 INFO: If you feel something didn't work properly, please press the 'Report an issue' button and follow the directions

```python
REPLACE THIS WITH DWT.LOG
```

**Comment by DeeJayhX** [comment]
That exit code -2147219823 indicates "Software update source not found". Seems like you had already removed onedrive?
