### ISSUE TITLE
not work !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by mnpoorsadegh** [10se1ucgo/DisableWinTracking#463]
**INFORMATION:**

* Windows Edition (Home/Pro/Enterprise):
* Architecture (32bit/64bit):
* Options used:

**LOG:**

```python
REPLACE THIS WITH DWT.LOG
```

**Comment by mnpoorsadegh** [comment]
what should i do
this app not work and crash

**Comment by DeeJayhX** [comment]
> what should i do
> this app not work and crash

You should read the first 2 lines of the readme:
https://github.com/10se1ucgo/DisableWinTracking/blob/master/README.md
