### ISSUE TITLE
ERROR: Hosts: Failed to modify hosts file

### ISSUE THREAD

**Issue by tradosfxe** [10se1ucgo/DisableWinTracking#465]
**INFORMATION:**

* Windows Edition (Home/Pro/Enterprise):
* Architecture (32bit/64bit):
* Options used:

**LOG:**

00:47:40 INFO: Python 2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:22:17) [MSC v.1500 32 bit (Intel)] on win32
00:47:40 INFO: ('Windows', 'DESKTOP-0RQ6G74', '10', '10.0.18362', 'AMD64', 'Intel64 Family 6 Model 58 Stepping 9, GenuineIntel')
00:47:40 INFO: DisableWinTracking version 3.2.3
00:47:59 INFO: IP Blocker: The IP 134.170.30.202 was successfully blocked.
00:47:59 INFO: IP Blocker: The IP 137.116.81.24 was successfully blocked.
00:47:59 INFO: IP Blocker: The IP 157.56.106.189 was successfully blocked.
00:48:00 INFO: IP Blocker: The IP 2.22.61.43 was successfully blocked.
00:48:00 INFO: IP Blocker: The IP 2.22.61.66 was successfully blocked.
00:48:00 INFO: IP Blocker: The IP 204.79.197.200 was successfully blocked.
00:48:00 INFO: IP Blocker: The IP 23.218.212.69 was successfully blocked.
00:48:00 INFO: IP Blocker: The IP 64.4.54.254 was successfully blocked.
00:48:00 INFO: IP Blocker: The IP 65.39.117.230 was successfully blocked.
00:48:01 INFO: IP Blocker: The IP 65.52.108.33 was successfully blocked.
00:48:01 INFO: IP Blocker: The IP 65.55.108.23 was successfully blocked.
00:48:01 INFO: DiagTrack: DiagTrack service doesn't exist. This is OK, you likely removed it already.
00:48:01 INFO: DiagTrack: Completed Part 1/3
00:48:01 INFO: DiagTrack: dmwappushservice service doesn't exist. This is OK, you likely removed it already.
00:48:01 INFO: DiagTrack: Completed Part 2/3
00:48:01 INFO: DiagTrack: Successfully erased tracking log.
00:48:01 INFO: DiagTrack: Completed Part 3/3
00:48:01 INFO: DiagTrack: Completed successfully, without errors.
00:48:01 INFO: Registry: Successfully modified dmwappushsvc key.
00:48:01 INFO: Registry: Successfully modified DiagTrack key.
00:48:01 INFO: Registry: Successfully modified AllowTelemetry key.
00:48:01 ERROR: Hosts: Failed to modify hosts file
Traceback (most recent call last):
  File "dwt_util.py", line 312, in host_file
IOError: [Errno 13] Permission denied: 'C:\\Windows\\System32/drivers/etc/hosts'
00:48:01 ERROR: Hosts: Failed to modify hosts file
Traceback (most recent call last):
  File "dwt_util.py", line 312, in host_file
IOError: [Errno 13] Permission denied: 'C:\\Windows\\System32/drivers/etc/hosts'
00:48:01 INFO: Registry: Successfully modified WifiSense Open-ness key.
00:48:01 INFO: Registry: Successfully modified WifiSense Credential Share key.
00:48:02 INFO: Registry: Successfully modified ListPin key.
00:48:02 INFO: Registry: Successfully modified ListPin64Bit key.
00:48:02 INFO: Registry: Successfully modified FileSync key.
00:48:22 INFO: OneDrive: successfully uninstalled
00:48:22 INFO: Registry: Successfully modified GameDVR_Enabled key.
00:48:22 INFO: Registry: Successfully modified AllowGameDVR key.
00:48:22 INFO: Xbox DVR: successfully disabled
00:48:22 INFO: Done. It's recommended that you reboot as soon as possible for the full effect.
00:48:22 INFO: If you feel something didn't work properly, please press the 'Report an issue' button and follow the directions

**Comment by DeeJayhX** [comment]
@tradosfxe 
Notice the bold text:
IOError: [Errno 13] **Permission denied**: 'C:\Windows\System32/drivers/etc/hosts'

Either you didn't run the program as administrator (I'm guessing you did by the looks of the rest of the log) or you have some antivirus running like Avast that prevents anything from modifying the hosts file (common practice of third party AVs)
