### ISSUE TITLE
Fails to edit the hosts file with Administrator privliges. (Solution included)

### ISSUE THREAD

**Issue by GigaXCodes** [10se1ucgo/DisableWinTracking#466]
**INFORMATION:**
Fails to edit the hosts file with Administrator privliges.

* Windows Edition (Home/Pro/Enterprise): Pro
* Architecture (32bit/64bit): 64bit
* Options used: All

**SOLUTION:**
Tell the user to check if the Write-protection is active on this file.
If unchecked, it works.

**LOG:**
12:54:00 ERROR: Hosts: Failed to modify hosts file
Traceback (most recent call last):
  File "dwt_util.py", line 312, in host_file
IOError: [Errno 13] Permission denied: 'C:\\WINDOWS\\System32/drivers/etc/hosts'
12:54:00 ERROR: Hosts: Failed to modify hosts file
Traceback (most recent call last):
  File "dwt_util.py", line 312, in host_file
IOError: [Errno 13] Permission denied: 'C:\\WINDOWS\\System32/drivers/etc/hosts'

**Comment by DeeJayhX** [comment]
Read the first 2 lines of the Readme:
https://github.com/10se1ucgo/DisableWinTracking/blob/master/README.md
