### ISSUE TITLE
Add ssw.live.com to hosts blacklist?

### ISSUE THREAD

**Issue by RowanDDR** [10se1ucgo/DisableWinTracking#47]
Add ssw.live.com to hosts blacklist?

Quote:
> Windows 10 will periodically send data to a Microsoft server named ssw.live.com. This server seems to be used for OneDrive and some other Microsoft services. Windows 10 seems to transmit information to the server even when OneDrive is disabled and logins are using a local account that isn't connected to a Microsoft Account. The exact nature of the information being sent isn't clear—it appears to be referencing telemetry settings—and again, it's not clear why any data is being sent at all. We disabled telemetry on our test machine using group policies.

Source: http://arstechnica.co.uk/information-technology/2015/08/even-when-told-not-to-windows-10-just-cant-stop-talking-to-microsoft/

**Comment by 10se1ucgo** [comment]
Done.
