### ISSUE TITLE
Request: hosts in raw form

### ISSUE THREAD

**Issue by lencc** [10se1ucgo/DisableWinTracking#50]
Could you create a raw list of all the hosts blocked by your tool?
So the hosts could be merged with other sources as well (such as [StevenBlack amalgamated hosts file](https://github.com/StevenBlack/hosts/)).

**Comment by 10se1ucgo** [comment]
Not on a computer right now so I can't do it, but if you can't wait just run the program and copy what it writes to the hosts file.

**Comment by 10se1ucgo** [comment]
[Here](https://gist.github.com/10se1ucgo/fcb774d781a66ea9d31f)

**Comment by lencc** [comment]
Thank you!
If I'm right, blocking these domains shouldn't affect Windows 10 functionalities, but only protect privacy ([or at least try to](http://www.overclock.net/t/1569236/localghost-a-traffic-analysis-of-windows-10)).
