### ISSUE TITLE
Mail app/Outlook - Cannot add accounts

### ISSUE THREAD

**Issue by StinkyMojo** [10se1ucgo/DisableWinTracking#51]
Thanks for your great work! 

![mail](https://cloud.githubusercontent.com/assets/14001433/9538478/dbb1c8ae-4cf9-11e5-9184-7aaee92bde08.png)

![outlook](https://cloud.githubusercontent.com/assets/14001433/9538479/dd1dfbd6-4cf9-11e5-8728-ca6785e3df93.png)

**Comment by 10se1ucgo** [comment]
I'll look into this in the morning, thanks for the report.

**Comment by 10se1ucgo** [comment]
Fixed in 168022e0062641347b4a10c2e1dbf7ca640bbfe2

Download v2.3 here: https://github.com/10se1ucgo/DisableWinTracking/releases/tag/v2.3
