### ISSUE TITLE
I have ideas...

### ISSUE THREAD

**Issue by Ovrclockd** [10se1ucgo/DisableWinTracking#53]
http://someonewhocares.org/hosts/
https://www.youtube.com/watch?v=n9tYLBNX4z8

Could we combine everyone's best work into your code and really stick it to Microsoft?

http://winaero.com/blog/how-to-disable-telemetry-and-data-collection-in-windows-10/

Another great article with what looks like more to add, look at the comments section as well...

**Comment by Ruined1** [comment]
Everything related to privacy from these sources is already implemented. We may expand to some other features, but in this project's current infant state, the rest would be beyond the scope of the project. We'll always have this to reference though. Thank you.
