### ISSUE TITLE
Improve Hosts File error message

### ISSUE THREAD

**Issue by Flosus** [10se1ucgo/DisableWinTracking#54]
Because of the rewrite my pull requests got closed.
But i think this is quit important:

Some Anti virus programs are blocking access to the hosts file. It should be noted in case of an inaccessible host file to check the running anti virus programs in the error message, because users may not expect this.

**Comment by 10se1ucgo** [comment]
Error messages are now replaced by `logging.exception()`, so error messages that are printed should just explain something is wrong, with DisableWinTacking.log containing the detailed error.
