### ISSUE TITLE
Request to revert changes back to Microsoft default

### ISSUE THREAD

**Issue by celendis** [10se1ucgo/DisableWinTracking#6]
I applaud these efforts, and I do not want to diminish anything that you are doing. However, there may be unforseen cases that may be better handled by reverting these settings back to the Microsoft defaults.

**Comment by 10se1ucgo** [comment]
There should never be a case where enabling diagnostic tracking should "fix" anything. If you need to revert these, look into the source code and do the opposite of what it does.
