### ISSUE TITLE
Will tracking IPs be imported by other firewalls?

### ISSUE THREAD

**Issue by mtomas7** [10se1ucgo/DisableWinTracking#64]
Hi, thank you for doing this important work!

As I understand, the tracking IPs will be blocked only in Windows FW. But what happens when I install Comodo Internet Security? Is it usual that custom firewall would import settings from Windows FW, or it should be done manually?

**Comment by ScottRFrost** [comment]
I'd also like an IP range list for my router / firewall :+1:

**Comment by 10se1ucgo** [comment]
I'm not sure about imports for third party firewalls, but if you'd like to be sure [you can find a list of IPs here](https://gist.github.com/10se1ucgo/fcb774d781a66ea9d31f)

**Comment by ScottRFrost** [comment]
These are hostnames (for a host file), not IP address ranges (for a router or firewall).  Here's what I'm rolling currently: 

23.212.108.0/24
64.4.0.0/18
65.52.0.0/14
111.221.29.0/24
157.56.91.77
168.61.0.0/16
168.62.0.0/15

**Comment by 10se1ucgo** [comment]
@mtomas7 did not ask for ranges.

I don't have any.
