### ISSUE TITLE
Does not seem to work with french OS (v2.4)

### ISSUE THREAD

**Issue by Hewyn** [10se1ucgo/DisableWinTracking#68]
Hi there!

I have a French laptop and here is what happens when I try to use your program v2.4:

>16:17:40 ERROR: Registry: Unable to modify Service dmwappushsvc key.
>Traceback (most recent call last):
>  File "<string>", line 474, in modifyregistry
>WindowsError: [Error 2] Le fichier spécifié est introuvable

last line means : the specified file is missing

>16:17:40 ERROR: Services: dmwappushsvc unable to be stopped.
>Traceback (most recent call last):
>  File "<string>", line 358, in disableservice
>  File "disablewintracking\win32serviceutil", line 409, in StopService
>  File "disablewintracking\win32serviceutil", line 320, in ControlService
>error: (1062, 'ControlService', 'Le service n\x92a pas \xe9t\xe9 d\xe9marr\xe9.')

last line means: the service has not been launched

>16:17:40 ERROR: Services: Diagnostics Tracking Service unable to be stopped.
>Traceback (most recent call last):
>  File "<string>", line 358, in disableservice
>  File "disablewintracking\win32serviceutil", line 409, in StopService
>  File "disablewintracking\win32serviceutil", line 318, in ControlService
>  File "disablewintracking\win32serviceutil", line 80, in SmartOpenService
>error: (1060, 'GetServiceKeyName', 'Le service sp\xe9cifi\xe9 n\x92existe pas en tant que service >install\xe9.')

last line means: the specified service does not exist as an installed service

>16:17:40 ERROR: Services: Diagnostics Tracking Service unable to be stopped.
>Traceback (most recent call last):
> File "<string>", line 358, in disableservice
>  File "disablewintracking\win32serviceutil", line 409, in StopService
>  File "disablewintracking\win32serviceutil", line 318, in ControlService
>  File "disablewintracking\win32serviceutil", line 80, in SmartOpenService
>error: (1060, 'GetServiceKeyName', 'Le service sp\xe9cifi\xe9 n\x92existe pas en tant que service >install\xe9.')

last line means: the specified service does not exist as an installed service

>16:17:40 ERROR: DiagTrack Log: Unable to clear/lock
>Traceback (most recent call last):
>  File "<string>", line 339, in cleardiagtracklog
>IOError: [Errno 13] Permission >denied: 'C:\\ProgramData\\Microsoft\\Diagnosis\\ETLLogs\\AutoLogger\\AutoLogger-Diagtrack->Listener.etl'

It works well with my English desktop. I believe it did not work with my laptop because it checks my location when it boots into Windows 10.

I don't mind to set my laptop in English if I have to.

Thanks for your help

**Comment by Ruined1** [comment]
**IF you have run a this program more than once, including previous versions, the following are ok, otherwise let me know**

> 16:17:40 ERROR: Registry: Unable to modify Service dmwappushsvc key.
> Traceback (most recent call last):
> File "", line 474, in modifyregistry
> WindowsError: [Error 2] Le fichier spécifié est introuvable
**The file would be missing because it was already removed previously**

> 16:17:40 ERROR: Services: dmwappushsvc unable to be stopped.
> Traceback (most recent call last):
> File "", line 358, in disableservice
> File "disablewintracking\win32serviceutil", line 409, in StopService
> File "disablewintracking\win32serviceutil", line 320, in ControlService
> error: (1062, 'ControlService', 'Le service n\x92a pas \xe9t\xe9 d\xe9marr\xe9.')
> last line means: the service has not been launched
**Can't be launched or stopped if it was deleted previously**

> 16:17:40 ERROR: Services: Diagnostics Tracking Service unable to be stopped.
> Traceback (most recent call last):
> File "", line 358, in disableservice
> File "disablewintracking\win32serviceutil", line 409, in StopService
> File "disablewintracking\win32serviceutil", line 318, in ControlService
> File "disablewintracking\win32serviceutil", line 80, in SmartOpenService
> error: (1060, 'GetServiceKeyName', 'Le service sp\xe9cifi\xe9 n\x92existe pas en tant que service >install\xe9.')
> last line means: the specified service does not exist as an installed service
> 
> 16:17:40 ERROR: Services: Diagnostics Tracking Service unable to be stopped.
> Traceback (most recent call last):
> File "", line 358, in disableservice
> File "disablewintracking\win32serviceutil", line 409, in StopService
> File "disablewintracking\win32serviceutil", line 318, in ControlService
> File "disablewintracking\win32serviceutil", line 80, in SmartOpenService
> error: (1060, 'GetServiceKeyName', 'Le service sp\xe9cifi\xe9 n\x92existe pas en tant que service >install\xe9.')
> last line means: the specified service does not exist as an installed service
> 
> 16:17:40 ERROR: DiagTrack Log: Unable to clear/lock
> Traceback (most recent call last):
> File "", line 339, in cleardiagtracklog
> IOError: [Errno 13] Permission >denied: >'C:\ProgramData\Microsoft\Diagnosis\ETLLogs\AutoLogger\AutoLogger-Diagtrack->Listener.etl'
**Can't be modified if it was deleted previously**

**Comment by Hewyn** [comment]
Hi Ruined1 thanks for your answer.

To be honest I don't remember if I have ever used it on my laptop. Yes, It might be possible. 
I'm gonna say it is the reason why it didn't work and close this issue.

Thanks for your help!

**Comment by Ruined1** [comment]
No problem, happy to help, language definitely shouldn't effect the program, so I thought this might be the cause. Thanks for participating! Enjoy your privacy :smile:
