### ISSUE TITLE
IP blocking null routing (not hostname)

### ISSUE THREAD

**Issue by NetworkPro** [10se1ucgo/DisableWinTracking#7]
The tool tries to block IPs through hosts file which does not work.
 
The IPs can be blocked by routing them to On-Link "0.0.0.0" like this:
 
route -p add 65.55.108.23 MASK 255.255.255.255 0.0.0.0
route -p add 65.39.117.230 MASK 255.255.255.255 0.0.0.0
route -p add 23.218.212.69 MASK 255.255.255.255 0.0.0.0
route -p add 134.170.30.202 MASK 255.255.255.255 0.0.0.0
route -p add 137.116.81.24 MASK 255.255.255.255 0.0.0.0
route -p add 204.79.197.200 MASK 255.255.255.255 0.0.0.0

More ways to catch outgoing connections:

- Windows Firewall Control or http://wfn.codeplex.com/releases
- GlassWire

Regards.

**Comment by 10se1ucgo** [comment]
Yep someone has mentioned this, however the list I used was simply generated from a hosts file I found on the MDL forums. I'll look into this
