### ISSUE TITLE
Errors in DisableWinTracking.log

### ISSUE THREAD

**Issue by Jastreb** [10se1ucgo/DisableWinTracking#70]
I ran this tool previously not sure which version but its called RUN.exe

I have now tried the prerelease(?) 2.4 version and got errors in the log for almost everything with exception of skype/mail fix and another one, can remember which, but you can see it in log I am attaching.

https://drive.google.com/file/d/0ByYZ00Ome8NTdmM0b2ozeEZOcGM/view?usp=sharing

Good work btw.

**Comment by Ruined1** [comment]
All of those "errors" are perfectly normal. At some point you have run the program with DELETE services selected. In turn, running it now, it's saying those services don't exist. (Because they don't, you deleted them.)

**Comment by Jastreb** [comment]
I fugured that was not a bug, but consider removing the ERROR label then in the app. Error indicates that something is wrong, while it is not as you described. Make it output something else, like "services not found", or "nothing to do here, done!"

More of a feature request :pray:

**Comment by 10se1ucgo** [comment]
There really is no way of doing this automatically. win32serviceutil just spits out a pywintypes.error whether or not it was a problem with finding it or if it just didn't have access. I'll be looking into creating a text file in AppData that signifies whether or not the program has been run before.

**Comment by Ruined1** [comment]
@Jastreb I already did in the latest versions it tells you that it's ok if you've run it before. :+1:
