### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by AWrightIV** [10se1ucgo/DisableWinTracking#71]
#### Console Output
> Registry: Unable to modify Service dmwappushsvc key.
> Registry: Service DiagTrack key successfully modified.
> Services: dmwappushsvc unable to be stopped.
> Services: Diagnostics Tracking Service successfully stopped.
> Services: Diagnostics Tracking Service unable to be stopped.
> DiagTrack Log: Succesfully cleared and locked.
> Done. It's recommended that you reboot as soon as possible for the full effect.
> If any errors were found, please make a GitHub ticket with the contents of DisableWinTracking.log

#### DisableWinTracking.log
> 10:11:24 ERROR: Registry: Unable to modify Service dmwappushsvc key.
> Traceback (most recent call last):
>   File "<string>", line 474, in modifyregistry
> WindowsError: [Error 2] The system cannot find the file specified
> 
> 10:11:24 ERROR: Services: dmwappushsvc unable to be stopped.
> Traceback (most recent call last):
>   File "<string>", line 358, in disableservice
>   File "disablewintracking\win32serviceutil", line 409, in StopService
>   File "disablewintracking\win32serviceutil", line 320, in ControlService
> error: (1062, 'ControlService', 'The service has not been started.')
> 
> 10:11:24 ERROR: Services: Diagnostics Tracking Service unable to be stopped.
> Traceback (most recent call last):
>   File "<string>", line 358, in disableservice
>   File "disablewintracking\win32serviceutil", line 409, in StopService
>   File "disablewintracking\win32serviceutil", line 320, in ControlService
> error: (1061, 'ControlService', 'The service cannot accept control messages at this time.')
>

**Comment by Ruined1** [comment]
These are all signs that the program has been run before (including previous versions) if this is the case, you can ignore these and close this issue. If not, let me know.
