### ISSUE TITLE
ELANTPCfg not working anymore

### ISSUE THREAD

**Issue by PeterVisscher** [10se1ucgo/DisableWinTracking#8]
After installation and restarting the computer several times i get this message at start up,
ELANTPCfg not working anymore. I then close the message and the computer continues too load fine it seems.

Edit: This message also pops up when i wake up the laptop from sleeping !

Edit 2: Installation report, everything selected and used disable.

Telemetry key succesfully modified.
2nd Telemetry key succesfully modified.
Unable to clear DiagTrack log. Deleted, or is the program not elevated?
Domains successfully appended to HOSTS file.
Unable to modify dmwappushsvc key. Deleted, or is the program not elevated?
Diagnostics Tracking Service unable to be stopped. Deleted, or is the program not elevated?
dmwappushsvc unable to be stopped. Deleted, or is the program not elevated?
Done. You can close this window after reading the log.

(i checked if the dmwappushsvc.dll was present in win10 and it is).

**Comment by 10se1ucgo** [comment]
The program doesn't delete the DLL, simply the service that uses it.

As for ELANTPCfg, I have no clue what that is and this program probably has nothing to do with it.
