### ISSUE TITLE
Are you blocking all of these?

### ISSUE THREAD

**Issue by Ovrclockd** [10se1ucgo/DisableWinTracking#80]
It is like the rabbit hole keeps getting deeper, make sure none of these have been missed, taken from Jimstone.is

Windows 10 BUSTED, AND IT IS CREEPY

Yeah, I guess HILLARY'S E-MAILS PROVED THE NSA AS A SOURCE IS NOT GOOD ENOUGH, because using them can land you in jail. THE NEW CONSULTEE IS (PROBABLY) MICROSOFT, why have your goons infiltrate an old outdated battleship like the NSA when that can backfire?

Why does Microsoft have a right to ALL text I type, the first 35 megabytes of video from a web cam every time it is turned on, and everything that gets picked up by the microphone? Ha, they don't BECAUSE I DO NOT USE THEIR PRODUCTS, if you have not woken up yet and still do, here is what now happens:

All text typed on the keyboard is stored in temporary files, and sent (once per 30 mins) to:

oca.telemetry.microsoft.com.nsatc.net
pre.footprintpredict.com
reports.wes.df.telemetry.microsoft.com
This will allow Microsoft and the greater Jewish community to have a way to steal every joke, every poem, every intellectual endeavor you ever create and have it copyrighted before you even stop typing.

Telemetry is sent once per 5 minutes, to:

vortex.data.microsoft.com
vortex-win.data.microsoft.com
telecommand.telemetry.microsoft.com
telecommand.telemetry.microsoft.com.nsatc.net
oca.telemetry.microsoft.com
oca.telemetry.microsoft.com.nsatc.net
sqm.telemetry.microsoft.com
sqm.telemetry.microsoft.com.nsatc.net
This allows them to track you very accurately.

Typing the name of any popular movie into your local file search starts a telemetry process that indexes all media files on your computer and transmits them to:

df.telemetry.microsoft.com
reports.wes.df.telemetry.microsoft.com
cs1.wpc.v0cdn.net
vortex-sandbox.data.microsoft.com
pre.footprintpredict.com
This allows them to index any "unauthorized" content, and build a dossier on you that can be used in conjunction with their tracking data to stuff almost anyone in jail when needed.

When a webcam is first enabled, ~35mb of data gets immediately transmitted to:

oca.telemetry.microsoft.com
oca.telemetry.microsoft.com.nsatc.net
vortex-sandbox.data.microsoft.com
i1.services.social.microsoft.com
i1.services.social.microsoft.com.nsatc.net
This allows them to get a good layout of your home and surroundings, and a good look at YOU PERSONALLY so they know exactly who to go get and how to stage the attack when something you typed pissed them off.

Everything that is said into an enabled microphone is immediately transmitted to:

oca.telemetry.microsoft.com
oca.telemetry.microsoft.com.nsatc.net
vortex-sandbox.data.microsoft.com
pre.footprintpredict.com
i1.services.social.microsoft.com
i1.services.social.microsoft.com.nsatc.net
telemetry.appex.bing.net
telemetry.urs.microsoft.com
cs1.wpc.v0cdn.net
statsfe1.ws.microsoft.com
So even if you do not type anything, just talking in the room is gonna get you nailed, and if you say anything they don't like they will already have had a good look at you personally with your web cam, plus your surroundings, plus your exact location with that telemetry data, so they can PEG YOU GOOD. Yeah, I guess HILLARY'S E-MAILS PROVED THE NSA AS A SOURCE IS NOT GOOD ENOUGH, because using them can land you in jail. THE NEW CONSULTEE IS MICROSOFT, why use an old outdated battleship like the NSA when that can backfire?

If this weren't bad enough, this behaviour still happens when Cortana (microsoft's version of SIRI) is not installed is SO IT IS NOT ANY HELPFUL ASSISTANT DOING THIS, IT IS A DATA AND PRIVACY RAPE PURE AND SIMPLE.

**Comment by brainscript** [comment]
@Ovrclockd I can't believe that this is true. This illegally and cruel! :imp:

**Comment by Ruined1** [comment]
@Ovrclockd all of those and more as far as I'm aware. We'll compare to make sure, but we're doing everything we can to fix this breach of privacy.

**Comment by 10se1ucgo** [comment]
Yes, these are all done.

**Comment by Gitoffthelawn** [comment]
Wow... anti-semitism rears its ugly head again.  Disgusting.

**Comment by 10se1ucgo** [comment]
@Gitoffthelawn Probably because nobody actually read his rant except you.

**Comment by Ruined1** [comment]
@10se1ucgo i would have left it. One, because it's probably accurate. Two, freedom of speech. Lol. I don't care i look at it as good people and bad people, doesn't matter your race, religion, or creed. Anywho this can probably be locked at this point :smile:

**Comment by 10se1ucgo** [comment]
Ehh, not sure about accuracy.. He said "This will allow Microsoft and the greater Jewish to have a way to steal every joke, every poem, every intellectual endeavor you ever create and have it copyrighted before you even stop typing."

**Comment by 10se1ucgo** [comment]
@Gitoffthelawn Wait, holy shit, I just read that website. What in the actual fuck. "Freelance journalist" Sorry for my previous comment, damn.

**Comment by Gitoffthelawn** [comment]
@Ruined1 Wow... you support anti-semitism?  Claiming that people of the Jewish faith are somehow in bed with Microsoft to steal things is just blatant prejudice.  Sorry to hear you support it.

**Comment by Ruined1** [comment]
@Gitoffthelawn That's not what I said, I was referring to M$'s attempts to log everything we do, and this is not the place to discuss it. Saying a particular group is doing something is not hate speech... He didn't slur or slander, he named a group of people he thought was committing a particular act, you just took offense to it. Issue was resolved 7 hours ago... I'm not saying your wrong, and I'm not saying OP was right, but this is insanely off topic, and so the conversation is now locked.

**Comment by 10se1ucgo** [comment]
Just so @Ovrclockd doesnt look bad, he didn't actually write that, he got it from a website.
