### ISSUE TITLE
Question: is blocking of host names and IPs necessary if proceses are deleted?

### ISSUE THREAD

**Issue by mtomas7** [10se1ucgo/DisableWinTracking#81]
Hi, I was asking related question before:

https://github.com/10se1ucgo/DisableWinTracking/issues/64

Now I want to get it more clear. It is not very common situation that standard Windows FireWall is active - most likely people will use some different security solution.

In this case we have to maintain some type of list to make it easy to import in other FireWalls or routers. Importing host names is not easy in some solutions. It looks that this would be the list:

https://gist.github.com/10se1ucgo/fcb774d781a66ea9d31f

But if we know that processes that generate those activities are no longer active, is the blocking of domain names and IPs just a double protection that most likely is not really needed?

Thank you!

**Comment by Ruined1** [comment]
@mtomas7 actually, I can't speak for the creator, but i never thought of that... excellent point to bring to our attention! Unfortunately there are many different software fields available and we can't provide for every single one... i would think a software firewall worth it's salt would be able to import our rules from the Windows firewall with a simple click of a button. I'm not sure what our approach on this would be... any techie (including myself) that i know just uses the Windows firewall, as it covers every function one could need. We'll let the creator come to a decision on this.

**Comment by 10se1ucgo** [comment]
@mtomas7 Unfortunately even after the services are disabled some other things call to home, so these IPs/domains are still necessary.

**Comment by mtomas7** [comment]
Thank you for the answer.

I am using Comodo IS, but I will try to use Windows FireWall with Windows Firewall Notifier, to make everything easier:

http://www.howtogeek.com/113641/how-to-extend-the-windows-firewall-and-easily-block-outgoing-connections/?PageSpeed=noscript
