### ISSUE TITLE
Add this article for all app removal 

### ISSUE THREAD

**Issue by jfmatth** [10se1ucgo/DisableWinTracking#82]
http://news.softpedia.com/news/how-to-remove-pre-installed-windows-10-apps-488894.shtml

I'm not sure the powershell equivalent in Python :(

**Comment by 10se1ucgo** [comment]
It's already implemented, I just haven't uploaded a compiled version yet because I'm working on another feature right now. I'll upload it soon.

**Comment by Ruined1** [comment]
And I'll do the stubborn APP removal whenever you're ready for me to implement it.

**Comment by jfmatth** [comment]
thank you.  Let me know if you need any help.
