### ISSUE TITLE
Donation

### ISSUE THREAD

**Issue by arnstein99** [10se1ucgo/DisableWinTracking#83]
Do you have a method for accepting donations? I would like to help.

**Comment by 10se1ucgo** [comment]
As nice as it is, I'd prefer if you'd donate it to charity or something, I'm just a kid having fun with computers :)

**Comment by Draxler** [comment]
^ ^ ^ ^ ^ ^ ^ ^ ^ ^
:+1: 
____________________

**Comment by s0rg0** [comment]
<3

**Comment by 10se1ucgo** [comment]
Gonna close this, thanks for your generous offer though :)
