### ISSUE TITLE
Bing.com

### ISSUE THREAD

**Issue by Hernandy** [10se1ucgo/DisableWinTracking#84]
Looks like i cant even open bing.com website completely, is this caused by the program? i did check all options

**Comment by Obihoernchen** [comment]
Yes.
The option "Block tracking IP addresses" blocks 204.79.197.200 which is bing.com (at least here in germany)
See: https://github.com/10se1ucgo/DisableWinTracking/blob/master/run.py#L425

There are 2 things you can do:
1) Disable the 204.79.197.200 rule in Windows firewall
2) Revert "Block tracking IP addresses"

**Comment by Hernandy** [comment]
Just a quick question is it OK to unblock that IP to make it bing.com working for search purpose only? will that caused other "~~Disable~~WinTracking" ?

**Comment by Ruined1** [comment]
It's blocked for a reason. If you must use Bing, rather than any of the other fantastic search engines available, such as Google, then you have to accept the tracking that comes with unblocking that domain.

**Comment by Obihoernchen** [comment]
Nevertheless the hint should state that this will block services like bing.com.

(I never used it, but there are people using bing out there ;)

**Comment by Hernandy** [comment]
I dont use it too, just accidentally open that site lol.

**If** that domain not affecting the tracking system, i dont see reason to block the "services" IP. 

I imagine if other tracking "services" domain like web.skype.com get blocked too -_-

People can chose what they want. An option will be appreciated.

**Comment by 10se1ucgo** [comment]
It's being worked on.

**Comment by 10se1ucgo** [comment]
Sorry for the slow progress, I started high school and time is short. Hard to manage homework, games, anime and this at the same time :P

**Comment by Ruined1** [comment]
@10se1cugo if you're ever tied up and something needs done just assign it to me and I'll comment if i can pick it up :+1: unfortunately sometimes there's things i spend 15 hours on and just can't crack (e.g. registry) lol

**Comment by 10se1ucgo** [comment]
Implemented in 0b235e9775c1371a87783441bd1cae1aa8eb07b4
