### ISSUE TITLE
Skype can't connect

### ISSUE THREAD

**Issue by Sylencer90** [10se1ucgo/DisableWinTracking#86]
Even if i remove skype domains from the tool my skype is unable to connect ...turned off firewall & antivirus programm. I assume they added a new domain with 7.10 update. please fix it.

**Comment by mpmc** [comment]
Skype is having issues atm, http://heartbeat.skype.com/2015/09/skype_presence_issues.html

**Comment by 10se1ucgo** [comment]
Seems right, closing.
