### ISSUE TITLE
A few errors

### ISSUE THREAD

**Issue by expwnent** [10se1ucgo/DisableWinTracking#87]
I ran the program once as administrator. I'm not sure how serious the problems are (if at all).
---
Services: dmwappushsvc key successfully modified.
Services: DiagTrack key successfully modified.
Services: dmwappushsvc unable to be stopped.
Services: Diagnostics Tracking Service successfully stopped.
Services: Diagnostics Tracking Service unable to be stopped.
DiagTrack Log: Succesfully cleared and locked.
Telemetry: AllowTelemetry key successfully modified.
Domain block: Domains succesfully appended.
IP Blocking: Succesfully blocked.
WifiSense/Defender: Unable to modify Windows Defender Spynet key.
WifiSense/Defender: Unable to modify Windows Defender Sample Submission key.
WifiSense/Defender: WifiSense Open-ness key successfully modified.
WifiSense/Defender: WifiSense Credential Share key successfully modified.
WifiSense/Defender: Windows Defender Delivery Optimization Download key successfully modified.
OneDrive: ListPin key successfully modified.
OneDrive: FileSync key successfully modified.
OneDrive: Succesfully uninstalled.
Done. It's recommended that you reboot as soon as possible for the full effect.
If any errors were found, please make a GitHub ticket with the contents of DisableWinTracking.log
---
10:51:54 INFO: DisableWinTracking Version: 2.4.3

10:51:54 ERROR: Services: dmwappushsvc unable to be stopped. THIS IS ONLY AN ISSUE IF THIS IS YOUR FIRST TIME RUNNING THIS PROGRAM! Please DO NOT submit issues on GitHub otherwise.
Traceback (most recent call last):
  File "<string>", line 373, in disableservice
  File "disablewintracking\win32serviceutil", line 409, in StopService
  File "disablewintracking\win32serviceutil", line 320, in ControlService
error: (1062, 'ControlService', 'The service has not been started.')

10:51:54 ERROR: Services: Diagnostics Tracking Service unable to be stopped. THIS IS ONLY AN ISSUE IF THIS IS YOUR FIRST TIME RUNNING THIS PROGRAM! Please DO NOT submit issues on GitHub otherwise.
Traceback (most recent call last):
  File "<string>", line 373, in disableservice
  File "disablewintracking\win32serviceutil", line 409, in StopService
  File "disablewintracking\win32serviceutil", line 320, in ControlService
error: (1061, 'ControlService', 'The service cannot accept control messages at this time.')

10:51:55 ERROR: Registry: Unable to modify Windows Defender Spynet key.
Traceback (most recent call last):
  File "<string>", line 487, in modifyregistry
WindowsError: [Error 5] Access is denied

10:51:55 ERROR: Registry: Unable to modify Windows Defender Sample Submission key.
Traceback (most recent call last):
  File "<string>", line 487, in modifyregistry
WindowsError: [Error 5] Access is denied
---

**Comment by expwnent** [comment]
I don't know how to disable github formatting, so here's a pastebin link in case it matters: http://pastebin.com/AaYHBVmK

**Comment by 10se1ucgo** [comment]
This is okay, windows is protecting Windows Defender keys. I'll look for a work around next update.
