### ISSUE TITLE
this app keep crash

### ISSUE THREAD

**Issue by MrJaf** [10se1ucgo/DisableWinTracking#89]
this app cant uninstall any app on windows and keep get " not responding " 
**INFORMATION:**

* Windows 10 Edition (Pro)
* Architecture (64bit): 
* Options used:

**LOG:**

```python
this txt file is empty  DISABLEWINTRACKING.LOG
```

**Comment by 10se1ucgo** [comment]
It takes time, around 30 seconds per app, and is stated in the tooltip. This is not an issue with the program, but rather Windows PowerShell.
