### ISSUE TITLE
[Idea]  Add "Disable Office 2016 telemetry" option

### ISSUE THREAD

**Issue by s0rg0** [10se1ucgo/DisableWinTracking#90]
I know that newer Office suites come with cloud/background "features" which users might like to disable/remove, similar to the "Uninstall OneDrive" option already available. I got the idea from this program (read the application description): https://kat.cr/destroy-windows-10-spying-1-5-0-build-448-portable-t11320518.html
:-)

**Comment by Draxler** [comment]
Destroy Windows 10 Spying; 
This is open source software here at Github. You can look into it:
https://github.com/Nummer/Destroy-Windows-10-Spying

**Comment by s0rg0** [comment]
Thanks!

**Comment by 10se1ucgo** [comment]
I'll implement this next major release.

**Comment by s0rg0** [comment]
Yes, that makes me -- and many others I'm sure -- very happy! The mostly-useless/bloat-y online "features" that come with Office suites is mildly infuriating. You and Ruined1 are angels on this earth. ♡

**Comment by Ruined1** [comment]
Telemetry blocking host entries are already made, available in dwt.py starting on line 317.
