### ISSUE TITLE
Bing.com is disabled due to [NOTABUG]

### ISSUE THREAD

**Issue by stisev** [10se1ucgo/DisableWinTracking#93]
Fyi. You locked the other thread so I couldn't comment. I didn't have a 'menu' option until I downloaded the newest version.  Your suggestion to remove bing.com did not help (since bing.com is not an entry), so I took matters into my hands!  Also, FYI: reverting changes did not remove the Windows firewall exceptions created. I had to go in and manually disable each one and see which was the offender.

Here is the solution:
http://i.imgur.com/cA3pq8y.png

  IP address:   204.79.197.200
  Host name:    a-0001.a-msedge.net
  Domain name:  a-msedge.net
  Top level:    NET (Network)

You may want to consider removing that entry or at least keeping it OFF by default as a LOT of people use Bing and don't intend on disabling it when using this tool. :(

**Comment by Ruined1** [comment]
@stisev, i truly don't know a single person who uses Bing, that includes my clients, and i fix computers for a couple major corporations. Most people use Google and those who don't know how to choose are usually using Yahoo as their default. In all my career I have yet to find a single person who intentionally uses Bing, not dating there aren't people who use it, but let's not over exaggerate... That being said, I'm on a mobile right now, I will review the issue at a later time when a PC is available...

**Comment by stisev** [comment]
Hi,
No worries. Actually I don't use Bing. I prefer Google, but Bing Images is
actually not half bad.

Thanks for the quick replies. I solved it on my end, so the ball is in your
court :)

**Comment by 10se1ucgo** [comment]
I'll implement IP block settings now, and point out that 204.79.197.200 breaks Bing.

**Comment by SuperMasterBlasterLaser** [comment]
@Ruined1 I use bing sometimes. When Google blocks searching when I share my internet with other devices and thinks that I'm bot.

**Comment by Ruined1** [comment]
@SuperMasterBlasterLaser i never said it wasn't used,i just said i haven't seen it used intentionally as a primary search engine

**Comment by 10se1ucgo** [comment]
Whatever, it's irrelevant. I'm closing this as it's not really a bug. Settings for IP blocking soon
