### ISSUE TITLE
Freeze and crash while uninstalling apps

### ISSUE THREAD

**Issue by icheyne** [10se1ucgo/DisableWinTracking#95]
DisableWinTracking freezes while trying to uninstall apps and then crashes without any error message.

No apps are uninstalled.

The log file stays empty.

**Comment by 10se1ucgo** [comment]
How many apps are you trying to uninstall?

**Comment by icheyne** [comment]
All except Camera and Xbox.

**Comment by 10se1ucgo** [comment]
Hmmm. I know it freezes because PowerShell takes a long time, but not sure why it crashes. I'll look into this.

**Comment by icheyne** [comment]
I alt-tabbed away and did other tasks. When I came back to
DisableWinTracking's window, it was unresponsive.

**Comment by 10se1ucgo** [comment]
It's supposed to be because PowerShell is slow. I'll see if I can implement multithreading.

**Comment by Ruined1** [comment]
@10se1ucgo if you want me to take this one, so you can work on more important things (like that registry issue I just can't solve lol) just assign it to me and I'll get on it.

**Comment by 10se1ucgo** [comment]
@Ruined1 Nah it's fine, the solution is simple :P Use `subprocess.Popen()` instead of `subprocess.call()`, as Popen will create a separate window (therefore a thread, I think?) for each command, and run it.

Example:

![subprocess.call](http://i.imgur.com/IctZKJA.png)
![subprocess.Popen](http://i.imgur.com/p4TO1Gn.png)

**Comment by Ruined1** [comment]
@10se1ucgo that's not true multithreading, that's just opening up a bunch of single processes each with their own thread and relying on the processor to handle each thread. While you are running multiple threads at the same time, you're also running multiple processes, so it's not true multithreading :grin: None the less, getting it working and THEN optimizing is the key (as we discovered with for-looping registry changes and so on :rocket: TO THE MOON!

**Comment by 10se1ucgo** [comment]
It's close enough :P 

Though, it does lead to the issue of the console window opening before the command is even done being executed. Will need some more work.

**Comment by icheyne** [comment]
Good work. I'll test it if you like.

**Comment by 10se1ucgo** [comment]
@icheyne I'll send a built your way when I find a workaround to the console window opening prematurely.

**Comment by icheyne** [comment]
Great!
