### ISSUE TITLE
hosts

### ISSUE THREAD

**Issue by aarpro** [10se1ucgo/DisableWinTracking#96]
- your program modifies the hosts file - add MS domains 
- I would like to add MS domains in my router hosts file, protection for all my network
- MS domains adds and changes - you make changes in DisableWinTracking
- if you can place actual list MS domains on you repo ? as well AdBloks hosts , for example: http://winhelp2002.mvps.org/hosts.txt

**Comment by 10se1ucgo** [comment]
I can't seem to understand you, please try to get someone/something to translate for you. Thanks.

**Comment by aarpro** [comment]
I edited question - please see it. thk and sorry for my english

**Comment by 10se1ucgo** [comment]
No worries.

For your first question, I don't think it's actually possible for me to access your router settings and block the domains. However, if you'd like to do this yourself, here is a list: https://gist.github.com/10se1ucgo/fcb774d781a66ea9d31f

**Comment by aarpro** [comment]
thk
if you update it at this link? (when MS domains adds and changes)

**Comment by 10se1ucgo** [comment]
Yes, I will update that link if anything ever changes.
