### ISSUE TITLE
There is no way to see what settings were previously applied

### ISSUE THREAD

**Issue by AdKiller** [10se1ucgo/DisableWinTracking#98]
**INFORMATION:**

* Windows Edition (Home/Pro/Enterprise): Pro
* Architecture (32bit/64bit): 64
* Options used: 

**LOG:**

```python

14:17:00 INFO: Performing clutter control

14:17:01 INFO: DiagTrack box ticked

14:17:01 INFO: Service disable option ticked

14:17:01 INFO: DisableWinTracking Version: v2.5.1

14:17:01 INFO: Mode: Privacy

14:17:01 INFO: Telemetry box ticked

14:17:01 INFO: Host box ticked

14:17:01 INFO: Extra host box ticked

14:17:01 INFO: IP block box ticked

14:17:02 INFO: Defender/Wifisense box ticked

14:17:02 ERROR: Registry: Unable to modify Windows Defender Spynet key.
Traceback (most recent call last):
  File "<string>", line 575, in modifyregistry
WindowsError: [Error 5] Access is denied

14:17:02 ERROR: Registry: Unable to modify Windows Defender Sample Submission key.
Traceback (most recent call last):
  File "<string>", line 575, in modifyregistry
WindowsError: [Error 5] Access is denied

14:17:02 INFO: OneDrive box ticked

```

**Comment by 10se1ucgo** [comment]
I'm not understanding what you mean by this. Can you elaborate?

**Comment by 10se1ucgo** [comment]
If this is in regards to the Windows Defender keys not being able to be modified, it's a known issue. Otherwise, please re-open.

**Comment by AdKiller** [comment]
I mean when I check some boxes & apply some settings, the close the program, and come back to it later... all the check-boxes are cleared and there is no easy way to see what settings have been applied previously.

**Comment by Ruined1** [comment]
@AdKiller DisableWinTracking isn't written to work this way. If you're going to revert something, you should know exactly what you're going to revert. if you want to revert everything, just check everything. Even if you check something that wasn't done, it will still work as expected.
